Dilpreet | Stage | Thermal stage
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10062
Opened 2022-04-14 10:48 UTC by dilpreet77

https://app.clickup.com/t/23m4guw

2022-04-14 11:27 UTC, prateek-giddh requested changes
Do remove unused asset: apps/web-giddh/src/assets/images/templates/thermal_template.png

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
> +        console.log('field name', fieldName);
Avoid console logs

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    border: 1px solid #bfbfbf;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    background: #fff;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    background: #fff;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    background: #fff;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    background: #fff;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    background: aqua;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    border: 1px dashed #808080;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    background: #fff;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    border-color: #999;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    border-bottom: 1px solid #ccc;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    background: url("data:image/svg+xml;utf8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pgo8IS0tIEdlbmVyYXRvcjogQWRvYmUgSWxsdXN0cmF0b3IgMTkuMS4wLCBTVkcgRXhwb3J0IFBsdWctSW4gLiBTVkc
Please check this once by creating a production build on local machine as it sometime breaks

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    border-bottom: 1px solid #ccc;
Color var should be used

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.ts
> +    @Input() public fieldsAndVisibility: any = null;
JS Doc is missing on all the members

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        this.maxLength = +this.maxLength;
This statement is of no use as on line 21 `this.maxLength` is assigned a numeric value

2022-04-14 11:27 UTC, prateek-giddh commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        if (!this.maxLength) {
This if block is of no use as on line 21 `this.maxLength` is defined a non-zero value

2022-04-14 11:27 UTC, prateek-giddh commented on package.json
> +    "path-browserify": "^1.0.1",
Do check this if it's used

2022-04-14 11:27 UTC, prateek-giddh commented on tsconfig.json
> +                "./node_modules/path-browserify"
Do check this if this is used

2022-04-14 12:13 UTC, ravinderwalkover requested changes

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
> +    public defaultTemplate: any;
add js doc

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
> +        private _invoiceTemplatesService: InvoiceTemplatesService) {
don't use underscore

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
> +            select((s) => s.receipt.voucher),
don't use variable name with single character

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
> +
remove blank line

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
> +    public printThermal() {
add return type

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                    fieldsAndVisibility?.table.date &&
check if date condition should have been checked here?

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                    fieldsAndVisibility?.table.date &&
check if date condition should have been checked here?

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                    fieldsAndVisibility?.table.date &&
check if date condition should have been checked here?

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                    fieldsAndVisibility?.table.date &&
check if date condition should have been checked here?

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> -                            <tr>
this should not have been removed. make it conditional

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                name="totalQ"
```suggestion
                                name="totalQuantityCheck"
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                            customTemplate?.templateType === 'gst_template_a' &&
```suggestion
                            (customTemplate?.templateType === 'gst_template_a' ||
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                            customTemplate?.templateType === 'gst_template_e' &&
```suggestion
                            customTemplate?.templateType === 'gst_template_e') &&
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
> +                        <!-- <li (click)="onDesignChange('thermal_template', 'thermal_template')">
remove commented code

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
> +        console.log('field name', fieldName);
remove console logs

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.html
> +    <!-- GST TEMPLATE *ngSwitchCase="'thermal_template'" -->
remove commented code

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.html
> +                                        <!-- <tr *ngIf="fieldsAndVisibility.header.dueDate?.display">
remove commented code

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.html
> +                                    <!-- *ngIf="fieldsAndVisibility.footer.message1?.display" -->
remove commented code

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +.companyTitle {
don't use camel case

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +@import "../../../../../../../assets/css/color.scss";
remove this

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +/*
remove all commented code from this file

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.ts
> +
remove this space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.ts
> +    @Input() public fieldsAndVisibility: any = null;
add JS doc for all variables and methods

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.ts
> +    public ngOnInit() {
add return type for all methods

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/printer.format.service.ts
> +  public formatCenter(data) {
add return type for all methods

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/printer.format.service.ts
> +  public formatCenter(data) {
add argument type in all methods

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/printer.format.service.ts
> +    let text = this.doubleFontSize + data + this.standardFontSize;
format code

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove this space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        /** This will use for intialized entry tax */
```suggestion
        /** This will use for initialized entry tax */
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove blank line

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +            qr = "SELLER DETAILS" + this.printerFormat.lineBreak + "GSTIN - " + request?.company?.billingDetails?.taxNumber + this.printerFormat.lineBreak + this.printerFormat.lineBreak + "INVOICE DE
make GSTIN conditional based on company country

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        }
format file

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        let accountAddress
```suggestion
        let accountAddress;
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        let biilingGstinNumber;
```suggestion
        let billingGstinNumber;
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        let discAmountField;
```suggestion
        let discountAmountField;
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove extra space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove extra space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove extra space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +            let quantity
```suggestion
            let quantity;
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +            totalQty += +quantity;
```suggestion
            totalQty += quantity;
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +            if (itemName.length === 0) {
add nulity check for all conditions where length is getting checked

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +                const itemNameShowHide = itemNameShow?.length ? this.justifyText(itemNameShow, itemDetails) : this.justifyText(itemDetails)
```suggestion
                const itemNameShowHide = itemNameShow?.length ? this.justifyText(itemNameShow, itemDetails) : this.justifyText(itemDetails);
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +            const productsFieldShowHide = productsField?.length ? this.justifyText(productsField, itemDetailsField) : this.justifyText(itemDetailsField)
```suggestion
            const productsFieldShowHide = productsField?.length ? this.justifyText(productsField, itemDetailsField) : this.justifyText(itemDetailsField);
```

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove extra space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove extra space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove extra space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +
remove extra space

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +    public justifyText(a: any, b: any = "") {
add return type

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +    public justifyText(a: any, b: any = "") {
add proper variable names

2022-04-14 12:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        let z = +lengthOfA + lengthOfB;
don't use single character variable name

2022-04-14 12:13 UTC, ravinderwalkover commented on package.json
> +    "path-browserify": "^1.0.1",
remove this

2022-04-14 12:13 UTC, ravinderwalkover commented on tsconfig.json
> +            "path": [
remove this

2022-04-14 14:04 UTC, ravinderwalkover requested changes

2022-04-14 14:04 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.ts
> +     * Lifecycle hook use for on destroy compoenent
```suggestion
     * Lifecycle hook use for on destroy component
```

2022-04-14 14:04 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +    public justifyText(characterA: any, characterB: any = "") : any {
rename variables and JS doc

2022-04-14 14:04 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/thermal.service.ts
> +        let z = +lengthOfA + lengthOfB;
rename variable

2022-04-15 04:57 UTC, prateek-giddh approved these changes

2022-07-04 11:32 UTC, ravinderwalkover requested changes

2022-07-04 11:32 UTC, ravinderwalkover commented on .vscode/settings.json
> +    }
this file shouldn't be part of PR

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
> +        this.invoiceTemplatesService.getAllCreatedTemplates("sales").pipe(takeUntil(this.destroyed$)).subscribe((res) => {
comment this api call

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === 'gst_template_a' ||
add condition of 12 for thermal only and 15 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === "gst_template_a" ||
add condition of 12 for thermal only and 15 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === 'gst_template_a' ||
add condition of 14 for thermal only and 15 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === "gst_template_a" ||
add condition of 14 for thermal only and 15 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === 'gst_template_a' ||
add condition of 8 for thermal only and 12 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === "gst_template_a" ||
add condition of 8 for thermal only and 12 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === 'gst_template_a' ||
add condition of 9 for thermal only and 10 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === "gst_template_a" ||
add condition of 9 for thermal only and 10 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === 'gst_template_a' ||
add condition of 5 for thermal only and 6 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                        customTemplate.templateType === "gst_template_a" ||
add condition of 5 for thermal only and 6 for rest

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                voucherType === 'sales'
confirm this

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                    customTemplate?.templateType === 'gst_template_a' ||
add reverse condition for thermal only

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                            (customTemplate?.templateType === 'gst_template_a' ||
add reverse condition for thermal

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                            customTemplate?.templateType === 'gst_template_a' ||
add reverse condition for thermal

2022-07-04 11:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/general.service.ts
> +    public convertV1ResponseInV2(data: any): any {
add JS doc

2022-07-04 11:53 UTC, dilpreet77 commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> +                                voucherType === 'sales'
Confirmed with Kriti this is correct

2022-07-05 07:38 UTC, ravinderwalkover approved these changes

2022-07-05 07:42 UTC, merged