Shivansh | Test | Replaced checkboxes with toggle button
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10138
Opened 2022-04-29 06:12 UTC by shivanshRawat14

https://app.clickup.com/t/2839xxp

2022-04-29 06:59 UTC, ravinderwalkover requested changes

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
> +        this.addStockForm.controls['enablePurchase']?.patchValue(false);
remove this

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/invoice.module.ts
> +        SharedModule,
revert changes of this file

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
> +
remove this space

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.html
> +                                        <mat-slide-toggle color="primary" formControlName="cancelledEntries">
test this

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.html
> +                        <mat-slide-toggle color="primary" name="withInvoiceNumber" [(ngModel)]="withInvoiceNumber">
test this

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.html
> +                        <mat-slide-toggle color="primary" name="balanceTypeAsSign" [(ngModel)]="balanceTypeAsSign">
test this

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                        [status]="razorPayObj.autoCapturePayment"
change this

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
> +                                                        [(status)]="
test this

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +    public varTest = this.initialGstDetailsForm;
remove if unused

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
> +                                                        [status]="
test this

2022-04-29 06:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/userDetails/userDetails.component.ts
> +import { fakeAsync } from '@angular/core/testing';
remove this if unused

2022-04-29 06:59 UTC, ravinderwalkover commented on package.json
> +    "@angular/animations": "^12.1.1",
revert this

2022-04-29 10:03 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
> +        this.addStockForm.controls['enablePurchase']?.patchValue(false);
removed

2022-04-29 10:05 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/invoice/invoice.module.ts
> +        SharedModule,
reverted

2022-04-29 10:07 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
> +
removed

2022-04-29 10:39 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                        [status]="razorPayObj.autoCapturePayment"
changed

2022-04-29 10:41 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +    public varTest = this.initialGstDetailsForm;
removed

2022-04-29 10:42 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/userDetails/userDetails.component.ts
> +import { fakeAsync } from '@angular/core/testing';
removed

2022-04-29 10:43 UTC, shivanshRawat14 commented on package.json
> +    "@angular/animations": "^12.1.1",
reverted

2022-04-29 10:44 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.html
> +                        <mat-slide-toggle color="primary" name="withInvoiceNumber" [(ngModel)]="withInvoiceNumber">
tested

2022-04-29 10:44 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.html
> +                        <mat-slide-toggle color="primary" name="balanceTypeAsSign" [(ngModel)]="balanceTypeAsSign">
tested

2022-04-29 12:37 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.html
> +                                        <mat-slide-toggle color="primary" formControlName="cancelledEntries">
tested

2022-05-05 11:31 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
> +                                                        [(status)]="
tested

2022-05-05 12:30 UTC, ravinderwalkover approved these changes

2022-05-05 13:01 UTC, prateek-giddh requested changes

2022-05-05 13:01 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/app.constant.ts
> +export enum BOOTSTRAP_TOGGLE_SWITCH {
Enums are always named in CamelCase
```suggestion
export enum BootstrapToggleSwitch {
```

2022-05-05 13:01 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
> +        this.invoiceSetting.showSeal = false;
Can we assign these default values in the class's constructor itself called at https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/blob/3a08674c9ccb75377f2dafba692a694f23730db1/apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts#L30

2022-05-05 13:01 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.ts
> +        this.invoiceSettings.purchaseBillSettings.sendThroughGmail = false;
Can we assign these default values at line https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/blob/3a08674c9ccb75377f2dafba692a694f23730db1/apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.ts#L25

2022-05-06 06:01 UTC, prateek-giddh approved these changes

2022-05-06 06:03 UTC, merged