Dilpreet | Test | Mandatory sign not shown on Field limit
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10176
Opened 2022-05-10 11:11 UTC by dilpreet77

https://app.clickup.com/t/28ejg0k

2022-05-10 11:14 UTC, prateek-giddh approved these changes

2022-05-11 11:00 UTC, prateek-giddh requested changes

2022-05-11 11:00 UTC, prateek-giddh commented on apps/web-giddh/src/app/new-inventory/component/stock-create-edit/stock-create-edit.component.ts
> +                        label: result.name +" ("+result.code+")",
```suggestion
                        label: `${result.name} (${result.code})`,
```

2022-05-11 12:41 UTC, prateek-giddh approved these changes

2022-05-11 13:13 UTC, ravinderwalkover approved these changes

2022-05-11 13:13 UTC, merged