Dilpreet | Stage | Prod - Undefined is coming in date on sales/purchase register page (for V2 companies)
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10368
Opened 2022-07-02 12:04 UTC by dilpreet77

https://app.clickup.com/t/2fz21cd

2022-07-02 12:21 UTC, prateek-giddh requested changes

2022-07-02 12:21 UTC, prateek-giddh commented on apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.ts
> +        console.log(selecteddate, this.monthNames);
Avoid console logs

2022-07-02 12:50 UTC, prateek-giddh approved these changes

2022-07-04 06:02 UTC, ravinderwalkover approved these changes

2022-07-05 11:50 UTC, merged