Shivansh | Stage | Create a downloads page under other category of all items page
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10377
Opened 2022-07-05 09:40 UTC by shivanshRawat14

https://app.clickup.com/t/2hctrbd

2022-07-14 12:22 UTC, prateek-giddh commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +        dialogRef.afterClosed().subscribe(result => {
Avoid console logs

2022-07-14 12:22 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/downloads/components/downloads-json/downloads-json.component.html
> +            <h3 _ngcontent-kab-c237="">{{ localeData.filter }}</h3>
```suggestion
            <h3>{{ localeData.filter }}</h3>
```

2022-07-14 12:22 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    /**
Do format the code

2022-07-14 12:22 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    /**
Do format the JS doc

2022-07-14 12:22 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    /**
Do format the JS doc

2022-07-14 12:22 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    public downloadData(data: any): void {
Avoid empty method

2022-07-14 12:27 UTC, dilpreet77 commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    public downloadData(data: any): void {
Sir, after this is completed I will work on downloading the export

2022-07-14 12:30 UTC, ravinderwalkover requested changes

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads-json/downloads-json.component.ts
> +    styleUrls: ['./downloads-json.component.scss']
add changeDetectionStrategy

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.html
> +                <button mat-raised-button class="btn-success min-width-100 mr-l1" (click)="resetFilter()">
use same class here which is getting used everywhere. currently it's of green color

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.html
> +                            (click)="element?.status === 'COMPLETED' ? downloadData(element) : ''"
no need of condition here

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    styleUrls: ['./downloads.component.scss'],
use changeDetectionStrategy

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +        this.universalDate$.subscribe(a => {
don't use single character variable

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    public openDialog(row: any): void {
row variable is not included in JS doc of this function

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +        dialogRef.afterClosed().subscribe(result => {
what's the use of this ?

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +  */
do code formatting

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    public getDownloads(resetPage?: boolean) {
add return type

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    public getDownloads(resetPage?: boolean) {
include parameters in JS doc as well

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +                    let today = moment().format('DD-MM-YYYY');
```suggestion
                    let today = moment().format(GIDDH_DATE_FORMAT);
```

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +                        result.expireAt = "Expired"
use translation variable

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +                    if (result.expireAt > today) {
expiry date should be shown even if today

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    public dateSelectedCallback(value?: any, from?: any): void {
include all variables in JS doc

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +    public downloadData(data: any): void {
remove this function if unused

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +        this.universalDate$.subscribe(a => {
don't use single character variable

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/app.module.ts
> +        MatTableModule,
what's the use of this module here?

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/all-items/en.json
> +                    "link": "/pages/download",
```suggestion
                    "link": "/pages/downloads",
```

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/all-items/hi.json
> +                    "link": "/pages/download",
```suggestion
                    "link": "/pages/downloads",
```

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/all-items/mr.json
> +                    "link": "/pages/download",
```suggestion
                    "link": "/pages/downloads",
```

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/downloads/en.json
> +    "download": "Download",
this is available in common locale already

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/downloads/en.json
> +    "status": "Status"
this is available in common locale already

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/downloads/en.json
> +    "filter": "Filter",
this is available in common locale already

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/downloads/en.json
> +    "no_logs": "No Record Found",
this is available in common locale already

2022-07-14 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/downloads/en.json
> +    "services": "Services",
this is available in common locale already

2022-07-14 13:33 UTC, dilpreetsinghofficial commented
PR review done from side

2022-07-14 13:46 UTC, ravinderwalkover approved these changes

2022-07-14 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/service.module.ts
> +                CustomFieldsService,
remove custom field service

2022-07-14 13:47 UTC, ravinderwalkover requested changes
test everything

2022-07-14 14:30 UTC, ravinderwalkover approved these changes

2022-07-21 12:08 UTC, dilpreet77 commented
self reviewed

2022-07-21 12:09 UTC, prateek-giddh approved these changes

2022-07-21 12:44 UTC, ravinderwalkover requested changes

2022-07-21 12:44 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/service.module.ts
> -import { CustomFieldsService } from "./custom-fields.service";
why is this removed?

2022-07-21 12:44 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/shared.module.ts
> +import { CustomFieldsService } from '../services/custom-fields.service';
remove this service from this file

2022-07-26 06:06 UTC, ravinderwalkover approved these changes

2022-07-26 08:34 UTC, merged