Dilpreet | Test | Integrate bill to bill for export in ledger entry
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10454
Opened 2022-07-20 13:18 UTC by dilpreet77

https://app.clickup.com/t/2khener

2022-07-20 13:22 UTC, prateek-giddh approved these changes

2022-07-21 07:57 UTC, ravinderwalkover requested changes

2022-07-21 07:57 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.ts
> +    public emailTypeBillToBill: string;
add js doc

2022-07-21 07:57 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.html
> +                        emailTypeSelected === 'detailed' ||
fix condition

2022-07-21 07:57 UTC, ravinderwalkover commented on apps/web-giddh/src/app/downloads/components/downloads/downloads.component.ts
> +   * @memberof CustomFieldsListComponent
fix js doc

2022-07-21 07:57 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.ts
> +        this.store.pipe(select(p => p.ledger.account), takeUntil(this.destroyed$)).subscribe(ledgerAccount => {
avoid single character variable names

2022-07-21 07:57 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.ts
> +                } else if (response.message) {
```suggestion
                } else if (response.body.message) {
```

2022-07-21 07:57 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.ts
> +                if (response.status === "success") {
```suggestion
                if (response?.status === "success") {
```

2022-07-21 07:57 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.ts
> +                    let blob = this.generalService.base64ToBlob(response.body.file, 'application/vnd.ms-excel', 512);
```suggestion
                    let blob = this.generalService.base64ToBlob(response?.body?.file, 'application/vnd.ms-excel', 512);
```

2022-07-21 07:59 UTC, ravinderwalkover requested changes
fix changes

2022-07-21 08:02 UTC, dilpreet77 commented
PR reviewed done

2022-07-21 09:16 UTC, ravinderwalkover approved these changes

2022-07-21 09:16 UTC, merged