Ravinder | Stage | New Inventory Code
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10512
Opened 2022-07-27 12:37 UTC by ravinderwalkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2022-07-27 12:58 UTC, shivanshRawat14 commented on apps/web-giddh/src/app/new-inventory/component/about-combo-detail/about-combo-detail.component.scss
> +@import "../../../../assets/css/color.scss";
Remove this line

2022-07-27 13:48 UTC, dilpreet77 requested changes

2022-07-27 13:48 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.ts
> +          <a class="btn btn-link btn-xs pull-right" [routerLink]="'/pages/new-inventory/stock/edit/' + item.uniqueName" *ngIf="!isMobileScreen && (activeStockUniqueName$ | async) === item.uniqueName"
Please revert the code according to old inventory work

2022-07-27 13:48 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
> +                        [routerLink]="'/pages/new-inventory/stock/edit/' + stockUniqueName"
Please revert the code according to old inventory work

2022-07-27 13:48 UTC, dilpreet77 commented on apps/web-giddh/src/app/new-inventory/component/about-group-detail/about-group-detail.component.html
> +                                    [routerLink]="['/pages/new-inventory/adjust-inventory']"
Please check this

2022-07-27 13:48 UTC, dilpreet77 commented on apps/web-giddh/src/app/new-inventory/component/about-group-detail/about-group-detail.component.html
> +                        [routerLink]="['/pages/new-inventory/create-new-inventory']"
Please check this

2022-07-27 13:48 UTC, dilpreet77 commented on apps/web-giddh/src/app/new-inventory/component/create-new-inventory-component/create-new-inventory.component.html
> +            <button mat-icon-button class="ml-3" style="font-size: 25px" [routerLink]="['/pages/new-inventory']">
Please check this

2022-07-27 13:48 UTC, dilpreet77 commented on apps/web-giddh/src/app/services/apiurls/inventory.api.ts
> +    },
Please check this

2022-07-27 13:48 UTC, dilpreet77 commented on apps/web-giddh/src/app/services/inventory.service.ts
> +
Please check this file

2022-07-27 13:48 UTC, dilpreet77 commented on apps/web-giddh/src/assets/locale/inventory/group-stockreport/en.json
> -    "search_product": "Search Product",
Please check this file

2022-07-27 15:46 UTC, dilpreet77 approved these changes

2022-07-28 05:30 UTC, prateek-giddh approved these changes

2022-07-28 05:30 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/new-inventory/component/about-group-detail/about-group-detail.component.ts
> +    /*datepicker funcation*/
Improper JS doc

2022-07-28 05:30 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/new-inventory/component/about-group-detail/about-group-detail.component.ts
> +    /* It will show/hide hsn code field */
Improper JS doc

2022-07-28 05:30 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +    /*datepicker funcation*/
Improper JS doc

2022-07-28 05:30 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +    /* Aside pane toggle fixed class */
Improper JS doc

2022-07-28 05:30 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +    /* Create combo aside pane open function */
Improper JS doc

2022-07-28 05:30 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/new-inventory/component/combo-list/inventory-combo-list.component.ts
> +        this.imgPath = (isElectron || isCordova) ? 'assets/images/' : AppUrl + APP_FOLDER + 'assets/images/';
isCordova is not needed

2022-07-28 05:30 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/new-inventory/component/inventory-dashboard/inventory-dashboard.component.ts
> +    /**
Invalid JS doc

2022-07-28 05:30 UTC, the-prateek-mishra commented on apps/web-giddh/src/app/new-inventory/component/stock-balance/stock-balance.component.ts
> +export class StockBalanceComponent implements OnInit, OnDestroy {
Format this file

2022-07-28 05:30 UTC, prateek-giddh commented on apps/web-giddh/src/assets/css/style-2.scss
> +.myPanelClass {
Avoid camelCase names in class

2022-07-28 06:12 UTC, merged