Dilpreet | Stage | For bank imported transaction entry pop up should not get overlap with account dropdown on ledger
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10561
Opened 2022-07-31 19:09 UTC by dilpreet77

2022-07-31 19:11 UTC, dilpreet77 commented
REVIEWED

2022-08-01 05:10 UTC, prateek-giddh approved these changes

2022-08-01 05:12 UTC, prateek-giddh requested changes

2022-08-01 05:12 UTC, prateek-giddh commented on apps/web-giddh/src/app/material-ledger/ledger.component.html
> +                                                                            'account-placeholder no': true,
Please check class name
```suggestion
                                                                            'account-placeholder-no': true,
```

2022-08-01 05:12 UTC, prateek-giddh commented on apps/web-giddh/src/app/material-ledger/ledger.component.html
> +                                                                            'account-placeholder yes': true,
Please check class name
```suggestion
                                                                            'account-placeholder-yes': true,
```

2022-08-01 05:12 UTC, prateek-giddh commented on apps/web-giddh/src/app/material-ledger/ledger.component.html
> +                                                                            'account-placeholder yes': true,
Please check class name
```suggestion
                                                                            'account-placeholder-yes': true,
```

2022-08-01 06:18 UTC, prateek-giddh approved these changes

2022-08-01 14:07 UTC, dilpreet77 commented
reviewed

2022-08-01 14:08 UTC, ravinderwalkover approved these changes

2022-08-01 14:09 UTC, merged