Dilpreet | Test | Fixed exception for undefined uniqueName
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10576
Opened 2022-08-01 16:59 UTC by dilpreet77

2022-08-02 15:35 UTC, ravinderwalkover requested changes

2022-08-02 15:35 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.ts
> +                    value: this.activeCompany ? this.activeCompany?.uniqueName : '',
revert

2022-08-02 15:35 UTC, ravinderwalkover commented on apps/web-giddh/src/app/material-ledger/ledger.component.ts
> +            if (transactions) {
incorrect condition

2022-08-04 06:12 UTC, prateek-giddh approved these changes

2022-08-04 07:19 UTC, merged