Dilpreet |Test | GROUP_NOT_FOUND fixed error
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10596
Opened 2022-08-04 20:01 UTC by dilpreet77

https://app.clickup.com/t/29prnca

2022-08-05 08:43 UTC, ravinderwalkover requested changes

2022-08-05 08:43 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> -                if (response.uniqueName !== this.activeGroupUniqueName) {
can't remove this code

2022-08-08 05:22 UTC, prateek-giddh approved these changes

2022-08-08 05:22 UTC, ravinderwalkover approved these changes

2022-08-08 05:23 UTC, merged