Dilpreet | Stage | Integrate mobile number library on voucher form
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10628
Opened 2022-08-08 14:40 UTC by dilpreet77

https://app.clickup.com/t/2p1fd62

2022-08-09 06:20 UTC, prateek-giddh approved these changes

2022-08-09 09:23 UTC, dilpreet77 commented
reviewed

2022-09-06 07:19 UTC, ravinderwalkover requested changes

2022-09-06 07:19 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/shared.module.ts
> +        NgxIntlTelInputModule,
remove this

2022-09-06 07:48 UTC, dilpreet77 commented
Reviewed

2022-09-06 08:52 UTC, ravinderwalkover approved these changes

2022-09-06 08:52 UTC, merged