Dilpreet | Test | UI: Integrate API to view all Imports
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10765
Opened 2022-09-03 10:09 UTC by dilpreet77

(https://app.clickup.com/t/2r66161)

2022-09-03 10:09 UTC, dilpreet77 commented
Reviewed

2022-09-05 08:59 UTC, prateek-giddh approved these changes

2022-09-05 09:49 UTC, dilpreet77 commented
Reviewed

2022-09-05 12:16 UTC, ravinderwalkover requested changes

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/imports/imports.module.ts
> +        GiddhPageLoaderModule, SharedModule]
don't import shared module

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/imports/imports/imports.component.ts
> +            // console.log(response);
remove commented code

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/imports/imports/imports.component.ts
> +            this.importRequest.from = null;
fix from/to

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/models/api-models/imports.ts
> +    count?: any;
correct data type and formatting

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/models/api-models/imports.ts
> +    branchUniqueName?: string;
```suggestion
    public branchUniqueName?: string;
```

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/imports.service.ts
> +
remove blank line

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/imports.service.ts
> +    public getImports(importsRequest: ImportsRequest): Observable<BaseResponse<ImportsResponse, ImportsRequest>> {
add js doc

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/imports/en.json
> +    "by":"By",
use from common locale

2022-09-05 12:16 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/imports/en.json
> +    "count": "Count",
add in common

2022-09-05 12:59 UTC, ravinderwalkover requested changes

2022-09-05 12:59 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/hi.json
> +    "app_count": "गिनती करना"
fix this

2022-09-05 13:07 UTC, dilpreet77 commented
DONE

2022-09-05 13:43 UTC, ravinderwalkover approved these changes

2022-09-05 14:13 UTC, merged