Dilpreet |Stage | UI - Currect the GSTR 1 and GSTR 2 Design.
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10776
Opened 2022-09-06 14:05 UTC by dilpreet77

https://app.clickup.com/t/2nau7vb

2022-09-07 06:46 UTC, dilpreet77 commented
Reviewed

2022-09-12 08:08 UTC, dilpreet77 commented
Reviewed

2022-09-12 08:22 UTC, prateek-giddh approved these changes

2022-09-12 09:23 UTC, ravinderwalkover requested changes

2022-09-12 09:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/modals/push-to-portal/push-to-portal.component.ts
> +export class PushtToPortalComponent {
```suggestion
export class PushToPortalComponent {
```

2022-09-12 09:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/modals/push-to-portal/push-to-portal.component.ts
> + * This will use for download success sheet
fix formatting

2022-09-12 09:23 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/gst/en.json
> +        "excel_file_support":"1. This Excel file support , GSTIN Portal Offline tool.",
```suggestion
        "excel_file_support":"1. This Excel file support GSTIN Portal Offline tool.",
```

2022-09-12 09:23 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/gst/en.json
> +        "organised_accountant":" 2. Its an organised way to give to any accountant/CA.",
```suggestion
        "organised_accountant":"2. It's an organised way to give to any accountant/CA.",
```

2022-09-12 09:23 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/gst/en.json
> +        "json_support":"JSON file support by GST Portal",
```suggestion
        "json_support":"JSON file supported by GST Portal",
```

2022-09-14 12:58 UTC, dilpreet77 commented
Reviewed

2022-09-14 13:03 UTC, ravinderwalkover approved these changes

2022-09-14 13:04 UTC, merged