Dilpreet |Test | UI - Currect the GSTR 1 and GSTR 2 Design.
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10793
Opened 2022-09-12 10:38 UTC by dilpreet77

https://app.clickup.com/t/2t8qaw3

2022-09-12 10:39 UTC, dilpreet77 commented
Reviewed

2022-09-12 11:26 UTC, prateek-giddh requested changes

2022-09-12 11:26 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +                                {{ dayjs(selectedMonth).format("MMMM YYYY") }}
`dayjs` method should not be called in HTML interpolation as it will be called on every change detection.

2022-09-12 11:26 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
> +                                {{ dayjs(selectedMonth).format("MMMM YYYY") }}
`dayjs` method should not be called in HTML interpolation as it will be called on every change detection.

2022-09-12 11:29 UTC, ravinderwalkover approved these changes

2022-09-13 14:06 UTC, ravinderwalkover approved these changes

2022-09-14 06:13 UTC, prateek-giddh approved these changes

2022-09-14 06:13 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
> +    public dayjs = dayjs;
This variable is of no use now

2022-09-14 06:55 UTC, prateek-giddh approved these changes

2022-09-14 07:03 UTC, merged