Dilpreet | Test | Remove implemented combine mobile no
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10845
Opened 2022-09-15 14:48 UTC by dilpreet77

https://app.clickup.com/t/2p1fd62

2022-09-16 05:16 UTC, dilpreet77 commented
Reviewed

2022-09-16 06:03 UTC, prateek-giddh approved these changes

2022-09-26 06:10 UTC, dilpreet77 commented
Reviewed

2022-09-26 06:18 UTC, ravinderwalkover requested changes

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +            utilsScript: 'https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.17/js/utils.js',
create url as constant

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +    public onlyPhoneNumber() {
add return type

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +        input.addEventListener('countrychange', () => {
remove blank event listener

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +    public isValidMobileNumber(ele: HTMLInputElement) {
add return type and js doc

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +        if (ele.value) {
```suggestion
        if (element?.value) {
```

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +    public isValidMobileNumber(ele: HTMLInputElement) {
```suggestion
    public isValidMobileNumber(element: HTMLInputElement) {
```

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +    public checkMobileNo(ele) {
```suggestion
    public checkMobileNo(element) {
```

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +    public checkMobileNo(ele) {
add return type and js doc

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +    public onlyPhoneNumber() {
add return type

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> +    public isValidMobileNumber(ele: HTMLInputElement) {
```suggestion
    public isValidMobileNumber(element: HTMLInputElement) {
```

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> +        if (ele.value) {
```suggestion
        if (element?.value) {
```

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> +    public isValidMobileNumber(ele: HTMLInputElement) {
add return type and js doc

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> +    public checkMobileNo(ele) {
add return type and js doc

2022-09-26 06:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> +    public onlyPhoneNumber() {
add return type and js doc

2022-09-26 06:56 UTC, ravinderwalkover requested changes

2022-09-26 06:56 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +        let mobileNo = this.intl.getNumber();
```suggestion
        let mobileNo = this.intl?.getNumber();
```

2022-09-26 06:56 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> +        let mobileNo = this.intl.getNumber();
```suggestion
        let mobileNo = this.intl?.getNumber();
```

2022-09-26 07:32 UTC, ravinderwalkover approved these changes

2022-09-26 07:32 UTC, merged