Dilpreet | Stage | Customer, Vendor, and Aging Report Page For New User
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #10944
Opened 2022-09-28 09:48 UTC by dilpreet77

https://app.clickup.com/t/2u541tw

2022-09-28 09:52 UTC, ravinderwalkover requested changes

2022-09-28 09:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/contact/contact.component.html
> +                                    *ngIf="sundryCreditorsAccounts?.length && sundryDebtorsAccounts?.length"
```suggestion
                                    *ngIf="sundryCreditorsAccounts?.length || sundryDebtorsAccounts?.length"
```

2022-09-28 09:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/contact/contact.component.html
> +                        *ngIf="isMobileScreen && sundryDebtorsAccounts?.length && sundryCreditorsAccounts?.length"
```suggestion
                        *ngIf="isMobileScreen && (sundryDebtorsAccounts?.length || sundryCreditorsAccounts?.length)"
```

2022-09-28 09:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/contact/contact.component.html
> +                <img class="customer-height" src="./assets/images/customer-vendor//stock-photo.png" alt="" />
```suggestion
                <img class="customer-height" src="{{imgPath}}customer-vendor/stock-photo.png" alt="" />
```

2022-09-30 06:42 UTC, prateek-giddh approved these changes

2022-09-30 06:48 UTC, merged