Dilpreet | Stage | UI work - HTML only
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #11406
Opened 2023-02-07 14:10 UTC by dilpreet77

https://app.clickup.com/t/85zrjyv9b

2023-02-24 07:02 UTC, ravinderwalkover requested changes

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/models/api-models/Inventory.ts
> +export class StockReportRequestNew {
Rename class

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/models/api-models/Inventory.ts
> +
reduce extra spaces

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.html
> +            [placeholder]="'Select Branch'"
multi language?

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.html
> +                    [placeholder]="'Searching  Stock Group , Multiple  Stocks, Multiple Variants'"
fix text

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/models/api-models/Inventory.ts
> +export class TransactionalStockReportResponse {
```suggestion
export class TransactionStockReportResponse {
```

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +    public VOUCHER_TYPES: any[] = [
why variable name is defined with capital letters and underscore?

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +    public CUSTOMISE_COLUMNS = [
why variable name is defined with capital letters and underscore?

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +     * This wii use for select filters in chiplist
```suggestion
     * This will use for select filters in chiplist
```

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +            if (this.stockReportRequest.stockGroupUniqueNames?.length > 0) {
remove if else and assign value directly since only 1 group is allowed

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +        this.inventoryService.searchStockTransactionReport(this.stockReportRequest).subscribe(response => {
add pipe

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +        if (!this.stockReportRequest.stockGroupUniqueNames || !this.stockReportRequest.stockUniqueNames) {
test this logic and consider variant also

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +        this.inventoryService.getStockTransactionReport(cloneDeep(this.stockReportRequest)).subscribe(response => {
add pipe

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +        this.inventoryService.getStockTransactionReportBalance(cloneDeep(this.stockReportRequest)).subscribe(response => {
add pipe

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +    public dateSelectedCallback(value?: any, from?: any): void {
remove usused variable

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +        this.changeDetection.detectChanges();
add for closed as well

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +    public filterByCheck(type: string) {
add return type

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +    public isFilterActive(): void {
add js doc

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +            this.changeDetection.detectChanges();
remove

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +        this.inventoryService.getStockTransactionReportColumns("INVENTORY_TRANSACTION_REPORT").subscribe(response => {
add pipe

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +
remove extra space

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +            this.inventoryService.saveStockTransactionReportColumns(saveColumnReq).subscribe(response => {
add pipe

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +            this.changeDetection.detectChanges();
remove

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.ts
> +                    this.toaster.showSnackBar("success", response?.body);
remove

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/new-inventory-advance-search/new-inventory-advance-search.component.ts
> +            label: "Outwards "
```suggestion
            label: "Outwards"
```

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/new-inventory-advance-search/new-inventory-advance-search.component.ts
> +            this.isMobileScreen = result.matches;
are we using this?

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/new-inventory-advance-search/new-inventory-advance-search.component.ts
> +            searching: Boolean
assign boolean value

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/new-inventory-advance-search/new-inventory-advance-search.component.ts
> +    public allowOnlyNumbers(event: any): boolean {
use available directive

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/new-inventory-advance-search/new-inventory-advance-search.component.ts
> +    public selectValue(value: any): void {
rename to expression

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/new-inventory-advance-search/new-inventory-advance-search.component.ts
> +            this.advanceSearchFormObj.expression = "GEATER_THAN";
fix spelling

2023-02-24 07:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/new-inventory-advance-search/new-inventory-advance-search.component.ts
> +            this.advanceSearchFormObj.expression = expression;
```suggestion
            this.advanceSearchFormObj.expression = "EQUALS";
```

2023-02-24 07:41 UTC, dilpreet77 commented on apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.html
> +            [placeholder]="'Select Branch'"
We can do this with item wise report

2023-02-24 08:11 UTC, dilpreet77 commented on apps/web-giddh/src/app/new-inventory/component/new-inventory-advance-search/new-inventory-advance-search.component.ts
> +            this.isMobileScreen = result.matches;
yes

2023-03-21 05:45 UTC, ravinderwalkover approved these changes

2023-03-21 05:48 UTC, merged