fix: Issues related to Ledger variant
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #11726
Opened 2023-05-16 13:07 UTC by prateek-giddh

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-05-16 13:15 UTC, ravinderwalkover requested changes

2023-05-16 13:15 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
> +        this.ledgerService.loadStockVariants(stockUniqueName).pipe(
add takeUntil

2023-05-16 13:15 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
> +                this.stockVariants$ = observableOf(res);
check if error response is handled

2023-05-16 13:15 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
> +            map((variants: IVariant[]) => variants.map((variant: IVariant) => ({label: variant.name, value: variant.uniqueName})))).subscribe(res => {
add takeUntil and check if error is handled

2023-05-17 05:07 UTC, prateek-giddh commented on apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
> +                this.stockVariants$ = observableOf(res);
Done

2023-05-17 05:07 UTC, prateek-giddh commented on apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
> +        this.ledgerService.loadStockVariants(stockUniqueName).pipe(
Done

2023-05-17 05:08 UTC, ravinderwalkover approved these changes

2023-05-17 05:08 UTC, merged