Dilpreet | Stage | Sales/Purchase register export related changes (Adding unique name and account parent group name)
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #12286
Opened 2023-08-01 11:20 UTC by dilpreet77

https://app.clickup.com/t/85zthqqv5

2023-08-02 12:30 UTC, ravinderwalkover requested changes

2023-08-02 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/sales-purchase-register-export/sales-purchase-register-export.component.ts
> +        let body = cloneDeep(this.inputData);
remove clonedeeo and add loader

2023-08-02 12:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/sales-purchase-register-export/sales-purchase-register-export.component.ts
> +        console.log(exportBodyRequest);
remove console

2023-08-04 09:55 UTC, prateek-giddh approved these changes

2023-08-04 09:56 UTC, merged