Nisha | Test | Convert cmd+k and help side bar in material
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #12297
Opened 2023-08-03 08:07 UTC by nisha-walkover

https://app.clickup.com/t/85ztj3nvh
https://app.clickup.com/t/85ztj3nyt

2023-08-03 13:46 UTC, ravinderwalkover requested changes

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.html
> +        <aside-help-support (closeAsideEvent)="matDialogRef.close()"></aside-help-support>
```suggestion
        <aside-help-support></aside-help-support>
```

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
> +            <div mat-dialog-close id="close" class="cursor-pointer" (click)="closeAsidePane($event)">
```suggestion
            <div mat-dialog-close id="close" class="cursor-pointer">
```

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
> +            <div mat-dialog-close id="close" class="cursor-pointer" (click)="closeAsidePane($event)">
delete closeAsidePane method from .ts file also if it's unused

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +    public matDialogRef: any;
remove

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        this.matDialogRef = this.dialog.open(this.asideHelpSupportMenuStateRef,{
```suggestion
        this.dialog.open(this.asideHelpSupportMenuStateRef,{
```

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        // this.toggleHelpSupportPane(false);
why is this commented?

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.module.ts
> +        MatDialogModule,
remove duplicate import

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/app/theme/command-k/command.k.component.html
> -            <i class="icon-cross close-navigation" (click)="close()"></i>
remove close method from .ts file if its unused

2023-08-03 13:46 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-2.scss
> -@import "../css/global/header.scss";
restrict this from getting deleted

2023-08-04 08:49 UTC, dilpreet77 requested changes

2023-08-04 08:49 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.ts
> -        this.closeAsidePane(event);
Close dialog when click on schedule

2023-08-04 08:49 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +    @ViewChild('asideHelpSupportMenuStateRef', { static: true }) public asideHelpSupportMenuStateRef: TemplateRef<any>;
Add documentation for instance

2023-08-04 08:49 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        public dialog: MatDialog,
remove last comma

2023-08-04 08:49 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        if(event){
Add documentation for this function and format code

2023-08-04 08:49 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> +        public dialog: MatDialog,
remove last comma

2023-08-04 08:49 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> +                })
remove the last comma and add semicolon on the end dialog function

2023-08-07 06:48 UTC, ravinderwalkover approved these changes

2023-08-07 07:18 UTC, dilpreet77 approved these changes

2023-08-07 07:19 UTC, merged