Divyanshu | Test | Rate and amount is overlapping in the manufacturing page
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #12723
Opened 2023-10-31 11:15 UTC by dvCodeWorld

https://app.clickup.com/t/85zu2q99f

2023-10-31 11:30 UTC, dilpreet77 requested changes

2023-10-31 11:30 UTC, dilpreet77 commented on apps/web-giddh/src/app/new-inventory/component/manufacturing/create-manufacturing/create-manufacturing.component.html
> +                                                            <td class="table-name2">
Correct class names for overall

2023-10-31 11:32 UTC, dilpreet77 approved these changes

2023-11-01 05:36 UTC, ravinderwalkover approved these changes

2023-11-01 05:36 UTC, merged