Divyanshu | Test | Bugs and fixes
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #12982
Opened 2024-02-09 10:02 UTC by dvCodeWorld

https://app.clickup.com/t/86cugzwmg

2024-02-10 08:00 UTC, ravinderwalkover requested changes

2024-02-10 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vat-report/vat-report.component.ts
> +    public getYearStartAndEndDate(selectedYear: any) {
add return type

2024-02-10 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vat-report/vat-report.component.ts
> +        this.store.dispatch(this.settingsFinancialYearActions.getFinancialYearLimits());
use of this store dispatch?

2024-02-10 21:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vat-report/vat-report.component.ts
> +    public getYearStartAndEndDate(selectedYear: any) {
done

2024-02-10 21:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vat-report/vat-report.component.ts
> +        this.store.dispatch(this.settingsFinancialYearActions.getFinancialYearLimits());
no use

2024-02-12 04:34 UTC, ravinderwalkover requested changes

2024-02-12 04:34 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vat-report/vat-report.component.ts
> +    private createFinancialYearsList(startDate: any, endDate: any, initList: boolean = true): any {
use of initList?

2024-02-12 05:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vat-report/vat-report.component.ts
> +    private createFinancialYearsList(startDate: any, endDate: any, initList: boolean = true): any {
Not  in use

2024-02-12 05:06 UTC, ravinderwalkover approved these changes

2024-02-12 05:07 UTC, merged