Divyanshu | Stage |  Support of excel export in other voucher get all page
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13148
Opened 2024-04-01 07:47 UTC by dvCodeWorld

https://app.clickup.com/t/86cuzbbu5

2024-04-01 09:02 UTC, dilpreet77 requested changes

2024-04-01 09:02 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
> +                        [ladda]="exportInvoiceRequestInProcess$ | async"
check this loader

2024-04-01 09:02 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
> +        private _invoiceService: InvoiceService
remove underscore

2024-04-01 09:02 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
> +        this._invoiceService.exportCsvInvoiceDownload(this.exportcsvRequest).pipe(takeUntil(this.destroyed$)).subscribe((response) => {
remove underscore from here also

2024-04-01 09:02 UTC, dilpreet77 commented on apps/web-giddh/src/app/reports/components/payment-report/payment-report.component.html
> +                        [ladda]="exportInvoiceRequestInProcess$ | async"
```suggestion
                        [ladda]="exportPaymentRequestInProcess$ | async"
```

2024-04-01 09:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
> +                        [ladda]="exportInvoiceRequestInProcess$ | async"
Done

2024-04-01 09:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
> +        private _invoiceService: InvoiceService
Done

2024-04-01 09:04 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/payment-report/payment-report.component.html
> +                        [ladda]="exportInvoiceRequestInProcess$ | async"
Removed unused variable

2024-04-01 09:05 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
> +        this._invoiceService.exportCsvInvoiceDownload(this.exportcsvRequest).pipe(takeUntil(this.destroyed$)).subscribe((response) => {
Done

2024-04-12 12:39 UTC, ravinderwalkover approved these changes

2024-04-12 13:25 UTC, dilpreet77 approved these changes

2024-04-12 13:25 UTC, merged