Nisha | Test | Table headers are getting remove when searching any random value
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13201
Opened 2024-04-16 05:11 UTC by nisha-walkover

https://app.clickup.com/t/86cv2xwyg

2024-04-16 11:21 UTC, ravinderwalkover requested changes

2024-04-16 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/list-branch-transfer/list-branch-transfer.component.ts
> +        const shouldShow = (
```suggestion
        return (
```

2024-04-16 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/list-branch-transfer/list-branch-transfer.component.ts
> +    public showData: boolean = true;
remove variable

2024-04-16 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/list-branch-transfer/list-branch-transfer.component.ts
> +            this.branchTransferForm?.controls['toWarehouse']?.value
) &&
                    (!this.branchTransferForm?.controls['voucherType']?.value ||
                    !this.branchTransferForm?.controls['amountOperator']?.value ||
                    !this.branchTransferForm?.controls['amount']?.value)

2024-04-16 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/list-branch-transfer/list-branch-transfer.component.ts
> +            this.branchTransferForm?.controls['sender']?.value ||
```suggestion
            (this.branchTransferForm?.controls['sender']?.value ||
```

2024-04-16 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/list-branch-transfer/list-branch-transfer.component.html
> +        <section *ngIf="showData">
```suggestion
        <section *ngIf="branchTransferResponse?.length || shouldShowElement">
```

2024-04-16 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/list-branch-transfer/list-branch-transfer.component.ts
> +                if(
remove this code

2024-04-18 09:19 UTC, dilpreet77 approved these changes

2024-04-18 09:29 UTC, dvCodeWorld approved these changes

2024-04-19 11:17 UTC, ravinderwalkover approved these changes

2024-04-19 11:17 UTC, merged