Divyanshu | Test | Convert Setting side bar all tabs into material
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13286
Opened 2024-05-08 04:55 UTC by dvCodeWorld

https://app.clickup.com/t/85ztgavyt

2024-05-08 11:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/ledger/components/share-ledger/share-ledger.component.html
> +                                        </mat-form-field> -->
delete this email input

2024-05-08 11:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
>      public selectAllPages(event) {
check selelct all not work properly

2024-05-08 11:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
> +                            </sales-sh-select> -->
change this in material

2024-05-08 11:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
> +                            <dropdown-field
remove unsed code

2024-05-08 11:29 UTC, dvCodeWorld commented on package.json
> +        "npx": "^3.0.0",
"npx": "10.2.2",

2024-05-14 08:07 UTC, ravinderwalkover requested changes

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
> +        if (this.roleObj.scopes) {
```suggestion
        if (this.roleObj?.scopes) {
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                        [checked]="true"
```suggestion
                                        [checked]="element.isSelected"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                        [checked]="true"
```suggestion
                                        [checked]="element.isSelected"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.scss
> +.permission-table {
remove this and use .mr-b4

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
> +                        (selectedOption)="$event.value && newRoleObj.isFresh = $event.value"
```suggestion
                        (selectedOption)="newRoleObj.isFresh = $event?.value"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
> +                        <mat-select [(ngModel)]="selectedValues" [ngModelOptions]="{ standalone: true }" multiple>
remove ngModelOptions and provide name and it should work

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
> +                        <mat-select [(ngModel)]="newRoleObj.uniqueName" [ngModelOptions]="{ standalone: true }">
use form control in place of ngModel everywhere

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
> +    public ngAfterViewInit(): void {
remove blank method

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
> +        setTimeout(() => {
move this condition in OnInit method

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
> +    public selectPage(index) {
```suggestion
    public selectPage(index): void {
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/permission.module.ts
> +        BsDropdownModule.forRoot(),
check and remove bootstrap module

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/branch.component.html
> +            <img src="/assets/images/warehouse-vector.svg" [alt]="localeData?.branch_image" />
use imgPath variable

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/branch.component.html
> +            Hello
remove dummy text

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/branch.component.ts
> +            if(query !== undefined) {
```suggestion
            if(query !== undefined && query !== null) {
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/branch.component.ts
> +                if(query.length) {
```suggestion
                if(query) {
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/branch.component.ts
> +            this.openCreateCompanyDialog()
```suggestion
            this.openCreateCompanyDialog();
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
> +                                                [keyboardShortcut]="'alt+c'"
remove duplicate keyboardShortcut attr

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +        this.branchForm.get('address')?.patchValue(this.branchForm.get('address').value.filter(i => i !== element));
dont' use single character variable

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +            return address
```suggestion
            return address;
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/discount/discount.component.html
> +            [activeAccountDetails]="accInfo"
check this

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/discount/discount.component.ts
> +    /** 8 This will hold common JSON data */
```suggestion
    /** This will hold common JSON data */
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/discount/discount.component.ts
> +            return filteredArray[0].label;
```suggestion
            return filteredArray?.length ? filteredArray[0].label : "";
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                        communicationPlatforms?.MSG91?.fields?.auth_key?.mandatory
remove condition

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                    [cssClass]="'auth_key_input'"
convert to snake case if not getting used at many places

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                    <mat-select
add required attr

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                    [require]="true"
```suggestion
                    [required]="true"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.html
> +                                        digitsOnlyDirectiv
use input for digits only directive

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/payment/setting.integration.payment.module.ts
> +        PayorCreateEditComponent,
```suggestion
        PayorCreateEditComponent
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                        [scrollableElementId]="'finishedStockDropdown'"
rename element id

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                [name]="'name'"
```suggestion
                                                [name]="'collection_email'"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                        [scrollableElementId]="'finishedStockDropdown'"
rename element id

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                type="submit"
```suggestion
                                                type="button"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                type="submit"
```suggestion
                                                type="button"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush
remove this

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> +        private plaidLinkService: NgxPlaidLinkService,
check why service is used

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> +    public openCreateNewAccountModal() {
```suggestion
    public openCreateNewAccountModal(): void {
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
> +                                        [defaultValue]="activeTheme === 'default-theme' ? 'Default' : 'Dark'"
don't use static text

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
> +                                        [name]="exportType"
```suggestion
                                        [name]="'exportType'"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
> +                                                                placeholder="Start date"
make start date and end date text dynamic

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
> +                                                        class=""
remove blank class attr

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush
remove changeDetection

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +    public resetForm: string = null;
add js doc

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +            let toDate = null
```suggestion
            let toDate = null;
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +                    setTimeout(() => { this.resetForm = null }, 100);
check why set timeout is used

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/setting.permission.component.html
> +                                                        [disabled]="true" [readonly]="true"></input-field>
check why disabled and readonly both are used

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
> +                        [id]="businessType"
```suggestion
                        [id]="'businessType'"
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush
remove change detection

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.ts
>          this.isValidDomain = this.generalService.checkDashCharacterNumberPattern(this.profileData.portalDomain)
```suggestion
        this.isValidDomain = this.generalService.checkDashCharacterNumberPattern(this.profileData.portalDomain);
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.ts
> +        if(this.profileData[keyName] && (this.tempProfileData[keyName] !== this.profileData[keyName])){
remove if condition if useless

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.html
> -                [showTaxColumn]="showTaxColumn"
check why it's getting removed

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +            this.currentTab = (params['referrer']) ? params['referrer'] : this.router.navigate(['/pages/settings/profile/personal']);
```suggestion
            this.currentTab = (params['referrer']) ? params['referrer'] : "personal";
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +            if((params['referrer']) === 'address') { this.activeTabIndex = 1; }
use else if

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +        this.activeTabIndex = event?.index;
format code

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
>                          this._toasty.successToast('Profile Updated Successfully.');
use showSnackBar toaster everywhere and make message dynamic from localeJson

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/settings.component.html
> +                                            snackOpen
check proper use of snackOpen

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/tags/tags.component.html
> +                                    <input
use material field

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/tags/tags.component.scss
> +.aside-pane {
check and remove this if unused since we are using mat dialog

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
> +                            class="form-group"
remove class attr

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
> +                (onShortcutPress)="closeAddressAsidePane()"
check if we should use toggle here

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
> +                this.addresses.address = modifiedAddresses
```suggestion
                this.addresses.address = modifiedAddresses;
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts
> +    providers: [{ provide: BsDropdownConfig, useValue: { autoClose: true } }]
remove bootstrap module

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/aside-menu-account/aside.menu.account.component.html
> -                *ngIf="activeGroupUniqueName && !isUpdateAccount"
condition shouldn't be removed

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/create-address/create-address.component.html
> +                                                        formControlName="pincode" decimalDigitsDirective
use input param for decimalDigitsDirective

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +        this.addressForm.get('state')?.patchValue(event.value);
```suggestion
        this.addressForm.get('state')?.patchValue(event?.value);
```

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/create-address/create-address.module.ts
>          ShSelectModule,
remove non material module like bootstrap and sh-select

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/theme/form-fields/input-field/input-field.component.ts
> +        if (changes?.defaultValue) {
remove this

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/components/move-company/move-company.component.ts
> +            this.availablePlansOption = this.availablePlansOption;
remove this line and check other changes of file and make it similar to test

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/components/subscription/subscription.component.html
> +                <div class="head-dropdown d-flex align-items-center w-100 pd-l15">
check and make dropdown design similar to how it was earlier

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/components/subscription/subscription.component.scss
> +.link-color {
don't create duplicate classes

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/user-details.component.html
> +                                        <mat-accordion class="example-headers-align" multi>
remove dummy class

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/user-details.module.ts
> +        ClipboardModule,
remove unused module

2024-05-14 08:07 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-1.scss
> +    font-weight: 600;
revert

2024-05-21 09:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
> +        if (this.roleObj.scopes) {
Done

2024-05-21 09:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                        [checked]="true"
Done

2024-05-21 09:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                        [checked]="true"
Done

2024-05-21 09:22 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.scss
> +.permission-table {
Done

2024-05-21 09:23 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
> +                        (selectedOption)="$event.value && newRoleObj.isFresh = $event.value"
Done

2024-05-21 09:34 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
> +                        <mat-select [(ngModel)]="selectedValues" [ngModelOptions]="{ standalone: true }" multiple>
Done

2024-05-21 09:35 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
> +    public ngAfterViewInit(): void {
Done

2024-05-21 09:36 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
> +        setTimeout(() => {
Done

2024-05-21 09:36 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
> +    public selectPage(index) {
Done

2024-05-21 09:37 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/permission.module.ts
> +        BsDropdownModule.forRoot(),
Done

2024-05-21 09:41 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/branch.component.html
> +            <img src="/assets/images/warehouse-vector.svg" [alt]="localeData?.branch_image" />
Done

2024-05-21 09:42 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/branch.component.html
> +            Hello
DONE

2024-05-21 09:59 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/branch.component.ts
> +            if(query !== undefined) {
Done

2024-05-21 10:01 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/branch.component.ts
> +                if(query.length) {
Done

2024-05-21 10:07 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/branch.component.ts
> +            this.openCreateCompanyDialog()
Done

2024-05-21 10:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
> +                                                [keyboardShortcut]="'alt+c'"
Done

2024-05-21 10:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +        this.branchForm.get('address')?.patchValue(this.branchForm.get('address').value.filter(i => i !== element));
Done

2024-05-21 10:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +            return address
Done

2024-05-21 10:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/discount/discount.component.ts
> +    /** 8 This will hold common JSON data */
Done

2024-05-21 10:13 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/discount/discount.component.ts
> +            return filteredArray[0].label;
Done

2024-05-21 10:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                        communicationPlatforms?.MSG91?.fields?.auth_key?.mandatory
Done

2024-05-21 10:15 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                    [cssClass]="'auth_key_input'"
change into 'auth-key-input '

2024-05-21 10:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                    <mat-select
Done

2024-05-21 10:19 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                    [require]="true"
Done

2024-05-21 10:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.html
> +                                        digitsOnlyDirectiv
Done

2024-05-21 10:21 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/payment/setting.integration.payment.module.ts
> +        PayorCreateEditComponent,
Done

2024-05-21 10:28 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                        [scrollableElementId]="'finishedStockDropdown'"
Done

2024-05-21 10:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                        [scrollableElementId]="'finishedStockDropdown'"
Done

2024-05-21 10:30 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                [name]="'name'"
Done

2024-05-21 10:31 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                type="submit"
Done

2024-05-21 10:31 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> +                                                type="submit"
Done

2024-05-21 10:32 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush
Done

2024-05-21 10:33 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush
Done

2024-05-21 10:36 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> +        private plaidLinkService: NgxPlaidLinkService,
Done

2024-05-21 10:36 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> +    public openCreateNewAccountModal() {
Done

2024-05-21 10:47 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
> +                                        [defaultValue]="activeTheme === 'default-theme' ? 'Default' : 'Dark'"
Done

2024-05-21 10:47 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
> +                                        [name]="exportType"
Done

2024-05-21 10:49 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
> +                                                                placeholder="Start date"
Done

2024-05-21 10:51 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
> +                                                        class=""
Done

2024-05-21 10:51 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush
Done

2024-05-21 10:53 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +    public resetForm: string = null;
Done, it not used any where so removed it

2024-05-21 10:54 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +            let toDate = null
Done

2024-05-21 10:54 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +                    setTimeout(() => { this.resetForm = null }, 100);
Removed

2024-05-21 11:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/setting.permission.component.html
> +                                                        [disabled]="true" [readonly]="true"></input-field>
Need to use both think else mat form field will not allow to  type but label will move up and down when click on it

2024-05-21 11:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
> +                        [id]="businessType"
Done

2024-05-21 11:04 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.ts
> +    changeDetection: ChangeDetectionStrategy.OnPush
Done

2024-05-21 11:04 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.ts
>          this.isValidDomain = this.generalService.checkDashCharacterNumberPattern(this.profileData.portalDomain)
Done

2024-05-21 11:08 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.ts
> +        if(this.profileData[keyName] && (this.tempProfileData[keyName] !== this.profileData[keyName])){
Done

2024-05-21 11:13 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.html
> -                [showTaxColumn]="showTaxColumn"
Added again

2024-05-21 11:15 UTC, dvCodeWorld commented on apps/web-giddh/src/assets/css/style-1.scss
> +    font-weight: 600;
Done

2024-05-21 11:17 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/user-details.module.ts
> +        ClipboardModule,
Done

2024-05-21 12:19 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/user-details.component.html
> +                                        <mat-accordion class="example-headers-align" multi>
done

2024-05-21 12:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/components/subscription/subscription.component.scss
> +.link-color {
Done

2024-05-21 12:54 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +            this.currentTab = (params['referrer']) ? params['referrer'] : this.router.navigate(['/pages/settings/profile/personal']);
Done

2024-05-21 12:55 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +            if((params['referrer']) === 'address') { this.activeTabIndex = 1; }
Done

2024-05-21 12:56 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +        this.activeTabIndex = event?.index;
Done

2024-05-21 13:04 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
>                          this._toasty.successToast('Profile Updated Successfully.');
Done

2024-05-21 13:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/tags/tags.component.html
> +                                    <input
Done

2024-05-21 13:16 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/tags/tags.component.scss
> +.aside-pane {
Done, removed used code

2024-05-21 13:17 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
> +                            class="form-group"
done

2024-05-21 13:17 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
> +                this.addresses.address = modifiedAddresses
Done

2024-05-21 13:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts
> +    providers: [{ provide: BsDropdownConfig, useValue: { autoClose: true } }]
Done

2024-05-21 13:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/aside-menu-account/aside.menu.account.component.html
> -                *ngIf="activeGroupUniqueName && !isUpdateAccount"
Done

2024-05-21 13:21 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.html
> +                                                        formControlName="pincode" decimalDigitsDirective
Done

2024-05-21 13:21 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +        this.addressForm.get('state')?.patchValue(event.value);
DONE

2024-05-21 13:23 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.module.ts
>          ShSelectModule,
Done, but i didn't remove LaddaModule

2024-05-21 13:54 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/components/subscription/subscription.component.html
> +                <div class="head-dropdown d-flex align-items-center w-100 pd-l15">
Done

2024-05-21 14:05 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/components/move-company/move-company.component.ts
> +            this.availablePlansOption = this.availablePlansOption;
Done

2024-05-22 04:52 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/discount/discount.component.html
> +            [activeAccountDetails]="accInfo"
Working Fine

2024-05-22 04:54 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/settings.component.html
> +                                            snackOpen
Unused logic

2024-05-22 07:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/form-fields/input-field/input-field.component.ts
> +        if (changes?.defaultValue) {
As discussed we not remove this and default value is only used in setting.permission.component.html

2024-05-23 08:00 UTC, ravinderwalkover requested changes

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
>              remove(page.permissions, (o: Permission) => !o.isSelected);
```suggestion
            remove(page.permissions, (o: Permission) => !o.isSelected || o.code === 'SELECT-ALL');
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
> +            remove(page.permissions, (o: Permission) => o.code === 'SELECT-ALL');
remove this code

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
> +        setTimeout(() => {
this code will run after response will return, either return response inside setTimeout or remove setTimeout

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                            (selectedOption)="pageName = $event.value"
```suggestion
                            (selectedOption)="pageName = $event?.value"
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                    <label for="{{page.name}}+_{{idx}}"> {{commonLocaleData?.app_select_all}}</label>
```suggestion
                                    <label [for]="page.name + '_' + idx"> {{commonLocaleData?.app_select_all}}</label>
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                        id="{{page.name}}+_{{idx}}"
```suggestion
                                        [id]="page.name + '_' + idx"
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                    <label for="{{element.code}}+_{{idx}}"> {{getNameByCode(element.code)}} </label>
```suggestion
                                    <label [for]="element.code + '_' + idx"> {{getNameByCode(element.code)}} </label>
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                        name="{{element.code}}_{{i}}"
```suggestion
                                        [name]="element.code + '_' + idx"
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
> +                console.log(this.localeData);
remove console

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
> +                                [required]="true"
field is not required

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +        if (option.isDefault &&( (this.branchForm.get('address')?.value === '') || (this.branchForm.get('address')?.value.findIndex(i => i.uniqueName === option.uniqueName) === -1))) {
why this extra logic is written?

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +    public handleShortcutPress() {
```suggestion
    public handleShortcutPress(): void {
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/discount/discount.component.ts
> +        }
return blank string after if condition since you mentioned method will return string

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                        required="true"
is this field required?

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.html
> +                                [label]="localeData?.payment?.login_id_labe"
```suggestion
                                [label]="localeData?.payment?.login_id_label"
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
> -                        <label *ngIf="isLblShow">{{ localeData?.ip_addresses }}</label>
remove variable from translation file if unused

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +                const fromDateParts = data.from.split('-').map(Number); // If Date in DD-MM-YYY
convert date properly using dayjs

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +                        this._toasty.showSnackBar("success",this.localeService.translate("app_messages.profile_updated"));
```suggestion
                        this._toasty.showSnackBar("success", this.commonLocaleData?.app_messages.profile_updated);
```

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/user-details.module.ts
> +        MatTooltipModule,
remove all bootstrap modules

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/components/subscription/subscription.component.ts
> -    public goToBuyNow(): void {
why is this getting removed?

2024-05-23 08:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/user-details.component.html
> +        <button class="buy-plan-btn position-absolute" mat-stroked-button color="primary" [routerLink]="['/pages/subscription/buy-plan']" *ngIf="activeTabIndex === 3 && !isSubscriptionLoading">
why this button is added here?

2024-05-23 09:36 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
>              remove(page.permissions, (o: Permission) => !o.isSelected);
Done

2024-05-23 09:36 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
> +            remove(page.permissions, (o: Permission) => o.code === 'SELECT-ALL');
Done

2024-05-23 09:58 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
> +        setTimeout(() => {
Done

2024-05-23 09:58 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                            (selectedOption)="pageName = $event.value"
Done

2024-05-23 09:59 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                    <label for="{{page.name}}+_{{idx}}"> {{commonLocaleData?.app_select_all}}</label>
Done

2024-05-23 10:02 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                        id="{{page.name}}+_{{idx}}"
Done

2024-05-23 10:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                    <label for="{{element.code}}+_{{idx}}"> {{getNameByCode(element.code)}} </label>
Done

2024-05-23 10:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/details/permission.details.html
> +                                        name="{{element.code}}_{{i}}"
Done

2024-05-23 10:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
> +                console.log(this.localeData);
Done

2024-05-23 10:09 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
> +                                [required]="true"
Done

2024-05-23 10:16 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +        if (option.isDefault &&( (this.branchForm.get('address')?.value === '') || (this.branchForm.get('address')?.value.findIndex(i => i.uniqueName === option.uniqueName) === -1))) {
<ng-container *ngFor="l**et chipItem of branchForm?.get('address')?.value**">
          <mat-chip-row (removed)="removeItem(chipItem)" role="option" >
              <span>{{ chipItem?.label }}</span>
              <span matChipRemove><i class="icon-cross"></i></span>
          </mat-chip-row>
</ng-container>


address form control used tho show selected item  so default me click krte hi value push krrha address control me

2024-05-23 10:17 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +    public handleShortcutPress() {
Done

2024-05-23 10:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/discount/discount.component.ts
> +        }
Yes and if condition will true then also return string i.e Label

2024-05-23 10:23 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/campaign/setting-campaign/setting-campaign.component.html
> +                        required="true"
yes preview there was  star (*) in label and now also checked in test env

It is required

2024-05-23 10:24 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.html
> +                                [label]="localeData?.payment?.login_id_labe"
Done

2024-05-23 10:25 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
> -                        <label *ngIf="isLblShow">{{ localeData?.ip_addresses }}</label>
Not used and removed

2024-05-23 11:15 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +                        this._toasty.showSnackBar("success",this.localeService.translate("app_messages.profile_updated"));
Done

2024-05-23 11:25 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/components/subscription/subscription.component.ts
> -    public goToBuyNow(): void {
By Mistake, it is used at two places one I  handle in but second one missed

2024-05-23 11:25 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/components/subscription/subscription.component.ts
> -    public goToBuyNow(): void {
Add again it was used in two different place

2024-05-23 11:27 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/user-details.module.ts
> +        MatTooltipModule,
Done

2024-05-23 11:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/user-details/user-details.component.html
> +        <button class="buy-plan-btn position-absolute" mat-stroked-button color="primary" [routerLink]="['/pages/subscription/buy-plan']" *ngIf="activeTabIndex === 3 && !isSubscriptionLoading">
To handle ui issue 

this not able to assign in parallel to mat tab as previous

2024-05-24 08:02 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +                const fromDateParts = data.from.split('-').map(Number); // If Date in DD-MM-YYY
Done

2024-05-24 09:43 UTC, ravinderwalkover approved these changes

2024-05-24 09:44 UTC, merged