Dilpreet | Test | Subscription Task and Bugs
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13335
Opened 2024-05-17 13:30 UTC by dilpreet77

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2024-05-17 13:36 UTC, dvCodeWorld approved these changes

2024-05-17 13:39 UTC, ravinderwalkover requested changes

2024-05-17 13:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/subscription/buy-plan/buy-plan.component.ts
> +        this.componentStore.activeCompany$.pipe(take(1)).subscribe(response => {
```suggestion
        this.componentStore.activeCompany$.pipe(takeUntil(this.destroyed$)).subscribe(response => {
```

2024-05-17 13:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/subscription/buy-plan/buy-plan.component.ts
>              if (response) {
```suggestion
            if (response && this.activeCompany?.uniqueName !== response?.uniqueName) {
```

2024-05-18 09:52 UTC, ravinderwalkover approved these changes

2024-05-18 09:52 UTC, merged