Dilpreet | Stage | Enables Go Cardless
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13398
Opened 2024-05-30 08:26 UTC by dilpreet77

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2024-06-03 13:33 UTC, dvCodeWorld requested changes

2024-06-03 13:33 UTC, dvCodeWorld commented on apps/web-giddh/src/app/subscription/buy-plan/buy-plan.component.html
> +                                                        [label]="commonLocaleData?.app_region + '*'"
```suggestion
                                                        [label]="commonLocaleData?.app_region"
                                                        [required]="true"
```

2024-06-03 13:33 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/helpers/countryWithCodes.ts
> + export const regionCountriesCode = ['eur', 'glb', 'glf'];
```suggestion
 export const regionsCode = ['eur', 'glb', 'glf'];
```

2024-06-03 13:33 UTC, dvCodeWorld approved these changes

2024-06-05 08:33 UTC, dvCodeWorld approved these changes

2024-06-05 08:59 UTC, ravinderwalkover approved these changes

2024-06-05 08:59 UTC, merged