Divyanshu | Test | Tags page, create new button in discount page and border line in field is not as per requirement
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13425
Opened 2024-06-06 09:57 UTC by dvCodeWorld

https://app.clickup.com/t/86cv9wkp0

2024-06-06 10:08 UTC, dilpreet77 requested changes

2024-06-06 10:08 UTC, dilpreet77 commented on apps/web-giddh/src/app/settings/discount/discount.component.html
> +    <div class="box clearfix giddh-container-center">
section-center

2024-06-06 10:08 UTC, dilpreet77 commented on apps/web-giddh/src/app/settings/tags/tags.component.html
> +    <div class="box giddh-container-center">
also correct this

2024-06-06 10:08 UTC, dilpreet77 commented on apps/web-giddh/src/app/settings/tags/tags.component.html
> +                            {{tag.name | titlecase }}
```suggestion
                            {{tag?.name | titlecase }}
```

2024-06-06 10:08 UTC, dilpreet77 commented on apps/web-giddh/src/app/settings/tags/tags.component.html
> +                            <button matChipRemove [attr.aria-label]="'remove ' + tag.name">
```suggestion
                            <button matChipRemove [attr.aria-label]="'remove ' + tag?.name">
```

2024-06-06 10:08 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +            console.log(this.addressConfiguration);
remove console

2024-06-06 10:08 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
> +                                    <span [innerHTML]="tab.icon"></span>
### 
```suggestion
                                    <span [innerHTML]="tab?.icon"></span>
```

2024-06-06 10:08 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
> +                                    <span>{{ tab.label }}</span>
```suggestion
                                    <span>{{ tab?.label }}</span>
```

2024-06-06 10:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/discount/discount.component.html
> +    <div class="box clearfix giddh-container-center">
Done

2024-06-06 10:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/tags/tags.component.html
> +    <div class="box giddh-container-center">
Done

2024-06-06 10:19 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/tags/tags.component.html
> +                            {{tag.name | titlecase }}
Done

2024-06-06 10:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/tags/tags.component.html
> +                            <button matChipRemove [attr.aria-label]="'remove ' + tag.name">
Done

2024-06-06 10:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +            console.log(this.addressConfiguration);
Done

2024-06-06 10:21 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
> +                                    <span [innerHTML]="tab.icon"></span>
Done

2024-06-06 10:21 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
> +                                    <span>{{ tab.label }}</span>
Done

2024-06-06 11:14 UTC, dilpreet77 approved these changes

2024-06-07 07:23 UTC, ravinderwalkover requested changes

2024-06-07 07:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/tags/tags.component.ts
> +        private formBuilder: UntypedFormBuilder
```suggestion
        private formBuilder: FormBuilder
```

2024-06-07 07:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.module.ts
> +        SettingsModule
don't import settings module

2024-06-07 07:51 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/header.module.ts
> +        SettingsModule
Done

2024-06-07 07:55 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/tags/tags.component.ts
> +        private formBuilder: UntypedFormBuilder
Done

2024-06-07 08:16 UTC, ravinderwalkover approved these changes

2024-06-07 08:17 UTC, merged