Dilpreet | Test | Get account information by its GST number from GST portal
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13483
Opened 2024-06-20 12:52 UTC by dilpreet77

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2024-06-20 13:34 UTC, dvCodeWorld requested changes

2024-06-20 13:34 UTC, dvCodeWorld commented on apps/web-giddh/src/app/add-company/add-company.component.ts
> +                this.closeDialog()
```suggestion
                this.closeDialog();
```

2024-06-20 13:34 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/common.service.ts
> +     * This will be use for gst information details
```suggestion
     * This will be use to show gst information details
```

2024-06-20 13:34 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/common.service.ts
> +    public getGstInformationDetails(gstin: any): Observable<BaseResponse<any, string>> {
```suggestion
    public getGstInformationDetails(gstin: string): Observable<BaseResponse<any, string>> {
```

2024-06-20 13:34 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +     * @param {*} l
```suggestion
     
```

2024-06-20 13:59 UTC, dvCodeWorld approved these changes

2024-06-21 05:30 UTC, ravinderwalkover requested changes

2024-06-21 05:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/add-company/add-company.component.ts
> +                dialogRef?.close();
remove

2024-06-21 05:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/add-company/add-company.component.ts
> +                        let completeAddress = this.commonService.getCompleteAddres(result.body?.pradr?.addr);
move this method in general service

2024-06-21 05:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/common.service.ts
> +        let completeAddress = `${address1} ${address2} ${address3} ${address4} ${address5}`.trim();
```suggestion
        return `${address1} ${address2} ${address3} ${address4} ${address5}`.trim();
```

2024-06-21 05:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +    public isDefaultAddressSelected(val: boolean, i: number): void {
fix variable name

2024-06-21 05:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> +                    dialogRef?.close();
remove

2024-06-21 07:06 UTC, ravinderwalkover requested changes

2024-06-21 07:06 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +        if (this.addressForm.get('taxNumber').value && this.addressForm.get('taxNumber').valid) {
```suggestion
        if (this.addressForm.get('taxNumber').value && this.addressForm.get('taxNumber').valid && this.addressConfiguration.tax.name === 'GSTIN') {
```

2024-06-21 07:19 UTC, ravinderwalkover approved these changes

2024-06-21 07:20 UTC, merged