Nisha | Stage | Provide support of Entries export in Giddh
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13490
Opened 2024-06-21 11:07 UTC by nisha-walkover

https://app.clickup.com/t/86cvqx9c3

2024-06-21 13:10 UTC, dvCodeWorld requested changes

2024-06-21 13:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/daybook/daybook.component.ts
>              this.daybookQueryRequest.type = response.type;
if (response && response !== 'close') {
            this.daybookQueryRequest.type = response.type;
            
Suggestion - check response so below all code work fine

2024-06-21 13:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/daybook/daybook.component.ts
> +                let branchUniqueName = this.generalService.currentBranchUniqueName ? this.generalService.currentBranchUniqueName : (this.currentBranch) ? this.currentBranch?.uniqueName : "";
```suggestion
                let branchUniqueName = this.generalService.currentBranchUniqueName ? this.generalService.currentBranchUniqueName : this.currentBranch ? this.currentBranch?.uniqueName : "";
```

2024-06-21 13:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/daybook.service.ts
> +    public ExportDaybookExpandedPost(request: any,branchUniqueName:string): Observable<BaseResponse<any, any>> {
Write documentation and format the code

2024-06-21 13:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/apiurls/daybook.api.ts
> +    ENTRIES_EXPORT: 'company/:companyUniqueName/exports?output=base64', // get call
```suggestion
    ENTRIES_EXPORT: 'company/:companyUniqueName/exports?output=:output', // get call
```

2024-06-21 13:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/daybook.service.ts
> +            ?.replace(':from', encodeURIComponent(request.from))
```suggestion
       
```

2024-06-21 13:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/daybook.service.ts
> +            ?.replace(':to', encodeURIComponent(request.to))
```suggestion
      
```

2024-06-21 13:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/daybook.service.ts
> +            ?.replace(':type', request.type?.toString())
```suggestion
         
```

2024-06-21 13:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/daybook.service.ts
> +        let format = request.fileType
```suggestion
        const request = request.fileType;
```

2024-06-24 05:44 UTC, nisha-walkover commented on apps/web-giddh/src/app/daybook/daybook.component.ts
>              this.daybookQueryRequest.type = response.type;
This code is not written by me it was written by someone five years ago.

2024-06-24 05:44 UTC, nisha-walkover commented on apps/web-giddh/src/app/daybook/daybook.component.ts
> +                let branchUniqueName = this.generalService.currentBranchUniqueName ? this.generalService.currentBranchUniqueName : (this.currentBranch) ? this.currentBranch?.uniqueName : "";
done

2024-06-24 05:44 UTC, nisha-walkover commented on apps/web-giddh/src/app/services/apiurls/daybook.api.ts
> +    ENTRIES_EXPORT: 'company/:companyUniqueName/exports?output=base64', // get call
done

2024-06-24 05:44 UTC, nisha-walkover commented on apps/web-giddh/src/app/services/daybook.service.ts
> +            ?.replace(':to', encodeURIComponent(request.to))
done

2024-06-24 05:45 UTC, nisha-walkover commented on apps/web-giddh/src/app/services/daybook.service.ts
> +        let format = request.fileType
The code was not used, so remove it.

2024-06-24 07:29 UTC, nisha-walkover commented on apps/web-giddh/src/app/services/daybook.service.ts
> +            ?.replace(':from', encodeURIComponent(request.from))
done

2024-06-24 07:29 UTC, nisha-walkover commented on apps/web-giddh/src/app/services/daybook.service.ts
> +            ?.replace(':type', request.type?.toString())
done

2024-06-24 07:29 UTC, nisha-walkover commented on apps/web-giddh/src/app/services/daybook.service.ts
> +    public ExportDaybookExpandedPost(request: any,branchUniqueName:string): Observable<BaseResponse<any, any>> {
done

2024-06-26 07:14 UTC, ravinderwalkover approved these changes

2024-06-26 07:22 UTC, dvCodeWorld approved these changes

2024-06-26 07:23 UTC, merged