Dilpreet | Stage | Template change - setting for base currency hide/show, exchange rate, POS, POC, LUT
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13500
Opened 2024-06-24 14:10 UTC by dilpreet77

https://app.clickup.com/t/86cvba3a3

2024-07-01 12:50 UTC, nisha-walkover requested changes

2024-07-01 12:50 UTC, nisha-walkover commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.scss
> +th {
write in scss format

2024-07-01 12:50 UTC, nisha-walkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
> +                                <p *ngIf="fieldsAndVisibility.table.displayBaseCurrency.display"><span [innerHTML]='dollarSymbol'></span>89.83</p>
check in commented code

2024-07-01 12:50 UTC, nisha-walkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
> +                    <a
check formating

2024-07-01 12:50 UTC, nisha-walkover commented on apps/web-giddh/src/app/services/gst-reconcile.service.ts
> +    public getLutNumberList(): Observable<BaseResponse<any, any>> {
add documentation in overall

2024-07-01 12:50 UTC, nisha-walkover commented on apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.html
> +                            <span>Manage Tax</span>
add translation check overall

2024-07-01 12:50 UTC, nisha-walkover commented on apps/web-giddh/src/environments/environment.ts
> +    production: true,
revert change

2024-07-02 06:18 UTC, dvCodeWorld requested changes

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/environments/environment.ts
> +    production: true,
Remove this

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> +        console.log(obj);
Remove

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.html
> +                <div class="row">
```suggestion
                <div class="row mx-0">
```

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.html
> +                        <div class="consumption-details-wrapper w-100">
```suggestion
                        <div class="consumption-details-wrapper">
```

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.html
> +                                                            name="date_{{ i }}"
```suggestion
                                                            [name]="'date_' + i"
```

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.html
> +                                                        type="text"
```suggestion
                                                       [type]="'text'"
```

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.html
> +                                                        name="lut_{{ i }}"
```suggestion
                                                        [name]="'lut_' + i"
```

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.scss
> +
Remove extra space

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +
remove space

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +            let value = event.value === this.commonLocaleData.app_yes.toLowerCase() ? true : false;
```suggestion
            const value = event.value === this.commonLocaleData.app_yes.toLowerCase() ? true : false;
```

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +
remove space

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +                    const req = {
write this lines

 const req = {
                        q: obj1,
                        index: index
                    };
 write this code above if condition, instead of write 2 2 place if and else block

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +
remove line

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/utility/gst-setting.store.ts
> +    createUpdateInSuccess: boolean;
```suggestion
    createUpdateIsSuccess: boolean;
```

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/utility/gst-setting.store.ts
> +    createUpdateInSuccess: boolean;
correct everywhere it is used

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/utility/gst-setting.store.ts
> +    createUpdateInSuccess: false,
```suggestion
    createUpdateIsSuccess: false,
```

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst.module.ts
> +        GiddhDatepickerModule,
if not in use, remove it

2024-07-02 06:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst.module.ts
> +        DatepickerWrapperModule,
if not in use, remove it

2024-07-02 06:33 UTC, dilpreet77 commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.html
> +                <div class="row">
I am not doing this due to already confirmed with @nisha-walkover  for html in over al file

2024-07-02 06:34 UTC, nisha-walkover requested changes

2024-07-02 06:34 UTC, nisha-walkover commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.scss
> +        font-weight: 500;
add class fw-bold and remove css

2024-07-02 07:22 UTC, dvCodeWorld approved these changes

2024-07-02 08:15 UTC, nisha-walkover approved these changes

2024-07-18 10:58 UTC, ravinderwalkover approved these changes

2024-07-18 10:58 UTC, merged