Nisha | Stage | Provide support of master export in Giddh
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13510
Opened 2024-06-26 10:38 UTC by nisha-walkover

https://app.clickup.com/t/86cvqx99a

2024-07-01 11:20 UTC, dvCodeWorld approved these changes

2024-07-02 07:43 UTC, dilpreet77 requested changes

2024-07-02 07:43 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/header/components/master-export-option/master-export-option.component.ts
> +   * This will use for export form
correct this documentation

2024-07-02 07:43 UTC, dilpreet77 commented on apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
> +    /** shows active group unique name */
```suggestion
    /** Hold active group unique name */
```

2024-07-02 07:59 UTC, dilpreet77 approved these changes

2024-07-02 08:08 UTC, nisha-walkover commented on apps/web-giddh/src/app/shared/header/components/master-export-option/master-export-option.component.ts
> +   * This will use for export form
done

2024-07-02 08:08 UTC, nisha-walkover commented on apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
> +    /** shows active group unique name */
done

2024-07-02 10:48 UTC, ravinderwalkover approved these changes

2024-07-02 10:50 UTC, merged