Divyanshu | Test | When user save the bulk entries then entries are not getting removed from the pdf list
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13541
Opened 2024-06-28 13:37 UTC by dvCodeWorld

https://app.clickup.com/t/86cvuchd0

2024-06-29 05:24 UTC, dilpreet77 approved these changes

2024-06-29 05:47 UTC, dilpreet77 requested changes

2024-06-29 05:47 UTC, dilpreet77 commented on apps/web-giddh/src/app/actions/ledger/ledger.actions.ts
> +            type: LEDGER.RESET_BLANK_LEDGER_REQUEST,
Add js doc

2024-07-01 07:07 UTC, dvCodeWorld commented on apps/web-giddh/src/app/actions/ledger/ledger.actions.ts
> +            type: LEDGER.RESET_BLANK_LEDGER_REQUEST,
Done

2024-07-01 07:28 UTC, dilpreet77 approved these changes

2024-07-01 07:29 UTC, ravinderwalkover approved these changes

2024-07-01 07:39 UTC, merged