Divyanshu | Stage | Support of US tax in Giddh
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13577
Opened 2024-07-04 14:23 UTC by dvCodeWorld

https://app.clickup.com/t/86cvhwu2c

2024-07-18 09:34 UTC, dilpreetsinghofficial requested changes

2024-07-18 09:34 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/actions/settings/taxes/settings.taxes.action.ts
> +    public GetTaxList(value): CustomActions {
Please use camelCase and add argument type in overall file and add also documentation

2024-07-18 09:34 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/services/settings.taxes.service.ts
> +            ?.replace(':count', encodeURIComponent(params?.count))
check this code

2024-07-18 09:34 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/branch/branch.component.scss
> +    border: none;
use common class for both and use in html

2024-07-18 09:44 UTC, dvCodeWorld commented on apps/web-giddh/src/app/actions/settings/taxes/settings.taxes.action.ts
> +    public GetTaxList(value): CustomActions {
Done

2024-07-18 09:58 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/settings.taxes.service.ts
> +            ?.replace(':count', encodeURIComponent(params?.count))
remove optional chaining

2024-07-18 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/branch.component.scss
> +    border: none;
Done

2024-07-18 10:55 UTC, dilpreetsinghofficial requested changes

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
> +    /** Holds true if active company  country is US */
remove space

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
>      ngOnInit() {
add return type and write documentation

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.ts
> +        document.querySelector('body').classList.add('gst-sidebar-open');
```suggestion
        document.querySelector('body').classList.remove('gst-sidebar-open');
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/store/settings/Settings.reducer.ts
> +    taxAuthorities: ITaxAuthority[]
```suggestion
    taxAuthorities: ITaxAuthority[];
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.html
> +                            [currentTaxAuthorityUniqueName]="getFormControl('taxAuthorityUniqueName').value"
```suggestion
                            [currentTaxAuthorityUniqueName]="getFormControl('taxAuthorityUniqueName')?.value"
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +                this.pagination.page = response?.page;
```suggestion
                this.pagination.page = response.page;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +                this.pagination.totalItems = response?.totalItems;
```suggestion
                this.pagination.totalItems = response.totalItems;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +                this.pagination.totalPages = response?.totalPages;
```suggestion
                this.pagination.totalPages = response.totalPages;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +        const formValue = this.salesTaxReportForm.value;
```suggestion
        const formValue = this.salesTaxReportForm?.value;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +        return saveAs(blob, `Sales Tax Report - Account wise.csv`);
When you receive data from the API for the name, make the necessary changes accordingly. Do the same for the code.

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +
remove extra space

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/rate-wise-report/rate-wise-report.component.html
> +                            [currentTaxAuthorityUniqueName]="getFormControl('taxAuthorityUniqueName').value"
```suggestion
                            [currentTaxAuthorityUniqueName]="getFormControl('taxAuthorityUniqueName')?.value"
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/rate-wise-report/rate-wise-report.component.html
> +                        <div class="pagination-wrapper justify-content-end" *ngIf="pagination?.totalPages > 1">
Make changes according to the API count. When it is more than the API items response, it will show.

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/rate-wise-report/rate-wise-report.component.ts
> +                this.pagination.page = response?.page;
```suggestion
                this.pagination.page = response.page;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/rate-wise-report/rate-wise-report.component.ts
> +                this.pagination.totalItems = response?.totalItems;
```suggestion
                this.pagination.totalItems = response.totalItems;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/rate-wise-report/rate-wise-report.component.ts
> +                this.pagination.totalPages = response?.totalPages;
```suggestion
                this.pagination.totalPages = response.totalPages;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/rate-wise-report/rate-wise-report.component.ts
> +        const formValue = this.salesTaxReportForm.value;
```suggestion
        const formValue = this.salesTaxReportForm?.value;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/rate-wise-report/rate-wise-report.component.ts
> +        const formValue = this.salesTaxReportForm.value;
```suggestion
        const formValue = this.salesTaxReportForm?.value;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/rate-wise-report/rate-wise-report.component.ts
> +        return saveAs(blob, `Sales Tax Report - Rate wise.csv`);
When you receive data from the API for the name, make the necessary changes accordingly. Do the same for the code.

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/tax-authority-report/tax-authority-report.component.ts
> +                this.pagination.page = response?.page;
```suggestion
                this.pagination.page = response.page;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/tax-authority-report/tax-authority-report.component.ts
> +                this.pagination.totalItems = response?.totalItems;
```suggestion
                this.pagination.totalItems = response.totalItems;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/tax-authority-report/tax-authority-report.component.ts
> +                this.pagination.totalPages = response?.totalPages;
```suggestion
                this.pagination.totalPages = response.totalPages;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/tax-authority-report/tax-authority-report.component.ts
> +        const formValue = this.salesTaxReportForm.value;
```suggestion
        const formValue = this.salesTaxReportForm?.value;
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/reports/tax-authority-report/tax-authority-report.component.ts
> +        return saveAs(blob, `Sales Tax Report - Tax Authority wise.csv`);
When you receive data from the API for the name, make the necessary changes accordingly. Do the same for the code

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/tax-authority.component.html
> +
remove extra space

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/tax-authority.component.scss
> +            font-size: var(--font-size-20);
use common class for font-20

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/tax-authority.component.ts
> +
remove extra space

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/utility/tax-authority.store.ts
> +        private store: Store<AppState>,
```suggestion
        private store: Store<AppState>
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/tax-authority/utility/tax-authority.store.ts
> +    readonly getTaxAuthorityList = this.effect((data: Observable<void>) => {
write documentation for this

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vat-report/vat-report-filters/vat-report-filters.component.ts
> +        taxAuthorityUniqueName: '',
```suggestion
        taxAuthorityUniqueName: ''
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vat-report/vat-report-filters/vat-report-filters.component.ts
> +                        arr.push({ label: tax.name, value: tax?.uniqueName });
```suggestion
                        arr.push({ label: tax?.name, value: tax?.uniqueName });
```

2024-07-18 10:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/utility/vouchers.utility.service.ts
> +            } else if(countryCode === TaxSupportedCountries.US) {
format this code

2024-07-18 10:58 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
>      ngOnInit() {
Done

2024-07-18 10:59 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
> +    /** Holds true if active company  country is US */
Done

2024-07-18 11:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.ts
> +        document.querySelector('body').classList.add('gst-sidebar-open');
Done

2024-07-18 11:06 UTC, dvCodeWorld commented on apps/web-giddh/src/app/store/settings/Settings.reducer.ts
> +    taxAuthorities: ITaxAuthority[]
Done

2024-07-18 11:07 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.html
> +                            [currentTaxAuthorityUniqueName]="getFormControl('taxAuthorityUniqueName').value"
Done

2024-07-18 11:09 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +                this.pagination.page = response?.page;
Done

2024-07-18 11:12 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +        const formValue = this.salesTaxReportForm.value;
no need

2024-07-18 11:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/tax-authority/reports/account-wise-report/account-wise-report.component.ts
> +
Done

2024-07-18 11:17 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/tax-authority/tax-authority.component.html
> +
Done

2024-07-18 11:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/tax-authority/tax-authority.component.scss
> +            font-size: var(--font-size-20);
Done

2024-07-18 11:18 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/tax-authority/tax-authority.component.ts
> +
Done

2024-07-18 11:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/tax-authority/utility/tax-authority.store.ts
> +    readonly getTaxAuthorityList = this.effect((data: Observable<void>) => {
Done

2024-07-19 07:25 UTC, dilpreetsinghofficial approved these changes

2024-07-20 09:22 UTC, ravinderwalkover approved these changes

2024-07-20 09:22 UTC, merged