Dilpreet | Stage | Version 1 - Inventory Adjustment
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13588
Opened 2024-07-08 05:07 UTC by dilpreet77

https://app.clickup.com/t/86cud1cfq

2024-07-16 14:14 UTC, dvCodeWorld requested changes

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.html
> +                    width="100%"
remove this it will not work

instead you can try 'w-100' class

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.html
> +                    (selectedOption)="currentBranch.uniqueName = $event?.value; handleBranchChange($event)"
Write this code 

currentBranch.uniqueName = $event?.value

inside handleBranchChange($event) this function

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.html
> +                                {{ element.refNo }}
```suggestion
                                {{ element?.refNo }}
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.html
> +                            <td mat-cell *matCellDef="let element">{{ element.adjustedProduct?.name }}</td>
```suggestion
                            <td mat-cell *matCellDef="let element">{{ element?.adjustedProduct?.name }}</td>
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.html
> +                            <td mat-cell *matCellDef="let element">{{ element.reason?.name }}</td>
```suggestion
                            <td mat-cell *matCellDef="let element">{{ element?.reason?.name }}</td>
```

change in all columns

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.scss
> +$color-nero: var(--color-nero);
use class of css properties you have used in this like display flex, position relative, width 100%,cursor: pointer;align-items: center; etc.

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.html
> +                                width="12%"
check **width="12%"** 

sum of all column with must be 100%

in case where no need of specific with write width="auto" which can occupy all available space

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +                            uniqueName: this.activeCompany ? this.activeCompany.uniqueName : '',
```suggestion
                            uniqueName: this.activeCompany ? this.activeCompany.uniqueName : ''
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +        if (searchedFieldName === 'Stock Name') {
```suggestion
        if (searchedFieldName === 'Stock Name' && this.adjustInventoryListForm?.controls['name'].value !== null && this.adjustInventoryListForm?.controls['name'].value !== '') {
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +            if (this.adjustInventoryListForm?.controls['name'].value !== null && this.adjustInventoryListForm?.controls['name'].value !== '') {
```suggestion
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +            }
```suggestion
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +        } else if (searchedFieldName === 'Reason') {
```suggestion
        } else if (searchedFieldName === 'Reason' && this.adjustInventoryListForm?.controls['reason'].value !== null && this.adjustInventoryListForm?.controls['reason'].value !== '') {
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +            if (this.adjustInventoryListForm?.controls['reason'].value !== null && this.adjustInventoryListForm?.controls['reason'].value !== '') {
```suggestion
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +            }
```suggestion
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +            }
do this in all below

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +                this.dialog.closeAll();
check this

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +
remove extra space lines

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/utility/adjust-inventory-list.store.ts
> +    public deleteAdjustInventoryIsSuccess$ = this.select((state) => state.deleteAdjustInventoryIsSuccess);
```suggestion
    public deleteAdjustInventoryIsSuccess: $Observable<any> = this.select((state) => state.deleteAdjustInventoryIsSuccess);
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/utility/adjust-inventory-list.store.ts
> +                                this.toaster.showSnackBar("error", res.message);
```suggestion
                                this.toaster.showSnackBar("error", res?.message);
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/utility/adjust-inventory-list.store.ts
> +                                this.toaster.showSnackBar("success", res.body);
```suggestion
                                this.toaster.showSnackBar("success", res?.body);
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                            <mat-label>Leave a comment</mat-label>
translation

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                                placeholder="Ex. It makes me feel..."
translation

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                                <table [width]="'100%'">
```suggestion
                                <table width="100%">
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                                <table [width]="'100%'">
do this below line in td th

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                                                        [placeholder]="commonLocaleData?.app_select_method + '*'"
```suggestion
                                                        [placeholder]="commonLocaleData?.app_select_method"
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                                                        [placeholder]="commonLocaleData?.app_select_method + '*'"
why show star in placeholder

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                            <button aria-label="clear" mat-stroked-button color="warn" (click)="resetForm()">
```suggestion
                            <button aria-label="clear" mat-stroked-button (click)="resetForm()">
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                                (click)="backClicked(true)"
correct function name

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +        (commonLocaleData)="(commonLocaleData)"
```suggestion
        [commonLocaleData]="commonLocaleData"
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +        (commonLocaleData)="(commonLocaleData)"
check and do this for below line

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.ts
> +    public panelOpenState = true;
add variable type everywhere

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.ts
> +    public isAllSelected() {
```suggestion
    public isAllSelected(): void {
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/utility/adjust-inventory.store.ts
> +                            this.toaster.showSnackBar('error', 'Something went wrong! Please try again.');
check this

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/aside-create-reason/aside-create-reason.component.html
> +                                    [label]="localeData?.reason + '*'"
```suggestion
                                    [label]="localeData?.reason"
                                    [required]="true"
```

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/aside-create-reason/aside-create-reason.component.html
> +                <button id="closedialog" aria-label="close button" mat-dialog-close><i class="icon-cross"></i></button>
what is use of this -> id="closedialog"

2024-07-16 14:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/aside-create-reason/aside-create-reason.component.scss
> +#closedialog {
check this and try to write less code for this 

please latest aside menu based on mat dailog

2024-07-17 04:05 UTC, nisha-walkover requested changes

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.html
> +                class="branch-width mr-0 float-left"
remove float-left class and check

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.scss
> +    padding: 0 0 0 10px !important;
remove padding and flex css and add pb-1 or 2 or d-flex class in HTML.

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.scss
> +        position: relative;
remove css and add class position-relative in HTML

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.scss
> +    div {
add class

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +     * This will be use for show delete delete inventory adjust confirmation modal
check document

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +    <div class="relative">
check class

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.ts
> +     *This will be use for upate inventory
check document

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/app/services/general.service.ts
> +            footerCssClass,
remove ,

2024-07-17 04:05 UTC, nisha-walkover commented on apps/web-giddh/src/environments/environment.ts
> +    production: true,
check this

2024-07-17 04:43 UTC, nisha-walkover requested changes

2024-07-17 04:43 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.scss
> +            padding-left: 0 !important;
add classes for padding

2024-07-17 04:43 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/aside-create-reason/aside-create-reason.component.scss
> +    display: flex;
add classes for flex

2024-07-17 06:06 UTC, dvCodeWorld requested changes

2024-07-17 06:06 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory-list/adjust-inventory-list.component.ts
> +    public dataSource: any;
variable type in over all file

2024-07-17 06:06 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.ts
> +    public matDialogRef: any;
```suggestion
    public matDialogRef: MatDialogRef<any>;
```

2024-07-17 06:06 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/apiurls/inventory.api.ts
> +        REPORT: 'company/:companyUniqueName/inventory-adjustment/adjustment-report?page=:page&&from=:from&to=:to&count=:count&sortBy=:sortBy&sort=:sort&q=:q&searchBy=:searchBy', // GET call
```suggestion
        REPORT: 'company/:companyUniqueName/inventory-adjustment/adjustment-report?page=:page&from=:from&to=:to&count=:count&sortBy=:sortBy&sort=:sort&q=:q&searchBy=:searchBy', // GET call
```

2024-07-17 06:06 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/inventory.service.ts
> +        url = url?.replace(":from", getParams.from);
```suggestion
        ?.replace(":from", getParams?.from);
```

2024-07-17 06:06 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/inventory.service.ts
> +        url = url?.replace(":companyUniqueName", this.companyUniqueName);
```suggestion
        url = url?.replace(":companyUniqueName", this.companyUniqueName)
```

2024-07-17 06:06 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/inventory.service.ts
> +        url = url?.replace(":from", getParams.from);
do this all below line

2024-07-17 06:06 UTC, dvCodeWorld commented on apps/web-giddh/src/assets/css/global/adjustment-inventory.scss
> +                min-width: 0;
we have class for this 
i.e min-width-unset

2024-07-17 06:42 UTC, dilpreetsinghdang commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +                                placeholder="Ex. It makes me feel..."
remove unused code

2024-07-17 06:47 UTC, dilpreetsinghdang commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.html
> +        (commonLocaleData)="(commonLocaleData)"
remove unused code

2024-07-17 07:31 UTC, dilpreetsinghdang commented on apps/web-giddh/src/app/new-inventory/component/adjust-inventory/adjust-inventory.component.scss
> +            padding-left: 0 !important;
not working

2024-07-17 08:56 UTC, nisha-walkover approved these changes

2024-08-05 06:48 UTC, closed without merging