Nisha | Stage | Version 1 Item wise export report
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13594
Opened 2024-07-09 04:23 UTC by nisha-walkover

https://app.clickup.com/t/86cv8daay

2024-07-17 08:02 UTC, dilpreetsinghdang requested changes

2024-07-17 08:02 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/inventory.store.ts
> +    isLoading: false,
```suggestion
    isLoading: false
```

2024-07-17 08:02 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/inventory.store.ts
> +    actions$: any;
```suggestion
    actions$: any; : remove this if this is unused
```

2024-07-18 06:09 UTC, nisha-walkover commented on apps/web-giddh/src/app/new-inventory/component/inventory.store.ts
> +    actions$: any;
done

2024-07-18 06:22 UTC, dilpreetsinghofficial approved these changes

2024-07-18 06:23 UTC, ravinderwalkover approved these changes

2024-07-18 11:02 UTC, merged