Nisha | Test | bug fixes Item wise export report
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13601
Opened 2024-07-15 06:36 UTC by nisha-walkover

https://app.clickup.com/t/86cvrkee7

2024-07-15 12:14 UTC, dilpreetsinghofficial requested changes

2024-07-15 12:14 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/downloads/components/exports/exports.component.ts
> +            'INVENTORY_VARIANT_WISE_EXPORT',
move to enum file and make it public variable

2024-07-15 12:14 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/downloads/components/exports/exports.component.ts
> +            console.log(row?.inventoryReportsExportFilter);
remove console

2024-07-15 12:14 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/downloads/components/exports/exports.component.ts
> +        let dataToPass = row;
```suggestion
        let dataReq ;
```

2024-07-15 12:14 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/downloads/components/exports/exports.component.ts
> +            dataToPass = row?.inventoryReportsExportFilter;
```suggestion
            dataReq = row?.inventoryReportsExportFilter;
```

2024-07-15 12:14 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/report-filters/report-filters.component.html
> +                style="width: 33%;"
remove inline css

2024-07-15 12:14 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/report-filters/report-filters.component.ts
> +             showClosingStockValue: false,
```suggestion
             showClosingStockValue: false
```

2024-07-15 12:14 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/report-filters/report-filters.component.ts
> +         this.displayedColumns.forEach(column => {
```suggestion
         this.displayedColumns?.forEach(column => {
```

2024-07-15 12:14 UTC, dilpreet77 commented on apps/web-giddh/src/app/new-inventory/component/report-filters/report-filters.component.ts
> +                this.stockReportRequestExport.branchUniqueNames = [this.generalService.currentBranchUniqueName];
```suggestion
                this.stockReportRequestExport.branchUniqueNames = this.generalService.currentBranchUniqueName ? [this.generalService.currentBranchUniqueName] : [];
```

2024-07-16 05:40 UTC, dilpreetsinghdang approved these changes

2024-07-16 05:40 UTC, dilpreetsinghdang commented on apps/web-giddh/src/app/downloads/components/exports/exports.component.ts
> +    /** enum for export data in inventory */
```suggestion
    /** Instance for export data in inventory */
```

2024-07-16 05:54 UTC, ravinderwalkover approved these changes

2024-07-16 06:00 UTC, merged