Dilpreet | Test | Template change - setting for base currency hide/show, exchange rate, POS, POC, LUT
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13602
Opened 2024-07-15 07:47 UTC by dilpreet77

2024-07-15 07:50 UTC, nisha-walkover commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.scss
> +            padding-bottom: 30px;
add pb-3 class for padding remove css

2024-07-15 07:50 UTC, nisha-walkover commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +    public showHideLutForm: boolean;
add documentation

2024-07-15 07:50 UTC, nisha-walkover commented on apps/web-giddh/src/assets/locale/gst-setting/mr.json
> +    "confirm_delete_message": "Are you sure you want to delete lut number?"
check translation

2024-07-15 08:16 UTC, dilpreet77 commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.scss
> +            padding-bottom: 30px;
This class will add dynamically

2024-07-15 08:57 UTC, nisha-walkover approved these changes

2024-07-15 09:04 UTC, dvCodeWorld requested changes

2024-07-15 09:04 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +    private openConfirmationDialog(index: number): void {
```suggestion
    private openConfirmationDialog(index: number): void || null {
```

2024-07-15 09:04 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +                        } else {
if (mappingForm.get('uniqueName')?.value) {
                            if (this.responseArray?.length) {
                                this.responseArray[index] = [];
                            }
                            this.componentStore.deleteLutNumber({ lutNumberUniqueName: mappingForm.get('uniqueName')?.value });  
                        } 
                            mappings.removeAt(index);

2024-07-15 09:04 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +                        } else {
Keep this line "mappings.removeAt(index);"

out side the if condition and no need to write else block

2024-07-15 09:08 UTC, dilpreet77 commented on apps/web-giddh/src/app/gst/gst-setting/gst-setting.component.ts
> +    private openConfirmationDialog(index: number): void {
removing return

2024-07-15 09:08 UTC, dvCodeWorld approved these changes

2024-07-16 05:23 UTC, ravinderwalkover approved these changes

2024-07-16 05:24 UTC, merged