Divyanshu | Stage | Add "Paid" option in all get all vouchers page (same as working in Invoice)
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13606
Opened 2024-07-16 04:42 UTC by dvCodeWorld

https://app.clickup.com/t/86cvyvevf

2024-07-18 12:33 UTC, dilpreetsinghofficial requested changes

2024-07-18 12:33 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> +                                            <span [ngClass]="{ 'text-light-2': !item.balanceStatus }">
```suggestion
                                            <span [ngClass]="{ 'text-light-2': !item?.balanceStatus }">
```

2024-07-18 12:33 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
> +    span.close-modal.pull-right {
write in scss format

2024-07-18 14:10 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> +                                            <span [ngClass]="{ 'text-light-2': !item.balanceStatus }">
Done

2024-07-19 07:26 UTC, dilpreetsinghofficial approved these changes

2024-07-19 09:19 UTC, ravinderwalkover approved these changes

2024-07-19 09:19 UTC, merged