Divyanshu | Test | Searching is not working state dropdown while creating address
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13642
Opened 2024-07-19 11:49 UTC by dvCodeWorld

https://app.clickup.com/t/86cw0d1g2

2024-07-20 06:15 UTC, dilpreetsinghofficial requested changes

2024-07-20 06:15 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/create-address/create-address.component.html
> +                                                            addressConfiguration?.tax?.name === 'GSTIN') || (addressForm?.get('stateLabel')?.value !== null && addressForm?.get('taxNumber')?.value !==
public isReadonly(): boolean {
  const isEditAddress = this.addressConfiguration?.type === 'editAddress';
  const hasTaxNumber = !!this.addressToUpdate?.taxNumber;
  const isGSTIN = this.addressConfiguration?.tax?.name === 'GSTIN';
  const stateLabelNotNull = this.addressForm?.get('stateLabel')?.value !== null;
  const taxNumberNotNull = this.addressForm?.get('taxNumber')?.value !== null;
  return (isEditAddress && hasTaxNumber && isGSTIN) || (stateLabelNotNull && taxNumberNotNull);
}
[readonly]="isReadonly()

2024-07-20 11:08 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.html
> +                                                            addressConfiguration?.tax?.name === 'GSTIN') || (addressForm?.get('stateLabel')?.value !== null && addressForm?.get('taxNumber')?.value !==
Done

2024-07-29 05:57 UTC, dilpreetsinghofficial approved these changes

2024-07-29 05:57 UTC, merged