Divyanshu | Stage | Searching is not working state dropdown while creating address
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13641
Opened 2024-07-19 11:42 UTC by dvCodeWorld

https://app.clickup.com/t/86cw0d1g2

2024-07-30 10:14 UTC, dilpreetsinghofficial approved these changes

2024-07-31 06:57 UTC, ravinderwalkover requested changes

2024-07-31 06:57 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +    public isReadonly(): boolean {
```suggestion
    public isStateReadonly(): boolean {
```

2024-07-31 09:33 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +    public isReadonly(): boolean {
Done

2024-07-31 10:06 UTC, ravinderwalkover approved these changes

2024-07-31 10:07 UTC, merged