Ankit | Stage | Prod - Table headers is coming when no stock present on Inventory list module
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13667
Opened 2024-07-22 13:04 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cw042wn

2024-07-30 11:16 UTC, dvCodeWorld approved these changes

2024-07-31 07:07 UTC, ravinderwalkover requested changes

2024-07-31 07:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/bulk-stock-edit/bulk-stock-edit.component.html
> +                                *ngIf="!noDataFound"
this will hide search icon if no data found. need confirmation from kriti/rishi

2024-08-06 12:29 UTC, ravinderwalkover approved these changes

2024-08-07 07:13 UTC, merged