Dilpreet | Stage | Sync test to stage
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13674
Opened 2024-07-24 11:05 UTC by dvCodeWorld

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2024-07-24 13:34 UTC, dilpreetsinghofficial requested changes

2024-07-24 13:34 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/app.component.ts
> +            this._generalService.setParameterInLocalStorage("X-Tenant", "GB");
@ravinderwalkover sir please check

2024-07-24 13:34 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/home/components/revenue/revenue-chart.component.html
> +                                {{ commonLocaleData?.app_total }} {{ activeGraphType["displayName"] }} ({{
@ravinderwalkover sir please check

2024-07-24 13:34 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
> +            this.router.navigate(['/pages/voucher/receipt/preview/' + receipt.uniqueName + '/' + receipt.account?.uniqueName]);
@ravinderwalkover sir please check

2024-07-24 13:34 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/payment-report/payment-report.component.html
> -                        [routerLink]="'/pages/voucher/payment/create'"
@ravinderwalkover sir please check

2024-07-24 13:34 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/payment-report/payment-report.component.ts
> +        if (this.voucherApiVersion === 2) {
@ravinderwalkover sir please check

2024-07-24 13:38 UTC, dilpreetsinghofficial requested changes

2024-07-24 13:38 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/app.routes.ts
> +            { path: 'voucher', loadChildren: () => import('./payment-receipt/payment-receipt.module').then(module => module.PaymentReceiptModule), canActivate: [NeedsAuthorization] },
@ravinderwalkover sir please check

2024-07-24 13:38 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/contact/contact.component.scss
> -    width: 225px !important;
@ravinderwalkover sir please check

2024-07-24 13:38 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
> +                                    matInput
@ravinderwalkover sir please check

2024-07-24 13:38 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.html
> +                                        [padding]="padding"
@ravinderwalkover sir please check

2024-07-24 13:38 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/financial-reports/components/export/model/data-formatter.ts
> +                                data1.push(`${this.firstCapital(acc.name)}(${this.firstCapital(group.groupName)})`);
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial requested changes

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
> +                if (tax) {
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/forms/inventory-user/transfer-inventory-user.component.html
> +<div class="form-body width-bg clearfix margin-child-label">
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/forms/inward-note/inward-note.component.html
> +                        <div class="col-12">
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/forms/inward-note/inward-note.component.html
> +                <div class="col-12 text-left mr-t1">
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/forms/outward-note/outward-note.component.html
> -                class="row"
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
> +                                                    class="sku-code"
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> +            width: 100%;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/inventory.component.scss
> -}
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/jobwork/jobwork.component.html
> +                [ranges]="datePickerOption"
@ravinderwalkover sir please check in overall file

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/jobwork/jobwork.component.scss
> +    margin-top: 45px;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/inventory/jobwork/jobwork.component.ts
> +    @ViewChild('receiverName', { static: false }) public receiverName: ElementRef;
@ravinderwalkover sir please check in overall file

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> +                        nextText="&#9658;"
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                                this.selectedInvoiceForDetails = allItems[itemIndex];
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.html
> +                        [disabled]="!emailList?.value || (currentVoucherFilter === 'invoices' && !invoiceType?.length)"
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.scss
> -.pdf-height {
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts
> -        this.voucherDetailsInProcess$ = this.store.pipe(select(p => p.receipt.voucherDetailsInProcess), takeUntil(this.destroyed$));
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/recurring/recurring.component.scss
> -    .dropdown-menu {
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
> +    margin-left: 0;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
> +                                                    (ngModelChange)="
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/edit-template.component.scss
> +    .template-preview-container {
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
> +        this.onChangeFieldVisibility(null, null, null);
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
> +                <i class="icon-change_template tab-expanded"></i> <label>Change up to template</label>
@ravinderwalkover sir please check in over all file

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.scss
> +            padding: 5px;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
> +                                *ngIf="fieldsAndVisibility.table.previousDue?.display && voucherType === 'sales'"
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
> -    overflow: hidden;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
> +                    <tr *ngIf="fieldsAndVisibility.table.previousDue?.display && voucherType === 'sales'">
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.html
> -                                        <span class="qty-number">4 No.</span>
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    table-layout: fixed;
@ravinderwalkover sir please check in overall file

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
> +    public manualGenerateVoucherChecked: boolean = true;
@ravinderwalkover sir please check in over all file

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
> +            this.vm.selectedLedger.generateInvoice = true;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/ledger/ledger.component.scss
> -        min-width: 160px;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/login/login.component.html
> +                                                    <img src="./assets/images/new/apple-icon.svg" alt="apple img" />
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/login/login.component.scss
> +    margin-bottom: 3px;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/login/login.component.ts
> +
@ravinderwalkover sir please check in overall file

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> +    &:focus {
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/models/api-models/SettingsIntegraion.ts
> +        this.loginId = '';
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/models/default-menus.ts
@ravinderwalkover sir please check in overall file

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/branch-transfer-create/branch-transfer-create.component.html
> +        </div>
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/bulk-stock-edit/bulk-stock-edit.component.ts
> +                this.resetSearch();
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/inventory-master/inventory-master.component.scss
> +                height: auto;
@ravinderwalkover sir please check

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/inventory-sidebar/inventory-sidebar.component.ts
> +                        { name: 'Inventory Adjustment', icons: 'home-icon-black.svg', link: '/pages/inventory/v2/product/adjust', hiddenLink: ['/pages/inventory/v2/product/adjust/create'] }
@ravinderwalkover sir please check in overall file

2024-07-24 14:05 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/payment-receipt/components/create-edit/payment-receipt.component.ts
> +                    uniqueName: this.paymentReceiptResponse?.uniqueName,
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial requested changes

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> +                                                                            name="companyShippingPinCode"
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> +                                        <br />
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> +                                        class="small text-muted sku-and-custom-fields"
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
> +    width: 100px !important;
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
> +        *ngIf="purchaseOrderUniqueName && translationLoaded"
@ravinderwalkover sir please check in overall file

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
> +                                currencyConversion = currencyConversion?.replace("[BASE_CURRENCY]", item.grandTotal?.currencyForCompany?.code)?.replace("[AMOUNT]", grandTotalAmountForCompany)?.replac
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
> +            this.initPurchaseOrders();
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
>                          class="btn btn-sky-blue dropdown-btn-new"
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
> +                                        'sorting-icon icon-pointer': true,
@ravinderwalkover sir please check in overall file

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/routes-array.ts
> +            { path: 'voucher', loadChildren: () => import('./payment-receipt/payment-receipt.module').then(module => module.PaymentReceiptModule) },
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/services/apiurls/logs.api.ts
> +    GET_AUDIT_LOGS_V2: 'v2/company/:companyUniqueName/logs?page=:page', // post call
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/services/authentication.service.ts
> +    public loginWithApple(data: any): Observable<BaseResponse<any, any>> {
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/services/http-wrapper.service.ts
> +        options.headers["X-Tenant"] = this.generalService.getUtmParameter("X-Tenant");
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/branch/branch.component.scss
> -                max-width: 180px;
@ravinderwalkover sir please check in over all file

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.ts
> -            this.toaster.clearAllToaster();
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.scss
> +.linked-account {
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/integration/setting.integration.component.scss
> +    height: 100%;
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/warehouse/action/warehouse.action.ts
> +                return { type: 'EmptyAction' };
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
> +        } else if(this.adjustVoucherForm.adjustments[index]) {
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/amount-field/amount-field.component.ts
> +                this.direction = "ltr";
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/aside-menu-product-service/aside-menu-product-service.component.html
> +                [includeSearchedGroup]="includeSearchedGroup"
@ravinderwalkover sir please check

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
> -            if (a && a.companyInventorySettings) {
@ravinderwalkover sir please check in overall file

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.html
> +                    [includeSearchedGroup]="includeSearchedGroup"
@ravinderwalkover sir please check in overall file

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.ts
> +            } else if (this.selectedGroupUniqueName === 'receipt' || this.selectedGroupUniqueName === 'payment') {
@ravinderwalkover sir please check in overall file

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
> +                                            commonLocaleData?.app_hsn
@ravinderwalkover sir please check in over all file

2024-07-25 06:23 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> -    public initialCustomFieldDetailsForm(value: any = null): UntypedFormGroup {
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial requested changes

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
> +                                            commonLocaleData?.app_hsn
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.ts
> +            this.isMobileView = result?.matches;
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html
> +                        <div class="input-share-width">
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.scss
> +        .input-group {
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html
> +                        <div class="input-share-width">
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.scss
> +            input {
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/header.component.scss
> +.user-dropdown-header:after {
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +                    window.location.href = (environment.production) ? `https://stage.giddh.com/login` : `https://test.giddh.com/login`;
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
> +        padding: 0;
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> +                    padding: 14px 10px !important;
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> +            this.closeAccountModal(true);
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/store/settings/Settings.reducer.ts
> +            return Object.assign({}, state, {
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/add-bulk-items/add-bulk-items.component.html
> +<ng-container appTranslate [file]="'vouchers/add-bulk-items'" (localeData)="localeData = $event"
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/confirmation-modal/confirmation-modal.component.scss
> +    }
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/discount-dropdown/discount-dropdown.component.ts
> +            if (hasManualDiscount?.length && hasManualDiscount[0]) {
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/user-details/components/move-company/move-company.component.ts
> +    /** Holds Store Subscription list observable*/
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/user-details/components/subscription/subscription.component.html
> +            <button mat-stroked-button color="primary" (click)="goToBuyNow(selectedSubscription?.subscriptionId)" *ngIf="!showLoader">
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/user-details/user-details.component.ts
> +        this.store.dispatch(this.settingsProfileActions.resetPatchProfile());
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/create/create.component.html
> +                                                        class="w-100" name="billingDetails"
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
>                      const entryFormGroup = this.getEntryFormGroup(entryIndex);
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/utility/directives/entry-amount/entry-amount.directive.ts
> +        if (this.calculateAmount) {
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/utility/vouchers.utility.service.ts
> +
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/assets/css/global/header.scss
> +            .mat-list-item-content {
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/assets/css/global/help-support.scss
> +        .mdc-dialog__content{
@ravinderwalkover sir please check

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/assets/css/style-1.scss
> +            height: 36px;
@ravinderwalkover sir please check in overall file

2024-07-25 07:03 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/assets/css/style-2.scss
> +        min-width: 160px !important;
@ravinderwalkover sir please check in overall file

2024-07-26 10:18 UTC, ravinderwalkover requested changes

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/app.component.ts
> +            this._generalService.setParameterInLocalStorage("X-Tenant", "GB");
@dilpreetsinghdang Confirm with Kriti if we can take the x-tenant task forward.

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
> +                                    matInput
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.html
> +                                        [padding]="padding"
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/financial-reports/components/export/model/data-formatter.ts
> +                                data1.push(`${this.firstCapital(acc.name)}(${this.firstCapital(group.groupName)})`);
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
> +                                                    class="sku-code"
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> +            width: 100%;
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/inventory/jobwork/jobwork.component.html
> +                [ranges]="datePickerOption"
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> +                        nextText="&#9658;"
@dvCodeWorld why multiple previousText and nextText is coming here???

@dilpreetsinghdang why are you asking me to check everything??

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts
> -        this.voucherDetailsInProcess$ = this.store.pipe(select(p => p.receipt.voucherDetailsInProcess), takeUntil(this.destroyed$));
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
> +        this.onChangeFieldVisibility(null, null, null);
@dvCodeWorld kaunse task k karan ye code aaya yaha?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.scss
> +            padding: 5px;
@dvCodeWorld ye css kisi icon k liye likhi he?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
> +                                *ngIf="fieldsAndVisibility.table.previousDue?.display && voucherType === 'sales'"
@dvCodeWorld kaunse task ka part he ye code?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
> +                    <tr *ngIf="fieldsAndVisibility.table.previousDue?.display && voucherType === 'sales'">
@dilpreetsinghdang we don't use this template.

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/thermal-template/thermal-template.component.scss
> +    table-layout: fixed;
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/login/login.component.html
> +                                                    <img src="./assets/images/new/apple-icon.svg" alt="apple img" />
@dilpreetsinghdang confirm with kriti. This is apply login for mac electron only.

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> +    &:focus {
@dilpreetsinghdang what to check here?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/create-new-inventory-component/create-new-inventory.component.html
> +            <button mat-icon-button class="ml-3" style="font-size: 25px" [routerLink]="['/pages/new-inventory']">
revert the change

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-sidebar/inventory-sidebar.component.ts
> +                        { name: 'Inventory Adjustment', icons: 'home-icon-black.svg', link: '/pages/inventory/v2/product/adjust', hiddenLink: ['/pages/inventory/v2/product/adjust/create'] }
@dvCodeWorld do translation

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/inventory-sidebar/inventory-sidebar.component.ts
> +                        { name: 'Inventory Adjustment', icons: 'home-icon-black.svg', link: '/pages/inventory/v2/service/adjust', hiddenLink: ['/pages/inventory/v2/service/adjust/create'] }
@dvCodeWorld do translation

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
> +            this.router.navigate(['/pages/voucher/receipt/preview/' + receipt.uniqueName + '/' + receipt.account?.uniqueName]);
@dilpreetsinghdang check and confirm this

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/http-wrapper.service.ts
> +        options.headers["X-Tenant"] = this.generalService.getUtmParameter("X-Tenant");
Confirm with kriti

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/service.module.ts
> +                PrinterFormatService,
remove both. duplicate

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/warehouse/action/warehouse.action.ts
> +                return { type: 'EmptyAction' };
@dilpreetsinghdang you need to check

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.html
> +    <div class="help-support-aside setting-sidebar-wrapper" *ngIf="asideInventorySidebarMenuState === 'in'">
@dilpreetsinghdang @dvCodeWorld ye q add ho raha he?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.scss
> +.desktop-header .hamburger-menu {
@dvCodeWorld @dilpreetsinghdang ye kaunsa task ka code he?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +            this.toggleSidebarPane(false, false);
ye q add ho raha he? is file k changes ko verify karo.

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> +            this.closeAccountModal(true);
@dilpreetsinghdang you need to verify this

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/user-details/user-details.component.ts
> +        this.store.dispatch(this.settingsProfileActions.resetPatchProfile());
check this yourself

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-1.scss
> +@import "./color.scss";
@dvCodeWorld why is this getting added?

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-1.scss
> -.expense-ledger {
@dvCodeWorld check this file properly

2024-07-26 10:18 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-2.scss
> +@import "../css/global/inventory-adjustment.scss";
@dvCodeWorld check this file properly

2024-07-29 12:07 UTC, ravinderwalkover requested changes

2024-07-29 12:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
> +        private router: Router,
is this getting used???

2024-07-29 12:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> -        this.checkIfPageHasTabs();
ye q remove kar rahe he?

2024-07-29 12:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> -                this.checkIfPageHasTabs();
ye q remove kar rahe he?

2024-07-29 12:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +            this.toggleSidebarPane(false, false);
bina comment likhe resolve kar rhe ho????

2024-07-29 12:07 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-1.scss
> -.expense-ledger {
@dvCodeWorld bina comment likhe resolved????

2024-07-29 12:07 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-2.scss
> -@import "../css/global/dialog.scss";
ye q remove kar rahe he?

2024-07-29 12:52 UTC, ravinderwalkover approved these changes

2024-07-29 13:21 UTC, dilpreetsinghofficial approved these changes

2024-07-29 13:27 UTC, merged