Ankit | Test | Prod - State dropdown is not getting open when GSTIN has been removed from address
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13695
Opened 2024-07-31 06:20 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cw2y5dv

2024-07-31 06:55 UTC, nisha-walkover requested changes

2024-07-31 06:55 UTC, nisha-walkover commented on apps/web-giddh/src/assets/css/global/input-dropdown-field.scss
> +        &:has(input:disabled, input:read-only) {
already have a class for disabled

2024-07-31 07:03 UTC, dvCodeWorld requested changes

2024-07-31 07:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +        const taxNumberNotEmpty = this.addressForm?.get('taxNumber')?.value !== "";
```suggestion
        const taxNumberNotEmpty = this.addressForm?.get('taxNumber')?.value !== "" && this.addressForm?.get('taxNumber')?.value !== null;
```

2024-07-31 07:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +        const taxNumberNotNull = this.addressForm?.get('taxNumber')?.value !== null;
```suggestion
   
```

2024-07-31 07:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +        return  (isGSTIN && stateLabelNotNull && taxNumberNotNull && taxNumberNotEmpty);
```suggestion
        return  isGSTIN && stateLabelNotNull && taxNumberNotEmpty;
```

2024-07-31 10:13 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +        const taxNumberNotEmpty = this.addressForm?.get('taxNumber')?.value !== "";
done

2024-07-31 10:19 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/create-address/create-address.component.ts
> +        return  (isGSTIN && stateLabelNotNull && taxNumberNotNull && taxNumberNotEmpty);
done

2024-08-01 05:06 UTC, dvCodeWorld approved these changes

2024-08-01 05:16 UTC, dvCodeWorld approved these changes

2024-08-02 05:17 UTC, nisha-walkover approved these changes

2024-08-02 05:18 UTC, merged