Ankit | Stage | Prod - Flag dropdown on mobile number field is not getting open correctly in case of create company flow
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13704
Opened 2024-08-01 09:07 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cw2xd8d

2024-08-06 12:09 UTC, dvCodeWorld requested changes

2024-08-06 12:09 UTC, dvCodeWorld commented on apps/web-giddh/src/assets/css/global/add-company.scss
> +    .mat-horizontal-stepper-content{
```suggestion
    .mat-horizontal-stepper-content {
```

2024-08-07 07:03 UTC, dvCodeWorld approved these changes

2024-08-07 07:35 UTC, ravinderwalkover approved these changes

2024-08-07 11:46 UTC, merged