Ankit | Stage |  Prod - Table headers is coming when no stock present on Inventory list module
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13748
Opened 2024-08-07 10:32 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cw042wn

2024-08-07 10:33 UTC, dvCodeWorld approved these changes

2024-08-22 10:06 UTC, ravinderwalkover approved these changes

2024-08-22 10:06 UTC, ravinderwalkover requested changes
Card is not ready for PROD

2024-08-22 11:12 UTC, ravinderwalkover approved these changes

2024-08-22 11:16 UTC, merged