Ankit | stage | Prod - Invalid date error is coming when changing the entry date on ledger for imported transaction #13739
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13740
Opened 2024-08-05 14:16 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cw4245t

2024-08-05 14:21 UTC, dvCodeWorld requested changes

2024-08-05 14:21 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
> +    public dateInputChange(event: Event): void {
js doc

2024-08-06 11:38 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
> +    public dateInputChange(event: Event): void {
done

2024-08-07 08:43 UTC, dvCodeWorld requested changes

2024-08-07 08:43 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
> +     *
Get input value

2024-08-07 08:43 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
> +        this.inputChange= inputValue;
```suggestion
        this.inputChange = inputValue;
```

2024-08-07 08:55 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
> +        this.inputChange= inputValue;
done

2024-08-07 09:25 UTC, dvCodeWorld approved these changes

2024-08-07 09:26 UTC, merged