Ankit | test | By Default, all the invoices, credit notes and debit notes should be shown in the GSTR 1 report in the respective sections
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13764
Opened 2024-08-09 11:20 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cw3tez0

2024-08-09 11:31 UTC, nisha-walkover requested changes

2024-08-09 11:31 UTC, nisha-walkover commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts
> +        //  give default value select all Transaction
remove commented code

2024-08-09 11:39 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts
> +        //  give default value select all Transaction
done

2024-08-12 12:17 UTC, nisha-walkover approved these changes

2024-08-12 12:19 UTC, dilpreetsinghofficial approved these changes

2024-08-12 12:36 UTC, merged