Divyanshu | Test | Version 3 - Get all voucher page
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13782
Opened 2024-08-16 14:42 UTC by dvCodeWorld

https://app.clickup.com/t/86cupmt5p

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/http-wrapper.service.ts
> +        // options.headers["X-Tenant"] = this.generalService.getUtmParameter("X-Tenant");
Confirm with @dilpreetsinghdang  sir

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/convert-bill-dialog/convert-bill-dialog.component.html
> +            <button mat-stroked-button color="primary" type="submit">Save</button>
translation

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
> +                console.log(invoiceForm);
remove

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
> +                console.log(invoiceForm);
remove

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.html
>                                  <span>+ New Estimate</span>
translation

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                    <!-- *ngIf="element.action !== 'invoiced'" ========== NEED TO ASK WHY THIS -->
????

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                            <!-- ======================= Ask what is use of this ======================= -->
????

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                            <button mat-menu-item (click)="showPaymentDialog(element)">Paid</button>
translation

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/payment-dialog/payment-dialog.component.ts
> +    public amountCurrency: string = "";
JS Doc

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/po-bulk-update/po-bulk-update.component.html
> +  po-bulk-update works!
Need to check

2024-08-16 20:29 UTC, dvCodeWorld commented on apps/web-giddh/src/assets/locale/vouchers/preview/en.json
> +    "po_bulkupdate_error": "Please choose a field to update"
translate Hindi Marathi

2024-08-20 12:49 UTC, ravinderwalkover requested changes

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/contact/contact.component.scss
> +.date-range-picker {
check this

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
> -        this.onChangeFieldVisibility(null, null, null);
check this

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.scss
> -.design-tool {
check this

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/utility/vouchers.store.ts
> +        private salesService: SalesService,
move methods to voucher service

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/utility/vouchers.store.ts
> +    readonly POBulkUpdateAction = this.effect((data: Observable<{ payload: any, actionType: string }>) => {
give proper naming

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-1.scss
> -.select-physical-product {
check removed css

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-2.scss
> -.ledger-attachments-popup {
check removed css

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/purchase-order/en.json
> +    "delivery_in_day": "delivery_in_day[DAYS] day",
correct this

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/payment-dialog/payment-dialog.component.ts
> +    public ngOnInit(): void {
add js doc in all methods

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/email-send-dialog/email-send-dialog.component.html
> -                <div class="my-3" *ngIf="!invoiceType?.isEstimateInvoice && !invoiceType?.isProformaInvoice && !invoiceType?.isDebitNote && !invoiceType?.isCreditNote && !invoiceType?.isReceiptInvoic
don't remove this

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/email-send-dialog/email-send-dialog.component.html
> -                <div class="d-flex column-gap1" [ngClass]="{'mr-t1' : invoiceType?.isEstimateInvoice || invoiceType?.isProformaInvoice || invoiceType?.isDebitNote || invoiceType?.isCreditNote || invo
don't remove this

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/convert-bill-dialog/convert-bill-dialog.component.html
> +<form [formGroup]="form" autocomplete="off" novalidate *ngIf="showForm" (ngSubmit)="onFormSubmit()">
remove ngIf

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/convert-bill-dialog/convert-bill-dialog.component.ts
> +  public showForm: boolean = true;
remove var

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/convert-bill-dialog/convert-bill-dialog.component.ts
> +  private setPurchaseOrderValue(voucher): FormGroup {
```suggestion
  private getPurchaseOrderValue(voucher?: any): FormGroup {
```

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/convert-bill-dialog/convert-bill-dialog.component.ts
> +        formAarry.push(this.setPurchaseOrderValue(this.vouchers));
send only in array form

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/advance-search/advance-search.component.html
> +        <button mat-stroked-button color="primary" (click)="search()">Search</button>
do translation

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/advance-search/advance-search.component.ts
> +    public invoiceTotalRangeChanged(item: IOption) {
add js doc and return type in all methods

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/bulk-update/bulk-update.component.html
> +                    <span class="max-character-label">Characters left:&nbsp;</span>
do translation

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/bulk-update/bulk-update.component.ts
> +    public bulkUpdateRequest(payload: any, actionType: string): void {
add js doc

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
>                                      Expiry Date
translation

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                    {{ grandTotal }}
check this

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
>                                  <td mat-cell *matCellDef="let element" matTooltip="In INR: 1.239 (Conversion Rate: 0.005)"
check this

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +            <mat-tab label="Purchase Order" *ngIf="activeTabGroup === 2">
do translation

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +            <mat-tab label="Bill" *ngIf="activeTabGroup === 2">
translation

2024-08-20 12:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +            <mat-tab label="Settings" class="setting-svg">
hide settings tab for now

2024-08-21 05:52 UTC, ravinderwalkover requested changes

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/apiurls/inventory.api.ts
> -        REPORT: 'company/:companyUniqueName/inventory-adjustment/adjustment-report?page=:page&from=:from&to=:to&count=:count&sortBy=:sortBy&sort=:sort&q=:q&searchBy=:searchBy&inventoryType=:inventory
ye q remove kiya?

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/apiurls/inventory.api.ts
> -        GET_REASON: 'company/:companyUniqueName/inventory-adjustment/reason/get-all?count=2000',// GET call
ye q change kiya?

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/apiurls/logs.api.ts
> -    GET_AUDIT_LOGS_V2: 'v2/company/:companyUniqueName/logs?page=:page', // post call
ye q remove kiya?

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/general.service.ts
> +            if ([VoucherTypeEnum.sales, VoucherTypeEnum.creditNote, VoucherTypeEnum.debitNote, VoucherTypeEnum.purchase, VoucherTypeEnum.receipt, VoucherTypeEnum.payment, 'purchase-order']?.indexOf(s
use enum for purchase order

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/bulk-export-voucher/bulk-export-voucher.component.ts
> +    providers:[VoucherComponentStore]
remove provider

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.html
> -    <div class="help-support-aside setting-sidebar-wrapper" *ngIf="asideInventorySidebarMenuState === 'in'">
check this

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.scss
> -.desktop-header .hamburger-menu {
check this

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> -            }
check this file changes

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> -            this.closeAccountModal(true);
check this

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/bulk-update/bulk-update.component.html
> +                type="text"
remove type

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/bulk-update/bulk-update.component.ts
> +
remove extra space

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/convert-bill-dialog/convert-bill-dialog.component.ts
> +  private getPurchaseOrderValue(voucher?: any): FormGroup {
```suggestion
  private getPurchaseOrderFormGroup(voucher?: any): FormGroup {
```

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/convert-bill-dialog/convert-bill-dialog.component.ts
> +    this.initForm();
format code with 4 spaces

2024-08-21 05:52 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/utility/vouchers.store.ts
> +        private bulkVoucherExportService: BulkVoucherExportService
move methods to voucher service

2024-08-21 07:11 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/services/apiurls/inventory.api.ts
> -        REPORT: 'company/:companyUniqueName/inventory-adjustment/adjustment-report?page=:page&from=:from&to=:to&count=:count&sortBy=:sortBy&sort=:sort&q=:q&searchBy=:searchBy&inventoryType=:inventory
revert

2024-08-21 07:12 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/services/apiurls/logs.api.ts
> -    GET_AUDIT_LOGS_V2: 'v2/company/:companyUniqueName/logs?page=:page', // post call
check this

2024-08-21 07:17 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/header.component.html
> -    <div class="help-support-aside setting-sidebar-wrapper" *ngIf="asideInventorySidebarMenuState === 'in'">
revert

2024-08-21 07:19 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/header.component.scss
> -.desktop-header .hamburger-menu {
remove this on test

2024-08-21 07:21 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> -            this.closeAccountModal(true);
remove this on test

2024-08-21 07:32 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/header.component.ts
> -            }
When changes on test do with me

2024-08-23 06:43 UTC, dvCodeWorld commented
Infected Branch hence closed this pr

2024-08-23 06:43 UTC, closed without merging