Ankit | Stage | PROD - When user is not passing the business nature then undefined is getting passed
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #13993
Opened 2024-09-27 06:00 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cwm3cyb

2024-10-08 10:09 UTC, dvCodeWorld approved these changes, later dismissed

2024-10-10 11:20 UTC, dvCodeWorld requested changes

2024-10-10 11:20 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vat-report/obligations/obligations.component.scss
> +    min-height: calc(100vh - 90px);
move in line no 2

2024-10-10 11:35 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/vat-report/obligations/obligations.component.scss
> +    min-height: calc(100vh - 90px);
done

2024-10-10 11:36 UTC, dvCodeWorld submitted a review, later dismissed

2024-10-14 10:30 UTC, dvCodeWorld submitted a review, later dismissed

2024-10-14 11:22 UTC, dvCodeWorld submitted a review, later dismissed

2024-10-15 08:48 UTC, dilpreetsinghofficial approved these changes, later dismissed

2024-10-15 17:39 UTC, dilpreetsinghofficial approved these changes, later dismissed

2024-10-16 09:59 UTC, dilpreetsinghofficial requested changes

2024-10-16 09:59 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/add-company/add-company.component.ts
> +        this.nextStepForm();
move into html

2024-10-16 09:59 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/create-branch-transfer/create-branch-transfer.component.html
> -                                                            ]?.length === 1
check this

2024-10-16 11:18 UTC, ravinderwalkover requested changes

2024-10-16 11:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/models/db/db.ts
> -                setTimeout(() => {
why removed this?

2024-10-16 11:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        this.store.pipe(select(s => s.session.lastState), takeUntil(this.destroyed$)).subscribe(s => {
what's the need of changing this logic?

2024-10-16 11:18 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/create-branch-transfer/create-branch-transfer.component.html
> -                                                            destinationWarehouses[
why changing this logic? and how is it useful?

2024-10-16 11:42 UTC, dvCodeWorld commented on apps/web-giddh/src/app/models/db/db.ts
> -                setTimeout(() => {
No need of set timeout here.

2024-10-16 11:42 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        this.store.pipe(select(s => s.session.lastState), takeUntil(this.destroyed$)).subscribe(s => {
this is required

2024-10-16 11:52 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/create-branch-transfer/create-branch-transfer.component.html
> -                                                            ]?.length === 1
done

2024-10-16 11:53 UTC, ravinderwalkover approved these changes

2024-10-16 11:54 UTC, dilpreetsinghofficial approved these changes

2024-10-16 11:55 UTC, merged