Nisha | Stage | Convert Tax module into material
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14016
Opened 2024-10-03 06:57 UTC by nisha-walkover

https://app.clickup.com/t/86cwmfhbm

2024-11-12 10:00 UTC, dvCodeWorld requested changes

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/filing.component.html
> +                    <!-- <tabset #staticTabs id="c-tab" class="custom-tabs gstr-tabs-head">
Remove comment

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/filing.component.html
> +                            *ngIf="selectedTab === localeData?.filing?.tabs?.overview || !selectedTabId"
check this logic and implement tab logic

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/filing.component.html
> +                        <!-- <div *ngIf="selectedTab === localeData?.filing?.tabs?.reconcilation || selectedTabId === 1"> -->
remove comment

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/filing.component.html
> +                                    <img src="assets/images/file-successful.svg" />
alt attribute

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/filing.component.html
> +                                    <button
In material

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +                        (click)="pushToPortalModal?.show()">
Change modal to dailog

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +            <div class="d-inline-flex align-items-center column-gap1" dropdown #dropdown="bs-dropdown">
change dropdown to mat menu

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +        (cancelConfirmationEvent)="cancelConfirmationModel?.show()"
modal to dialog

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +        (cancelCallBack)="cancelConfirmationModel.hide()"
check this code

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
> +    // @ViewChild('cancelConfirmationModel', { static: true }) public cancelConfirmationModel: ModalDirective;
remove

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
> +        // this.cancelConfirmationModel.toggle();
change the logic

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
> +                    <mat-tab-group
Add tab functionality

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
> +                                <mat-paginator
functionality check

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
> +                                <mat-paginator
check

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
> +                                    (page)="reconcilePageChanged($event, 'partiallymatched')"
check

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
> +                                <mat-paginator
check

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gst.component.html
> +                <dropdown-field
check

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/modals/gst-aside-menu/gst-aside-menu.component.html
> +<div class="modal-header theme-bg d-flex justify-content-between">
Check whole component fix

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
> +                    [showClear]="false"
check this

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
> +                    [label]="commonLocaleData?.app_gstin"
check

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
> +                                                (click)="sortbyApi('invoiceDate', 'asc')"
change sorting code

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
> +                                            dropdownToggle
change into material

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
> +                            [label]="localeData?.vehicle_no_label"
check this whole component

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.ts
> +    // public openModal(ewayItem: any, template: TemplateRef<any>) {
remove

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
> +                            <!-- <dropdown-field
check

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
> +                            <amount-field [amount]="element.taxRate" [currencySymbol]="false" [currencyCode]="false"></amount-field>
check this code

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
> +import { UntypedFormControl } from "@angular/forms";
remove

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
> +    displayedColumns: string[] = [
js doc

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/taxes/confirmation/confirmation.model.component.html
> +    <!-- <div class="modal-header">
check commented code

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/taxes/setting.taxes.component.ts
> +    public deleteTax(taxToDelete): void {
check

2024-11-12 10:00 UTC, dvCodeWorld commented on apps/web-giddh/src/assets/css/global/color.scss
> +// .bg-white {
remove

2025-01-24 05:20 UTC, dvCodeWorld commented
@coderabbit

2025-01-24 06:58 UTC, dilpreetsinghofficial requested changes

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/app.constant.ts
> +export const GST_UTILITY_DOWNLOAD_LINK = "https://www.gst.gov.in/download/returns";
Add documentation

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/gst/filing/filing.component.ts
> +        } else if(this.selectedGst === GstReport.Gstr2) {
format code

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +                        (click)="openSettingAsidePane($event, 'TAXPRO')"
use enum here

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
> +                this.openSettingAsidePane(null, 'TAXPRO');
use enum here

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts
> +        if (invoice.voucherType !== this.voucherTypeEnum.purchase) {
```suggestion
        if (invoice?.voucherType !== this.voucherTypeEnum.purchase) {
```

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
> +
remove spacing

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
> +            (click)="goBack()"
Please correct method name

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
> +                class="table transactions-table w-100 zi-table table-hover"
check zi-table

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts
> +    public invoicesEnum: string = InvoicesEnum.Invoices;
add documentation

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
> +    /** Holds true if searching is in progress */
```suggestion
    /** True if searching is in progress */
```

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
> +                localStorage.setItem('currencyDecimalType', response.request?.balanceDecimalPlaces);
Please move into getProfileInfo Response and remove from here

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/form-fields/reactive-dropdown-field/reactive-dropdown-field.component.html
> +                    [readonly]="readonly" [disabled]="disabled" [matAutocomplete]="auto" [name]="name" [autocomplete]="autocomplete"
do not handle one more attribute for disable we have already readonly property

2025-01-24 06:58 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/theme/form-fields/reactive-dropdown-field/reactive-dropdown-field.component.html
> +            [readonly]="readonly" [disabled]="disabled" [matAutocomplete]="auto" [name]="name" [autocomplete]="autocomplete"
please also check here

2025-01-24 08:55 UTC, dvCodeWorld commented on apps/web-giddh/src/app/app.constant.ts
> +export const GST_UTILITY_DOWNLOAD_LINK = "https://www.gst.gov.in/download/returns";
Done

2025-01-24 08:56 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/filing.component.ts
> +        } else if(this.selectedGst === GstReport.Gstr2) {
Done

2025-01-24 09:54 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +                        (click)="openSettingAsidePane($event, 'TAXPRO')"
Done

2025-01-24 09:54 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
> +                this.openSettingAsidePane(null, 'TAXPRO');
Done

2025-01-24 09:55 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts
> +        if (invoice.voucherType !== this.voucherTypeEnum.purchase) {
Done

2025-01-24 09:57 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
> +
Done

2025-01-24 09:59 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
> +            (click)="goBack()"
Done

2025-01-24 10:02 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
> +                class="table transactions-table w-100 zi-table table-hover"
removed

2025-01-24 10:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts
> +    public invoicesEnum: string = InvoicesEnum.Invoices;
Done

2025-01-24 10:03 UTC, dvCodeWorld commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
> +    /** Holds true if searching is in progress */
Done

2025-01-24 10:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/form-fields/reactive-dropdown-field/reactive-dropdown-field.component.html
> +            [readonly]="readonly" [disabled]="disabled" [matAutocomplete]="auto" [name]="name" [autocomplete]="autocomplete"
Done

2025-01-24 10:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/theme/form-fields/reactive-dropdown-field/reactive-dropdown-field.component.html
> +                    [readonly]="readonly" [disabled]="disabled" [matAutocomplete]="auto" [name]="name" [autocomplete]="autocomplete"
Done

2025-01-24 10:14 UTC, dvCodeWorld commented on apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
> +                localStorage.setItem('currencyDecimalType', response.request?.balanceDecimalPlaces);
Done

2025-01-24 11:00 UTC, dilpreetsinghofficial approved these changes

2025-01-24 14:09 UTC, dvCodeWorld approved these changes

2025-01-24 14:09 UTC, merged