Ankit | Test | Prod - On create/update voucher flow, discount value is displaying with many digits after decimal.
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14131
Opened 2024-10-19 10:23 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cwu183q

2024-11-05 11:11 UTC, dvCodeWorld requested changes

2024-11-05 11:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/general.service.ts
> +     *
```suggestion
```

2024-11-05 11:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/general.service.ts
> +     * @param {number} companyDecimalPlaces
```suggestion
     * @param {number} [companyDecimalPlaces=2]
```

2024-11-05 11:20 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/services/general.service.ts
> +     *
Done

2024-11-05 11:20 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/services/general.service.ts
> +     * @param {number} companyDecimalPlaces
Done

2024-11-07 04:42 UTC, dvCodeWorld approved these changes

2024-11-07 04:42 UTC, merged