Dilpreet | Stage | Branch Wise UI Changes
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14157
Opened 2024-10-23 14:07 UTC by dilpreetsinghofficial

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2024-12-09 15:11 UTC, dvCodeWorld requested changes

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
> +                                                [ngClass]="{
```suggestion
                                                [ngClass]="option?.consolidatedBranch ? 'icon-company-profile' : 'icon-branch-icon'
```

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.ts
> +                this.isCompany = this.generalService.currentOrganizationType !== OrganizationType.Branch && response?.length > 1;
```suggestion
                this.isCompany = this.generalService.currentOrganizationType !== OrganizationType.Branch && response.length > 1;
```

check everywhere same code

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
> +                                        [ngClass]="{
use ternary operator

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
> +                                                    'icon-company-profile': option?.consolidatedBranch,
use ternary

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/new-inventory/component/manufacturing/list-manufacturing/list-manufacturing.component.ts
> +            if (response) {
check formating

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/branch/branch.component.html
> +                                                                    branch.consolidatedBranch
```suggestion
                                                                    <span *ngIf="branch.consolidatedBranch">({{ localeData?.consolidated}})</span>
```

personal suggestion

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
> +                <div class="row pd-b1 mt-3" *ngIf="(organizationType === 'COMPANY') && voucherApiVersion === 2">
```suggestion
                <div class="row pd-b1 mt-3" *ngIf="organizationType === 'COMPANY' && voucherApiVersion === 2">
```

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
> +                <div class="row mt-3" *ngIf="(organizationType === 'COMPANY') && voucherApiVersion === 2">
```suggestion
                <div class="row mt-3" *ngIf="organizationType === 'COMPANY' && voucherApiVersion === 2">
```

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
> +            <div class="row mr-0 mt-3" *ngIf="(organizationType === 'COMPANY')">
```suggestion
            <div class="row mr-0 mt-3" *ngIf="organizationType === 'COMPANY'">
```

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
> +                                                >{{ commonLocaleData?.app_company }}
check this in hindi and marathi also

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
>                                          <!-- <span class="font-11 branch-company-name">{{companyBranches?.name}}</span> -->
Why not remove this ??

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                let tab = (!this.isCompany && !this.isConsolidatedBranch )? ['pending', 'templates'] : ['pending', 'settings', 'templates'];
```suggestion
                let tab = (!this.isCompany && !this.isConsolidatedBranch ) ? ['pending', 'templates'] : ['pending', 'settings', 'templates'];
```

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +            } else if (this.activeTabGroup === 2) {
else if (this.activeTabGroup === 2)

why write same in two palce line 803 and 809

2024-12-09 15:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                    voucherType = "estimates";
assign value from enum if possible

and if use please check in case of debit-note, credit-note and purchase-order

2024-12-10 06:42 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/branch/branch.component.html
> +                                                                    branch.consolidatedBranch
no need

2024-12-10 06:50 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
> +                                                >{{ commonLocaleData?.app_company }}
correct

2024-12-10 06:51 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
>                                          <!-- <span class="font-11 branch-company-name">{{companyBranches?.name}}</span> -->
this is already commented

2024-12-10 06:55 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +            } else if (this.activeTabGroup === 2) {
corrected

2024-12-10 06:56 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                    voucherType = "estimates";
I had worked on only for pending related vouchers

2024-12-11 06:02 UTC, dvCodeWorld approved these changes, later dismissed

2024-12-12 11:11 UTC, ravinderwalkover requested changes

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/daybook/daybook.component.html
> +                                *ngIf="currentCompanyBranches?.length > 2 &&( currentOrganizationType === 'COMPANY'|| isConsolidatedBranch)"
```suggestion
                                *ngIf="currentCompanyBranches?.length > 2 && (currentOrganizationType === 'COMPANY'|| isConsolidatedBranch)"
```

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts
> +            if (response) {
format code

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
> +            if (response) {
why this is under another subscription?

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/branch-transfer/list-branch-transfer/list-branch-transfer.component.ts
> +    public isConsolidatedBranch: boolean;
move this above getter

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/manufacturing/list-manufacturing/list-manufacturing.component.ts
> +                        this.store.pipe(select(select => select.branchConsolidated), takeUntil(this.destroyed$)).subscribe(response => {
why this is inside another subscription?

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/manufacturing/list-manufacturing/list-manufacturing.component.ts
> +        if ((this.currentOrganizationType === OrganizationType.Company|| this.isConsolidatedBranch) && this.allWarehouses?.length) {
```suggestion
        if ((this.currentOrganizationType === OrganizationType.Company || this.isConsolidatedBranch) && this.allWarehouses?.length) {
```

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/manufacturing/list-manufacturing/list-manufacturing.component.ts
> +        if ((this.universalDate && (this.manufacturingSearchRequest.from !== dayjs(this.universalDate[0]).format(GIDDH_DATE_FORMAT) || this.manufacturingSearchRequest.to !== dayjs(this.universalDate[
```suggestion
        if ((this.universalDate && (this.manufacturingSearchRequest.from !== dayjs(this.universalDate[0]).format(GIDDH_DATE_FORMAT) || this.manufacturingSearchRequest.to !== dayjs(this.universalDate[1]).format(GIDDH_DATE_FORMAT))) || this.manufacturingSearchRequest.product || this.manufacturingSearchRequest.productVariant || ((this.currentOrganizationType === OrganizationType.Company || this.isConsolidatedBranch) && this.manufacturingSearchRequest.branchUniqueName && this.manufacturingSearchRequest.branchUniqueName !== this.currentBranch.uniqueName) || this.manufacturingSearchRequest.warehouseUniqueName || this.manufacturingSearchRequest.inventoryType || this.manufacturingSearchRequest.searchBy || this.manufacturingSearchRequest.searchOperation || this.manufacturingSearchRequest.searchValue) {
```

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/report-filters/report-filters.component.ts
> +            if (!this.isCompany || !this.isConsolidatedBranch) {
```suggestion
            if (!this.isCompany && !this.isConsolidatedBranch) {
```

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/report-filters/report-filters.component.ts
> +                if (!this.isCompany || !this.isConsolidatedBranch) {
```suggestion
                if (!this.isCompany && !this.isConsolidatedBranch) {
```

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/report-filters/report-filters.component.ts
> +        if (!this.isCompany || !this.isConsolidatedBranch) {
```suggestion
        if (!this.isCompany && !this.isConsolidatedBranch) {
```

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-inventory/component/report-filters/report-filters.component.ts
> +        if (!this.isCompany || !this.isConsolidatedBranch) {
```suggestion
        if (!this.isCompany && !this.isConsolidatedBranch) {
```

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +                const branches = cloneDeep(response.body);
what's the use of clone deep?

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +                this.branches = branches.results?.filter(branch => !branch?.isCompany)?.map(branch => {
```suggestion
                this.branches = this.allBranches?.map(branch => {
```

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +            <ng-container *ngIf="(!isCompany && !isConsolidatedBranch)">
add this condition on mat-tab directly

2024-12-12 11:11 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +        this.getInvoiceSettings();
already getting called below. why calling here?

2024-12-13 07:17 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
> +            if (response) {
by mistake

2024-12-13 07:35 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> +                const branches = cloneDeep(response.body);
no need

2024-12-19 12:11 UTC, ravinderwalkover approved these changes

2024-12-19 12:11 UTC, merged