Ankit| Stage | Version 3 - plan permission
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14170
Opened 2024-10-26 12:33 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cwm1bc1

-->   This is complete in the present time.  <---

2024-11-16 12:44 UTC, dvCodeWorld requested changes

2024-11-16 12:44 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.scss
> +// @media screen and (min-width:992px){
Remove commnet

2024-11-16 12:44 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
>                  <li>
```suggestion
```

2024-11-16 12:44 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
>                  </li>
```suggestion
```

2024-11-16 12:44 UTC, dvCodeWorld commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +                    <div class="flex-content">{{ commonLocaleData?.app_no_access_limit_module }}</div>
```suggestion
                    <div>{{ commonLocaleData?.app_no_access_limit_module }}</div>
```

2024-11-18 10:08 UTC, dvCodeWorld submitted a review, later dismissed

2024-11-18 10:36 UTC, dvCodeWorld submitted a review, later dismissed

2024-11-19 10:31 UTC, dilpreetsinghofficial submitted a review, later dismissed

2024-11-19 10:47 UTC, ravinderwalkover requested changes

2024-11-19 10:47 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/en.json
> +    "app_no_access_limit_module": "You currently don’t have access to this module. Upgrade your plan to unlock it without any hassle",
```suggestion
    "app_no_access_limit_module": "You currently don't have access to this module. Upgrade your plan to unlock it without any hassle",
```

2024-11-19 10:47 UTC, ravinderwalkover commented on apps/web-giddh/src/app/onboarding/onboarding.component.ts
> +    public syncWithTallyHelpDocUrl: string = "https://giddh.com/help/sync-with-tally-1591360375828781";
create constant for this in app constant and use

2024-11-19 10:47 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +                            [disabled]="(activeCompany$ | async)?.subscription?.planDetails?.restrictedModules.hasOwnProperty('Tax filing')">
put all modules name in a constant and use at all places

2024-11-19 10:47 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
> +                <span class="pull-right d-flex align-items-center column-gap5">
create a common upgrade button module and use at all places

2024-11-19 10:47 UTC, ravinderwalkover commented on apps/web-giddh/src/app/add-company/add-company.component.html
> +                                                (click)="remainingUsers > (thirdStepForm.get('creatorSuperAdmin').value === 'true') + thirdStepForm.get('permissionRoles').value.length ? addNewUser()
kya logic he ye?

2024-11-20 12:13 UTC, dvCodeWorld approved these changes

2024-11-20 12:25 UTC, dvCodeWorld submitted a review, later dismissed

2024-11-20 12:30 UTC, dvCodeWorld approved these changes

2024-11-20 12:32 UTC, ravinderwalkover approved these changes

2024-11-20 12:33 UTC, merged