Divyanshu | Stage | "Quantity recorded can't be more than order" error coming in updating PB for stock and updating qty when no PO linked
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14201
Opened 2024-11-08 13:08 UTC by dvCodeWorld

https://app.clickup.com/t/86cwnehh0

2024-12-04 07:15 UTC, dilpreetsinghofficial requested changes

2024-12-04 07:15 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
> +    private getStockMaxQuantity(entryData): number | undefined {
Add type for entryData

2024-12-04 07:15 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
> +        if (this.invoiceType.isPurchaseInvoice && entryData.purchaseOrderLinkSummaries?.length > 0) {
```suggestion
        if (this.invoiceType.isPurchaseInvoice && entryData?.purchaseOrderLinkSummaries?.length > 0) {
```

2024-12-04 09:42 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
> +    private getStockMaxQuantity(entryData): number | undefined {
Done

2024-12-04 09:46 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
> +        if (this.invoiceType.isPurchaseInvoice && entryData.purchaseOrderLinkSummaries?.length > 0) {
No need here because entryData will always  present

2024-12-04 10:16 UTC, dilpreetsinghofficial approved these changes, later dismissed

2024-12-16 08:56 UTC, ravinderwalkover approved these changes

2024-12-16 11:33 UTC, merged