Dilpreet | Stage | Pending Related Voucher
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14223
Opened 2024-11-14 07:25 UTC by dilpreetsinghofficial

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2024-12-02 09:11 UTC, dvCodeWorld requested changes

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
> +                this.router.navigate([`/pages/vouchers/preview/${this.queryParams.voucherType}/pending`]);
check this for all voucher

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    /** selected pending voucher */
```suggestion
    /** Selected pending voucher */
```

Do this for all

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +        { label: 'Credit Note', value: 'credit note' },
Use translated label

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +
```suggestion
```

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +            } else if (this.voucherType === 'receipt' && this.activeModule === 'pending') {
use enum if possible

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +            } else if (this.voucherType === 'payment' && this.activeModule === 'pending') {
use enum if possible

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
>              if (this.voucherType === 'payment' && this.activeModule === 'list') {
use enum if possible

Here to

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +     *Fetch ledgers for invoices.
```suggestion
     * Fetch ledgers for invoices.
```

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                { queryParams: { entryUniqueNames: uniqueNames, voucherType:this.voucherType } }
```suggestion
                { queryParams: { entryUniqueNames: uniqueNames, voucherType: this.voucherType } }
```

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                [`/pages/vouchers/${voucher.voucherType}/${voucher.account?.uniqueName}/create`],
```suggestion
                [`/pages/vouchers/${voucher.voucherType ?? this.voucherType}/${voucher.account?.uniqueName}/create`],
```

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                            {{ element?.account?.name | titlecase }}
```suggestion
                                            {{ element.account?.name | titlecase }}
```

2024-12-02 09:11 UTC, dvCodeWorld commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                            {{ element?.account?.name | titlecase }}
check every where

2024-12-02 09:52 UTC, dvCodeWorld approved these changes, later dismissed

2024-12-02 09:56 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/create/create.component.ts
> +                this.router.navigate([`/pages/vouchers/preview/${this.queryParams.voucherType}/pending`]);
this is working for only sales, credit note , debit note etc

2024-12-02 10:14 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                [`/pages/vouchers/${voucher.voucherType}/${voucher.account?.uniqueName}/create`],
No need

2024-12-02 10:37 UTC, dvCodeWorld approved these changes, later dismissed

2024-12-02 11:23 UTC, ravinderwalkover requested changes

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +        return true;
remove useless return statement

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    private groupPendingVouchersByAccount(): Record<string, GenBulkInvoiceGroupByObj[]> {
inform usage of Record

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    private flattenGroupedVouchers(grouped: Record<string, GenBulkInvoiceGroupByObj[]>): string[] {
rename parameters

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                { label: this.localeData.tabs.credit_note, value: 'credit note' },
use voucher type enum

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    public previewInvoice(): void {
correct method name based on usage

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    public isSameAccount(): boolean {
rename method

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    private decrementPageIfNeeded(): void {
mention the usage of this logic

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    private dispatchLedgerRequest(): void {
rename method names

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +        this.componentStore.isBulkInvoiceGeneratedWithoutError$.subscribe(result => {
explain usage

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                this.selectAllPendingVouchers(false);
```suggestion
                this.selectAllPendingVouchers({ checked: false });
```

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +        private commonActions: CommonActions
remove useless import

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> -// pending-table
remove unused interface also

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                            <p *ngIf="transaction?.inventory && transaction.inventory?.stock">
```suggestion
                                            <p *ngIf="transaction?.inventory?.stock">
```

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                                    [currencyCode]="activeCompany?.baseCurrency"
use account base currency

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                                    <img src="./assets/images/path.svg" />
use correct image path to handle electron

2024-12-02 11:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.html
> +                                                [currencyCode]="activeCompany?.baseCurrency"
use account currency

2024-12-02 11:29 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    private groupPendingVouchersByAccount(): Record<string, GenBulkInvoiceGroupByObj[]> {
Record is the use for key and values where we know what the type of key and value is.

2024-12-02 11:44 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +    private decrementPageIfNeeded(): void {
This is the use case for when decrement page automatically when records are deleted or generated

2024-12-02 11:46 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +        this.componentStore.isBulkInvoiceGeneratedWithoutError$.subscribe(result => {
removed

2024-12-03 10:00 UTC, ravinderwalkover approved these changes

2024-12-03 10:01 UTC, merged