Shivani | stage | Fetch Go cardless integrated bank balance in dashboard page
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14273
Opened 2024-11-28 14:00 UTC by shivanivani02

https://app.clickup.com/t/86cx4gg7h

2025-04-04 07:45 UTC, dvCodeWorld requested changes

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.scss
> +.dashboard-filter {
optimise

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.scss
> +    display: inline-flex;
use class d-inline-flex align-items-center

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.ts
> +        this.callBackBroadcast = new BroadcastChannel("call-back-subscriptiy367on");
use correct name

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.ts
> +    public getBank(): void {
doc

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.ts
> +                    if (response === 'integrate') {
Use enum

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.ts
> +    private getAccounts(fromDate: string, toDate: string, groupUniqueName: string, pageNumber?: number, requestedFrom?: string, refresh?: string, count: number = 200, query?: string, sortBy: string =
update doc

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.ts
> +     * This will be yse get bank account by its unique name
```suggestion
     * This will be use get bank account by its unique name
```

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.ts
> +                if (response === 'closeDialog') {
remove

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/institutions-list/institutions-list.component.ts
> +        this.openedWindow = this.generalService.openCenteredWindow(url, '', width, height);
optimise and also write correct width

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/institutions-list/institutions-list.component.ts
> +        this.searchForm = this.formBuilder.group({
why use form group for single form control

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-link/bank-link.component.html
> +        <button class="close" (click)="closeDialog()">×</button>
use direct icon 

<i (click)="closeDialog() aria-label="close icon" class="icon-cross"></i>

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/ledger/ledger.component.ts
> +        localStorage.setItem('refNo', null);
before set value you not checking localStorage but before removing you check ?

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/institutions-list/institutions-list.component.html
> +    <button class="close" (click)="closeDialog()">×</button>
use icon

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/integration/institutions-list/institutions-list.component.ts
> +    public closeDialog(): void {
check the login why close using this function

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration-popup/bank-integration-popup.component.html
> +        <h3>Bank Account</h3>
Translation

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration-popup/bank-integration-popup.component.scss
> +        justify-content: center;
use classes
write all code in scss

in over all file

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration-popup/bank-integration-popup.component.scss
> +    div {
```suggestion
    > div {
```

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration-popup/bank-integration-popup.component.html
> +        <button class="close" (click)="closeDialog()">×</button>
use icon

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration-popup/bank-integration-popup.component.ts
> +    public closeDialog(): void {
remove unsed function and also use common function to close dialog

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration.component.html
> +            <ng-template>
Why write  <ng-template>

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration.component.html
> +                <div class="form-group mr-l2">
use col inside row

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration.component.html
> +                        <div class="col-md-4">
```suggestion
                        <div class="col-4">
```

correct all places

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration.component.html
> +                        <span class="mr-l1 action-div" *ngIf="!isIciciBankSupportedCountry">
action-div correct name

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration.component.ts
> +    /**
```suggestion
    
    /**
```

2025-04-04 07:45 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration.component.ts
> +        this.imgPath = (isElectron) ? 'assets/images/' : AppUrl + APP_FOLDER + 'assets/images/';
```suggestion
        this.imgPath = isElectron ? 'assets/images/' : AppUrl + APP_FOLDER + 'assets/images/';
```

2025-04-05 07:08 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.ts
> +                    if (response === 'integrate') {
not required

2025-04-05 07:36 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/bank-integration/bank-integration-popup/bank-integration-popup.component.ts
> +    public closeDialog(): void {
not required

2025-04-05 07:36 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/integration/institutions-list/institutions-list.component.ts
> +    public closeDialog(): void {
not required

2025-04-05 08:26 UTC, dvCodeWorld approved these changes

2025-04-05 08:27 UTC, dilpreetsinghofficial approved these changes

2025-04-05 08:27 UTC, merged