Ankit | Stage | PROD - Date range is not getting reset when user change the date from universal date picker
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14270
Opened 2024-11-28 12:01 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cx0j3t3

2024-12-03 11:49 UTC, dvCodeWorld approved these changes, later dismissed

2024-12-04 11:10 UTC, ravinderwalkover requested changes

2024-12-04 11:10 UTC, ravinderwalkover commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                        this.router.navigate(['/pages/vouchers/preview/' + this.voucherType + '/' + this.activeModule], {
update the code with better logic

2024-12-05 05:55 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/vouchers/list/list.component.ts
> +                        this.router.navigate(['/pages/vouchers/preview/' + this.voucherType + '/' + this.activeModule], {
Done

2024-12-16 08:34 UTC, dvCodeWorld approved these changes

2024-12-16 09:15 UTC, dilpreetsinghofficial approved these changes

2024-12-16 11:00 UTC, ravinderwalkover approved these changes

2024-12-16 11:01 UTC, merged