Ankit | Stage | Fetch Go cardless integrated bank balance in dashboard page
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14315
Opened 2024-12-09 14:26 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cx4gg7h

2024-12-11 05:39 UTC, dvCodeWorld requested changes

2024-12-11 05:39 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/components/bank-accounts/bank-accounts.component.ts
> +        this.store.pipe(select(profileObj => profileObj.settings.profile), takeUntil(this.destroyed$)).subscribe((profile) => {
Write this in component store

2024-12-11 05:39 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/home.store.ts
> +                            if (res?.status === "success" && res?.body) {
```suggestion
                            if (res?.status === "success" && res.body) {
```

2024-12-11 05:39 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/home.store.ts
> +                            if (res?.status === "success" && res?.body) {
```suggestion
                            if (res.status === "success" && res?.body) {
```

2024-12-11 05:39 UTC, dvCodeWorld commented on apps/web-giddh/src/app/home/home.store.ts
> +                                res?.message && this.toaster.showSnackBar("error", res.message);
```suggestion
                                res.message && this.toaster.showSnackBar("error", res.message);
```

2024-12-11 05:39 UTC, dvCodeWorld commented on apps/web-giddh/src/app/services/contact.service.ts
> +     * @returns {Observable<BaseResponse<any, any>>}
check doc and fix Observable type

2024-12-11 08:46 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/services/contact.service.ts
> +     * @returns {Observable<BaseResponse<any, any>>}
Done

2024-12-12 11:59 UTC, dvCodeWorld approved these changes, later dismissed

2024-12-16 09:17 UTC, dilpreetsinghofficial requested changes

2024-12-16 09:17 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/home/home.store.ts
> +    isBankRefreshing: false,
```suggestion
    isBankRefreshing: false
```

2024-12-16 09:48 UTC, dilpreetsinghofficial submitted a review, later dismissed

2024-12-16 10:59 UTC, ravinderwalkover requested changes

2024-12-16 10:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/contact.service.ts
> +     public refreshBank(): Observable<BaseResponse<IBankRefreshResponse, any>> {
```suggestion
     public refreshGoCardlessBankTransactions(): Observable<BaseResponse<IBankRefreshResponse, any>> {
```

2024-12-16 10:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/apiurls/contact.api.ts
> +    BANKACCOUNTS_REFRESH: 'company/:companyUniqueName/gocardless/refresh'
```suggestion
    GOCARDLESS_BANKTRANSACTIONS_REFRESH: 'company/:companyUniqueName/gocardless/refresh'
```

2024-12-16 10:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/home/home.store.ts
> +    readonly refreshBank = this.effect((data: Observable<void>) => {
```suggestion
    readonly refreshGoCardlessBankTransactions = this.effect((data: Observable<void>) => {
```

2024-12-16 10:59 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/contact.service.ts
> +     * Refresh bank accounts
Update js doc also

2024-12-16 11:06 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/services/contact.service.ts
> +     public refreshBank(): Observable<BaseResponse<IBankRefreshResponse, any>> {
Done

2024-12-16 11:09 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/home/home.store.ts
> +    readonly refreshBank = this.effect((data: Observable<void>) => {
Done

2024-12-16 11:10 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/services/apiurls/contact.api.ts
> +    BANKACCOUNTS_REFRESH: 'company/:companyUniqueName/gocardless/refresh'
Done

2024-12-16 11:12 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/services/contact.service.ts
> +     * Refresh bank accounts
Done

2024-12-16 11:46 UTC, ravinderwalkover approved these changes

2024-12-16 11:47 UTC, merged