Shivani | Stage | Prod - Change subscription expiry message in case of auto renewal
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14329
Opened 2024-12-12 14:02 UTC by shivanivani02

https://app.clickup.com/t/86cx9rybp

2024-12-20 12:06 UTC, dvCodeWorld requested changes

2024-12-20 12:06 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        if (['MONTHLY', 'DAILY'].includes(this.subscribedPlan?.duration)) {
```suggestion
        if (['MONTHLY', 'DAILY'].includes(this.subscribedPlan?.duration) && !subscribedPlan?.isSubTrialOrCancelled) {
```

2024-12-20 12:06 UTC, dvCodeWorld commented on apps/web-giddh/src/assets/locale/header/en.json
> +    "subscription_expire_renewal_message": "The payment has been initiated. The subscription will be renewed upon successful payment processing.",
```suggestion
    "subscription_expire_renewal_message": "The payment has been initiated. Your subscription will be renewed upon successful payment processing.",
```

2024-12-20 13:44 UTC, dvCodeWorld requested changes

2024-12-20 13:44 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +    /** Hold the message of subscription plane get expire and remains day wise*/
```suggestion
    /** Holds true if plan is either trail or cancelled  */
```

2024-12-20 13:44 UTC, dvCodeWorld commented on apps/web-giddh/src/assets/locale/header/mr.json
> +    "subscription_expire_renewal_message": "पेमेंट सुरू करण्यात आले आहे. यशस्वी पेमेंट प्रक्रियेनंतर तुमचे सदस्यत्व नूतनीकरण केले जाईल.",
```suggestion
    "subscription_expire_renewal_message": "पेमेंट सुरू करण्यात आले आहे. यशस्वी पेमेंट प्रक्रियेनंतर तुमचे सदस्यत्व नूतनीकरण केले जाईल",
```

2024-12-30 06:45 UTC, dilpreetsinghofficial approved these changes

2024-12-30 10:39 UTC, dvCodeWorld approved these changes

2024-12-30 10:40 UTC, dilpreetsinghofficial approved these changes

2024-12-30 10:40 UTC, merged