Dilpreet | Stage | Prod Bugs
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14349
Opened 2024-12-18 11:13 UTC by dilpreetsinghofficial

https://app.clickup.com/t/86cx1xtwu
https://app.clickup.com/t/86cxbmye5

2024-12-18 12:36 UTC, dvCodeWorld requested changes

2024-12-18 12:36 UTC, dvCodeWorld commented on apps/web-giddh/src/app/contact/contact.component.ts
> +                    this.isIciciAccountPendingForApproval = false;
Check

2024-12-18 12:44 UTC, dvCodeWorld submitted a review, later dismissed

2024-12-18 13:05 UTC, dvCodeWorld submitted a review, later dismissed

2024-12-19 05:41 UTC, dvCodeWorld approved these changes

2024-12-19 05:48 UTC, ravinderwalkover approved these changes

2024-12-19 05:48 UTC, merged