Ankit | Stage | Prod - Email, role and date range fields are enable even when plan do not have permission
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14388
Opened 2024-12-25 04:26 UTC by ankitdubeyoffice

https://app.clickup.com/t/86cxdft90

2025-01-23 07:06 UTC, dilpreetsinghofficial requested changes

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
>                      [placeholder]="localeData?.role_name_placeholder" [options]="allRoles"
format code

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +    /** Holds true if user module is restricted */
```suggestion
    /** True if user module is restricted */
```

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +    /** Holds true if user module is restricted */
```suggestion
    /** True if user module is restricted */
```

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +            if (activeCompany && Object.hasOwn(activeCompany?.subscription?.planDetails?.restrictedModules, this.restrictedModules.Users) && activeCompany?.moduleRestrictionStatus) {
```suggestion
            if (activeCompany && Object.hasOwn(activeCompany.subscription?.planDetails?.restrictedModules, this.restrictedModules.Users) && activeCompany.moduleRestrictionStatus) {
```

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +            this.router.navigate(['/pages/user-details/subscription/buy-plan/' + subscriptionId]);
```suggestion
            this.router.navigate([ 'pages','user-details', 'subscription', 'buy-plan', + subscriptionId]);
```

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts
> +    /** Holds true if user module is restricted */
```suggestion
    /** True if user module is restricted */
```

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts
> +                if (Object.hasOwn(activeCompany?.subscription?.planDetails?.restrictedModules, this.restrictedModules.Users) && activeCompany?.moduleRestrictionStatus) {
```suggestion
                if (Object.hasOwn(activeCompany.subscription?.planDetails?.restrictedModules, this.restrictedModules.Users) && activeCompany.moduleRestrictionStatus) {
```

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts
> +            this.router.navigate(['/pages/user-details/subscription/buy-plan/' + subscriptionId]);
this.router.navigate([ 'pages','user-details', 'subscription', 'buy-plan', + subscriptionId]);

2025-01-23 07:06 UTC, dilpreetsinghofficial commented on apps/web-giddh/src/app/shared/subscription-upgrade-button/subscription-upgrade-button.component.ts
> +    /** Holds true if user module is restricted */
```suggestion
    /** True if user module is restricted */
```

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
>                      [placeholder]="localeData?.role_name_placeholder" [options]="allRoles"
Done

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +    /** Holds true if user module is restricted */
Done

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +    /** Holds true if user module is restricted */
Done

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +            if (activeCompany && Object.hasOwn(activeCompany?.subscription?.planDetails?.restrictedModules, this.restrictedModules.Users) && activeCompany?.moduleRestrictionStatus) {
Done

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +            this.router.navigate(['/pages/user-details/subscription/buy-plan/' + subscriptionId]);
Done

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts
> +    /** Holds true if user module is restricted */
Done

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts
> +                if (Object.hasOwn(activeCompany?.subscription?.planDetails?.restrictedModules, this.restrictedModules.Users) && activeCompany?.moduleRestrictionStatus) {
Done

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts
> +            this.router.navigate(['/pages/user-details/subscription/buy-plan/' + subscriptionId]);
**Done**

2025-01-23 13:57 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/subscription-upgrade-button/subscription-upgrade-button.component.ts
> +    /** Holds true if user module is restricted */
Done

2025-01-24 11:06 UTC, dilpreetsinghofficial approved these changes

2025-01-24 11:06 UTC, merged