Ankit | Test | Prod - Email, role and date range fields are enable even when plan do not have permission
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #14389
Opened 2024-12-25 05:15 UTC by ankitdubeyoffice

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2024-12-26 10:59 UTC, dvCodeWorld requested changes

2024-12-26 10:59 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +                this.isUserRestricted = !(module?.remainingUsers ?? false);
```suggestion
                this.isUserRestricted = !module?.remainingUsers;
```

2024-12-26 10:59 UTC, dvCodeWorld commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
> +                            permissionForm.invalid || isUserRestricted
```suggestion
                            permissionForm?.invalid || isUserRestricted
```

2024-12-26 10:59 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +            if (activeCompany) {
optmise

2024-12-26 10:59 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +                    let module = activeCompany.moduleRestrictionStatus.find(
```suggestion
                    const module: any = activeCompany.moduleRestrictionStatus.find(
```

2024-12-26 11:49 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/settings/permissions/form/form.component.ts
> +                this.isUserRestricted = !(module?.remainingUsers ?? false);
done

2024-12-26 11:49 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/settings/permissions/form/form.component.html
> +                            permissionForm.invalid || isUserRestricted
Done

2024-12-26 11:50 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +                    let module = activeCompany.moduleRestrictionStatus.find(
Done

2024-12-30 14:02 UTC, dvCodeWorld requested changes

2024-12-30 14:02 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +    public restrictedModules: any = RestrictedModules;
```suggestion
    public restrictedModules: RestrictedModules = RestrictedModules;
```

2024-12-30 14:02 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +    /** Holds user module restriction */
```suggestion
    /** Holds true if user module is restricted */
```

2024-12-30 14:02 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts
>      /** Holds user module restriction */
check

2024-12-30 14:02 UTC, dvCodeWorld commented on apps/web-giddh/src/app/shared/subscription-upgrade-button/subscription-upgrade-button.component.ts
> +    public restrictedModules: any = RestrictedModules;
```suggestion
    public restrictedModules: RestrictedModules = RestrictedModules;
```

2024-12-31 08:50 UTC, ankitdubeyoffice commented on apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
> +    public restrictedModules: any = RestrictedModules;
Type 'typeof RestrictedModules' is not assignable to type 'RestrictedModules'.

2025-01-01 05:34 UTC, dvCodeWorld approved these changes

2025-01-01 05:35 UTC, merged