Gidk 1135 prod
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #5606
Opened 2020-08-29 08:57 UTC by shalinee-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-08-29 09:42 UTC, prateek-giddh requested changes
There are multiple elements with same ID. For eg: giddh-datepicker is used twice in same HTML, please have a look

2020-08-31 12:17 UTC, aditi-tiwari17 approved these changes

2020-08-31 13:23 UTC, ravinderwalkover requested changes

2020-08-31 13:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> +                                    <td data-title="Particular" id="{{'dabit-id-' + i}}"
correct Debit spelling everywhere

2020-08-31 13:27 UTC, shalinee-walkover commented on apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> +                                    <td data-title="Particular" id="{{'dabit-id-' + i}}"
Done

2020-08-31 13:28 UTC, ravinderwalkover approved these changes

2020-08-31 14:37 UTC, prateek-giddh approved these changes

2020-09-01 12:38 UTC, merged