Gidk 1135 ledger id new
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #5607
Opened 2020-08-29 11:04 UTC by shalinee-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-08-29 11:21 UTC, ravinderwalkover requested changes

2020-08-29 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
> +                                    <sh-select id="ledger-vouchar-type" #sh [options]="voucherTypeList | async" [isFilterEnabled]="true"
correct voucher spelling

2020-08-29 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
> +                                    <sh-select id="ledger-vouchar-number" [options]="invoiceList" #invoice placeholder="Select Invoice"
correct voucher spelling

2020-08-29 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> +                                        <input id="update-ledger-adjust-vouchar" type="text" class="form-control mb-1" [(ngModel)]="item.voucherNumber" disabled>
update voucher spelling

2020-08-29 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> +                                        <input type="text" id="update-ledger-vouchar-tax" class="form-control mb-1" decimalDigitsDirective [mask]="vm.inputMaskFormat" [prefix]="vm.selectedPrefixForCu
update voucher spelling

2020-08-29 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> +                                        <sh-select id="update-ledger-vouchar-type" [options]="vm.voucherTypeList" [isFilterEnabled]="true"
update voucher spelling

2020-08-29 11:21 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> +                                        <input id="update-ledger-vouchar-number" type="text" placeholder="Voucher no." class="form-control"
update voucher spelling

2020-08-29 11:39 UTC, shalinee-walkover commented on apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
> +                                    <sh-select id="ledger-vouchar-number" [options]="invoiceList" #invoice placeholder="Select Invoice"
Done, updated all voucher spell

2020-08-31 12:31 UTC, rohit-walkover approved these changes

2020-08-31 13:28 UTC, shalinee-walkover commented on apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> +                                        <input id="update-ledger-vouchar-number" type="text" placeholder="Voucher no." class="form-control"
All spell corrections done

2020-08-31 13:28 UTC, ravinderwalkover approved these changes

2020-08-31 14:37 UTC, prateek-giddh approved these changes

2020-09-01 04:05 UTC, merged