Ravinder | Development | Purchase Order v 1.2
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #5650
Opened 2020-09-10 08:10 UTC by ravinderwalkover

Ravinder | Development | Purchase Order v 1.2

2020-09-10 12:29 UTC, prateek-giddh requested changes

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
> +        if (loop < (this.purchaseOrders.length - 1)) {
Consider using just
```suggestion
        return (loop < (this.purchaseOrders.length - 1));
```

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
> +    background-color: #5b64c9;
Use color variables

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
> +            if (this.bulkUpdateGetParams.action === 'purchasedate') {
Consider adding these actions to an enum

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.html
> +<div _ngcontent-xlm-c43="" class="invoce-controll">
Incorrect spelling of control

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.ts
> +    private destroyed$: ReplaySubject<boolean> = new ReplaySubject(1);
Do add ngOnDestroy and emit this Subject

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.ts
> +    public onTabChanged(tabName: string): void {
Missing JS doc

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/services/purchase-order.service.ts
> +    public getPdf(getRequestObject: any): any {
Avoid incorrect return type:
```suggestion
    public getPdf(getRequestObject: any): Observable<BaseResponse<any, any>> {
```

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/services/purchase-record.service.ts
> +    public getPdf(requestObject: any): any {
Avoid incorrect return type in JS doc
```suggestion
    public getPdf(requestObject: any): Observable<BaseResponse<any, any>> {
```

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/purchase-order-preview/purchase-order-preview.component.scss
> +    background-color: #5b64c9;
Use color variables

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/assets/css/style-2.scss
> +.invoce-controll .nav > li > a:hover{
Avoid incorrect spelling `invoice-control`

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +    public openModal(template: TemplateRef<any>): void {
Missing JS doc

2020-09-10 12:29 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +    @Input() public refreshPurchaseBill: boolean = false;
Missing JS doc

2020-09-11 05:47 UTC, aditi-tiwari17 approved these changes

2020-09-11 06:09 UTC, prateek-giddh approved these changes

2020-09-11 13:11 UTC, merged