Gidk 1153 d | Rohit | create all module dynamic
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #5652
Opened 2020-09-10 14:21 UTC by rohit-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-09-10 14:23 UTC, ravinderwalkover requested changes

2020-09-10 14:23 UTC, ravinderwalkover commented on apps/web-giddh/src/app/all-modules/all-modules.component.ts
> +    public navigateTo(route: any, queryParamsItem: any, isClickMethod: any) {
add return type

2020-09-10 14:30 UTC, ravinderwalkover approved these changes

2020-09-11 05:42 UTC, shalinee-walkover approved these changes
Approve

2020-09-11 05:58 UTC, prateek-giddh approved these changes

2020-09-11 06:38 UTC, merged