Rohit | Daybook ng-10 issue resolved
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #5775
Opened 2020-09-28 12:46 UTC by rohit-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-09-28 12:54 UTC, prateek-giddh approved these changes

2020-09-28 12:58 UTC, ravinderwalkover requested changes

2020-09-28 12:58 UTC, ravinderwalkover commented on apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
> +        this.initializeDaybookAdvanceSearchForm()
add semicolon

2020-09-28 12:58 UTC, ravinderwalkover commented on apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
> +    public initializeDaybookAdvanceSearchForm() {
add return type

2020-09-28 13:17 UTC, ravinderwalkover approved these changes

2020-09-29 13:53 UTC, ravinderwalkover approved these changes

2020-09-29 13:55 UTC, prateek-giddh approved these changes

2020-09-29 13:56 UTC, merged