Architecture v1 to TEST
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #5942
Opened 2020-10-16 09:52 UTC by prateek-giddh

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-10-16 10:58 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
> +        </div> -->
@prateek-giddh Where is this code written? I couldn't find remove logo button and text

2020-10-16 11:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
> +                            <div class="row">
ignore for now this will cover for V2

2020-10-16 11:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
> +        <!-- <div class="col-md-12 mt-15">
Cover on V2

2020-10-16 11:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
> +                            <span><img src="../../../assets/images/flags.png"> India - INR Rupee</span>
make image src dynamic

2020-10-16 11:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
> +                    <img src="../../../assets/images/warehouse-image.svg" alt="warehouse image">
make image src dynamic @prateek-giddh

2020-10-16 11:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
> +                    <img class="branch-image" *ngIf="isBranchElemnt" src="../../../assets/images/branch-image.svg" alt="Brnach image">
make image src dynamic @prateek-giddh

2020-10-17 10:19 UTC, ravinderwalkover requested changes

2020-10-17 10:19 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
> +    border: 1px dashed gainsboro;
use color var

2020-10-17 10:19 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
> +                this.store.dispatch(this.commonActions.GetCurrency());
Looks like we removed this and it's being readded. Please verify

2020-10-17 10:19 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
> +            this.store.dispatch(this.companyActions.userStoreCreateBranch(null));
duplicate code

2020-10-17 10:19 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +                    type: SETTINGS_PROFILE_ACTIONS.GET_PROFILE_RESPONSE,
Please create a function for this in action and call here.

2020-10-17 10:19 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        this.setOrganziationDetails(OrganizationType.Company, details);
Fix spelling of organization

2020-10-17 10:19 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +    private setOrganziationDetails(type: OrganizationType, branchDetails: OrganizationDetails): void {
fix organization spelling

2020-10-17 10:19 UTC, ravinderwalkover commented on apps/web-giddh/src/app/welcome/welcome.component.ts
> +            this.store.dispatch(this.companyActions.userStoreCreateBranch(null));
duplicate code

2020-10-19 06:34 UTC, ravinderwalkover requested changes

2020-10-19 06:34 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/http.interceptor.ts
>      private addBranchUnqiueName(request: HttpRequest<any>): HttpRequest<any> {
Fix spelling of unique

2020-10-19 06:47 UTC, ravinderwalkover requested changes

2020-10-19 06:47 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
>      ngOnInit(): void {
add public

2020-10-19 06:47 UTC, ravinderwalkover commented on apps/web-giddh/src/app/settings/personal-information/personal-information.component.ts
>      ngOnInit(): void {
add public

2020-10-19 06:53 UTC, ravinderwalkover approved these changes

2020-10-22 12:13 UTC, merged