Merging Stage to Production
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #5943
Opened 2020-10-16 10:15 UTC by ravinderwalkover

Merging Stage to Production

2020-10-16 14:42 UTC, prateek-giddh requested changes

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +                    window.location.href = (environment.production) ? `https://beta.giddh.com/login/?action=logout` : `https://test.giddh.com/login/?action=logout`;
Change it back to giddh.com

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
> +                updateStockIteminGroupArray(groupArray,activeGroupUniqueName, updateStockResp);
Incorrect camelCase name
```suggestion
                updateStockItemInGroupArray(groupArray,activeGroupUniqueName, updateStockResp);
```

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
> +     .form-inline.financial-selectYear{
```suggestion
     .form-inline.financial-select-year{
```

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
> +    private onChangeCallback: (_: any) => void = noop;
Missing JS doc

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/environments/environment.prod.ts
> +    AppUrl: 'https://beta.giddh.com',
Please revert this

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/environments/environment.stage.ts
> +    ApiUrl: 'https://api.giddh.com/',
Should be apirelease

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/environments/environment.stage.cordova.ts
> +    ApiUrl: 'https://api.giddh.com/',
Should be apirelease

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/environments/environment.ts
> +    AppUrl: 'https://beta.giddh.com/',
Please revert this

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/meta/success.html
> +        <p>All right are reserved &copy; 2020 Walkover <a href="https://beta.giddh.com/" target="_Blank">Giddh.com</a>
Please revert this

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/meta/yodlee-success.html
> +        <p>All right are reserved &copy; 2020 Walkover <a href="https://beta.giddh.com/" target="_Blank">Giddh.com</a>
Please revert this

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/meta/yodlee-success.html
> +                apiBaseUrl = 'https://api.giddh.com/';
apirelease

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/meta/yodlee-success.html
> +                apiBaseUrl = 'https://api.giddh.com/';
apidev

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/src/meta/yodlee-success.html
> +                apiBaseUrl = 'https://api.giddh.com/';
apitest

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/webpack.cordova.local.partial.js
> +            'ApiUrl': JSON.stringify('https://apirelease.giddh.com/'),
apidev

2020-10-16 14:42 UTC, prateek-giddh commented on apps/web-giddh/webpack.local.partial.js
> +            'ApiUrl': JSON.stringify('https://apirelease.giddh.com/'),
apidev

2020-10-16 14:48 UTC, ravindersinghdang commented on apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
> +    private onChangeCallback: (_: any) => void = noop;
Prateek, Doc is already added.

2020-10-17 03:43 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
> +.total-amt{
Yes, this is done in code improvement. Will raise PR for this after a couple of days.

2020-10-29 13:16 UTC, shalinee-walkover commented on apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
> +     .form-inline.financial-selectYear{
Done

2020-10-29 13:16 UTC, shalinee-walkover commented on apps/web-giddh/src/app/gst/gst.component.scss
> +    color: #fff!important;
Done

2020-10-29 13:16 UTC, shalinee-walkover commented on apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
> +            <form class="mr-b2" name="manufaturingForm" #manufaturingForm="ngForm">
Done

2020-10-29 13:16 UTC, shalinee-walkover commented on apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> +                    <div class="form-group mrR1 max500  d-initial flex-column" *ngIf="selectedType==='quater'">
this is appearing in many places, I can't take the risk for it

2020-10-29 13:16 UTC, shalinee-walkover commented on apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> +                    <div class="row mTB1" *ngIf="isMobileScreen">
updated

2020-10-29 13:16 UTC, shalinee-walkover commented on apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
> +    background: #fff;
Done

2020-10-29 13:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
> +    background-color: #5b64c9;
Done

2020-10-29 13:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
> +.cash-invoice-tip-Img.search-arrow-image {
Done

2020-10-29 13:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/settings/permissions/form/form.component.scss
> +    .permissionForm {
Done

2020-10-29 13:17 UTC, shalinee-walkover commented on apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
> +    <div class="mb-2 selectBox">
Done

2020-10-29 13:29 UTC, aditi-tiwari17 approved these changes

2020-10-29 13:54 UTC, shalinee-walkover approved these changes
Approve

2020-10-29 14:01 UTC, prateek-giddh approved these changes

2020-10-29 14:21 UTC, rohit-walkover approved these changes

2020-10-31 14:01 UTC, merged