Merge stage beta
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #6167
Opened 2020-11-05 12:07 UTC by prateek-giddh

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-11-05 12:31 UTC, ravinderwalkover requested changes

2020-11-05 12:31 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
> +        <tab heading="Generated Bills" id="tab1">
Please update this in language JSON.

2020-11-05 12:31 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/authentication.service.ts
> +            // let data: BaseResponse<VerifyEmailResponseModel, LinkedInRequestModel> = res as BaseResponse<any, any>;
remove commented code.

2020-11-05 12:31 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +                    window.location.href = (environment.production) ? `https://beta.giddh.com/login/?action=logout` : `https://test.giddh.com/login/?action=logout`;
Please revert the url

2020-11-05 12:47 UTC, aditi-tiwari17 approved these changes

2020-11-05 12:48 UTC, shalinee-walkover approved these changes
Approve

2020-11-05 14:33 UTC, rohit-walkover approved these changes

2020-11-06 07:17 UTC, ravinderwalkover approved these changes

2020-11-06 07:17 UTC, ravinderwalkover approved these changes

2020-11-06 07:31 UTC, merged