Merge beta-stage to beta-branch
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #6168
Opened 2020-11-05 12:26 UTC by prateek-giddh

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-11-06 06:14 UTC, ravinderwalkover approved these changes

2020-11-06 06:16 UTC, shalinee-walkover approved these changes
Approve

2020-12-15 05:22 UTC, ravinderwalkover requested changes

2020-12-15 05:22 UTC, ravinderwalkover commented on apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
> +                        <div class="custom-datepicker" (click)="showGiddhDatepicker($event)">
This story of new datepicker is still under testing, it shouldn't be merged

2020-12-16 09:28 UTC, aditi-tiwari17 approved these changes

2020-12-16 12:05 UTC, ravinderwalkover requested changes

2020-12-16 12:57 UTC, prateek-giddh commented on apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts
> +        this.universalDate$ = this._store.pipe(select(sessionStore => sessionStore.session.applicationDate), distinctUntilChanged(), takeUntil(this.destroyed$));
This is formatted but not visible in GIthub diff view

2020-12-16 13:01 UTC, prateek-giddh commented on apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
> +		this.fromDate = this.startDate;
This is formatted but not visible in GIthub diff view

2020-12-16 13:01 UTC, prateek-giddh commented on apps/web-giddh/src/app/inventory/components/aside-branch-transfer-pane/aside-branch-transfer-pane.component.ts
> +        this._store.pipe(select(p => p.inventoryInOutState.entryInProcess), takeUntil(this.destroyed$)).subscribe(p => this.isLoading = p);
This is formatted but not visible in GIthub diff view

2020-12-16 13:58 UTC, prateek-giddh commented on apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
> +				let accountList = this.flattenGroup(response.body, []);
This is formatted but not visible in GIthub diff view

2020-12-16 13:58 UTC, prateek-giddh commented on apps/web-giddh/src/app/services/import-excel.service.ts
> +        if (model.branchUniqueName) {
Done

2020-12-16 13:58 UTC, prateek-giddh commented on apps/web-giddh/src/app/settings/other-settings/other-settings.component.scss
> +    }
Done

2020-12-16 13:58 UTC, prateek-giddh commented on apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
> +        document.querySelector('body').classList.remove('fixed');
Done

2020-12-16 13:58 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        this.generalService.isMobileSite.subscribe(s => {
Done

2020-12-16 13:58 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +                    window.location.href = (environment.production) ? `https://stage.giddh.com/login/?action=logout` : `https://test.giddh.com/login/?action=logout`;
Done

2020-12-16 13:59 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +        this.location.back();
Done

2020-12-16 13:59 UTC, prateek-giddh commented on apps/web-giddh/src/app/tb-pl-bs/components/export/tb-export-csv.component.ts
> +		this.destroyed$.next(true);
This is formatted but not visible in GIthub diff view

2020-12-16 15:42 UTC, ravinderwalkover approved these changes

2020-12-24 16:06 UTC, merged