Gidk 1b74u6 intercom test
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #6193
Opened 2020-11-06 13:32 UTC by shalinee-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-11-06 13:35 UTC, prateek-giddh requested changes

2020-11-06 13:35 UTC, prateek-giddh commented on apps/web-giddh/src/app/ledger/ledger.component.ts
> +        $('.modal-backdrop').addClass('update-ledger-overlay');
Avoid use of jQuery

2020-11-06 13:37 UTC, ravinderwalkover approved these changes

2020-11-07 04:37 UTC, shalinee-walkover commented on apps/web-giddh/src/app/ledger/ledger.component.ts
> +        $('.modal-backdrop').addClass('update-ledger-overlay');
Done

2020-11-07 04:59 UTC, prateek-giddh approved these changes

2020-11-07 05:02 UTC, merged