setup company store and used in some modules
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #6382
Opened 2020-11-20 05:43 UTC by ravinderwalkover

setup company store and used in some modules

2020-11-26 05:03 UTC, prateek-giddh requested changes

2020-11-26 07:44 UTC, ravinderwalkover commented on apps/web-giddh/src/app/home/home.component.ts
> -                if (this.activeFinancialYear) {
yes, it wasn't getting used.

2020-11-26 07:45 UTC, prateek-giddh approved these changes

2020-11-26 13:15 UTC, rohit-walkover approved these changes

2020-11-27 06:42 UTC, prateek-giddh approved these changes

2020-11-27 07:08 UTC, merged