TCS/TDS tax and discount issues resolved
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #6400
Opened 2020-11-21 14:50 UTC by rohit-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-11-21 14:54 UTC, prateek-giddh approved these changes

2020-11-25 06:09 UTC, ravinderwalkover requested changes

2020-11-25 06:09 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.ts
> +            this.discountAccountsDetails[0].isActive = false;
This will break if this.discountAccountsDetails is null

2020-11-25 06:09 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
> +            this.currentTxn.discounts[0].isActive = false;
This will break if this.currentTxn.discounts is null

2020-11-25 06:37 UTC, ravinderwalkover approved these changes

2020-11-25 06:41 UTC, merged