TCS TDS and Discount issues resolved
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #6484
Opened 2020-12-01 06:41 UTC by rohit-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-12-01 07:05 UTC, prateek-giddh requested changes

2020-12-01 07:05 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/header/header.component.ts
> +    public getAllMenusModules() {
Do add return type

2020-12-01 07:10 UTC, prateek-giddh approved these changes

2020-12-14 05:32 UTC, ravinderwalkover requested changes

2020-12-14 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
> +    public calculateDiscount(event: any) {
add return type

2020-12-14 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
> +    public preparePreAppliedDiscounts() {
add return type

2020-12-14 06:05 UTC, ravinderwalkover approved these changes

2020-12-14 13:55 UTC, merged