feat: Prateek | Test | Architecture-v2 to Test env.
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #6517
Opened 2020-12-03 11:42 UTC by prateek-giddh

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-12-03 12:09 UTC, shalinee-walkover commented on apps/web-giddh/src/app/import-excel/import-report/import-report.component.html
> +                            <div class="col-xs-3 col-sm-3">
update **col-xs-3** to **col-3**

2020-12-03 12:09 UTC, shalinee-walkover commented on apps/web-giddh/src/app/import-excel/import-report/import-report.component.html
> +                            <div class="col-xs-9 col-sm-9">{{ item?.branch?.name || '-' }}</div>
update **col-xs-9** to **col-9**

2020-12-03 12:37 UTC, aditi-tiwari17 approved these changes

2020-12-03 12:38 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
> +                                                <div class="item-unq giddh-limit single-line-clamp">
Please change this class name to -  item-unique @prateek-giddh

2020-12-03 12:39 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.scss
>      color: #cccccc;
Please give color var to this class @prateek-giddh

2020-12-03 14:04 UTC, ravinderwalkover requested changes

2020-12-03 14:04 UTC, ravinderwalkover commented on apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
> +        this.store.pipe(
```suggestion
        this.store.pipe(select(state => state.company && state.company.activeCompany), takeUntil(this.destroyed$)).subscribe(activeCompany => {
            if(activeCompany) {
                this. activeCompany = activeCompany;
            }
        });
```

2020-12-05 07:51 UTC, ravinderwalkover approved these changes

2020-12-05 09:15 UTC, shalinee-walkover approved these changes

2020-12-05 09:16 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
> +                                        <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:16 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/contact/contact.component.html
> +                                                    <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:17 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/daybook/daybook.component.html
> +                                        <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:17 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
> +                                    <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:18 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
> +                                        <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:19 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/ledger/ledger.component.html
> +                                            <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:19 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
> +                                            <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:20 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
> +                                            <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:20 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
> +                                <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:21 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
> +                                <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:21 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
> +                                        <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:21 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
> +                                                <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:24 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
> +                                                <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:26 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/vat-report/vatReport.component.html
> +                                                                    <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-05 09:27 UTC, aditi-tiwari17 commented on apps/web-giddh/src/app/ledger/ledger.component.html
> +                                                <div class="item-unq giddh-limit single-line-clamp">
change class name - item-unq to item-unique

2020-12-14 06:02 UTC, ravinderwalkover approved these changes

2020-12-15 13:43 UTC, merged