new datepicker implemented on reverse charge report and advance recei…
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #6623
Opened 2020-12-10 13:54 UTC by rohit-walkover

…pt report

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-12-10 13:57 UTC, prateek-giddh approved these changes

2020-12-11 06:00 UTC, ravinderwalkover requested changes

2020-12-11 06:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
> +                this.selectedDateRange = { startDate: moment(applicationDate[0]), endDate: moment(applicationDate[1]) };
use universalDate var here also

2020-12-11 06:00 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
> +                this.selectedDateRange = { startDate: moment(dateObj[0]), endDate: moment(dateObj[1]) };
use universalDate var here also

2020-12-11 07:40 UTC, ravinderwalkover approved these changes

2020-12-11 07:55 UTC, merged