Giddh multilanguage
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #7184
Opened 2021-01-28 12:22 UTC by ravinderwalkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-02-16 13:07 UTC, prateek-giddh requested changes

2021-02-18 07:04 UTC, ravinderwalkover commented on apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.ts
> +import { Component, OnDestroy, OnInit, Input } from '@angular/core';
Done

2021-02-18 07:26 UTC, ravinderwalkover commented on apps/web-giddh/src/app/import-excel/upload-success/upload-success.component.ts
> +                this.importedCountMessage = this.localeData.imported_count_message;
Done

2021-02-18 07:30 UTC, ravinderwalkover commented on apps/web-giddh/src/app/import-excel/upload-success/upload-success.component.ts
> +                this.failedReportMessage = this.localeData.failed_report_message;
Done

2021-02-18 07:34 UTC, ravinderwalkover commented on apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.ts
> +    public bifurcationClients: string = "";
Done

2021-02-18 07:35 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/confirmation/confirmation.model.component.ts
> +    public confirmationMessage: string = "";
Done

2021-02-18 07:35 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/confirmation/confirmation.model.component.ts
> +    public ngOnInit(): void {
Done

2021-02-18 07:37 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
> +    public groupSharedWith: string = "";
Done

2021-02-18 07:37 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
> +                this.groupSharedWith = this.localeData.shared_with;
Done

2021-02-18 07:37 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
> +                this.accountSharedWith = this.localeData.shared_with;
Done

2021-02-18 07:38 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
> +        this.deleteMergedAccountModalBody = this.localeData.delete_merged_account_content;
Done

2021-02-18 07:38 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
> +        this.moveMergedAccountModalBody = this.localeData.move_merged_account_content;
Done

2021-02-18 07:40 UTC, ravinderwalkover commented on apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
> +    @Input() public localeData: any = {};
Done

2021-02-18 09:52 UTC, prateek-giddh approved these changes

2021-02-18 10:08 UTC, merged