Beta - Implement multi-language in giddh
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #7611
Opened 2021-03-13 05:10 UTC by ravinderwalkover

https://app.clickup.com/t/1h82ed

2021-03-13 11:49 UTC, prateek-giddh requested changes

2021-03-13 11:49 UTC, prateek-giddh commented on apps/web-giddh/src/app/ledger/ledger.component.html
> +                                                            <tr class="ledger-row row" (mouseenter)="txn.showDropdown = true;" (mouseleave)="txn.showDropdown = false;" [ngClass]="{'compoundEntry': tx
Please check this class name change

2021-03-13 11:49 UTC, prateek-giddh commented on apps/web-giddh/src/app/permissions/components/list/permission-list.html
> +                    <div class="text-center mr-t2 onHover">
Please check this class name change

2021-03-13 11:49 UTC, prateek-giddh commented on apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
> +                            <th *ngIf="showFieldFilter.voucherNo" class="td-search-box nowrap" style="width: 210px;"
Please check this class name change

2021-03-13 11:49 UTC, prateek-giddh commented on apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
> -    <div class="no-data mr-t2 loader-main" *ngIf="showLoader">
Please check this change

2021-03-13 11:49 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
> +//     public taxPopOverTemplate: string = `
Please check this change

2021-03-13 11:49 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
> +    <div class="">
Please revert this class change

2021-03-13 11:49 UTC, prateek-giddh commented on apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
> +                            <div class="custom-datepicker" (click)="showGiddhDatepicker($event)">
Please check this class name change

2021-03-13 11:49 UTC, prateek-giddh commented on apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
> -                            <input type="text" name="selectedDateRange" [value]="(selectedDateRangeUi) ? selectedDateRangeUi : ''" class="giddh-datepicker date-range-picker border-radius-2" />
Please check this class name change

2021-03-13 14:03 UTC, ravinderwalkover commented on apps/web-giddh/src/app/audit-logs/audit-logs.component.html
> -                <div class="custom-datepicker" (click)="showGiddhDatepicker($event)" *ngIf="isNewVersion">
It's not getting removed.

2021-03-13 14:07 UTC, ravinderwalkover commented on apps/web-giddh/src/app/home/components/ratio-analysis/ratio-analysis-chart.component.html
> +                <div class="no-data mr-t2 loader-main">
yes it's fine

2021-03-13 14:08 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/ledger.component.html
> +                                                            <tr class="ledger-row row" (mouseenter)="txn.showDropdown = true;" (mouseleave)="txn.showDropdown = false;" [ngClass]="{'compoundEntry': tx
done

2021-03-13 14:09 UTC, ravinderwalkover commented on apps/web-giddh/src/app/permissions/components/list/permission-list.html
> +                    <div class="text-center mr-t2 onHover">
Done

2021-03-13 14:10 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
> +                            <th *ngIf="showFieldFilter.voucherNo" class="td-search-box nowrap" style="width: 210px;"
Done

2021-03-13 14:12 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
> -    <div class="no-data mr-t2 loader-main" *ngIf="showLoader">
yes its fine

2021-03-13 14:13 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
> +//     public taxPopOverTemplate: string = `
it wasn't getting used to commented it.

2021-03-13 14:15 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
> +    <div class="">
which change?

2021-03-15 04:15 UTC, prateek-giddh approved these changes

2021-03-15 12:13 UTC, merged