Merging Prod to Beta
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #7713
Opened 2021-03-19 14:30 UTC by ravinderwalkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-03-20 04:07 UTC, prateek-giddh requested changes

2021-03-20 04:07 UTC, prateek-giddh commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
> +<<<<<<< HEAD
Please check this unresolved merge conflict

2021-03-20 04:07 UTC, prateek-giddh commented on apps/web-giddh/src/assets/magic-link-assets/magic.css
> +<<<<<<< HEAD
Please check this unresolved merge conflict

2021-03-22 04:57 UTC, prateek-giddh approved these changes

2021-03-22 06:24 UTC, shalinee-walkover approved these changes

2021-03-22 06:32 UTC, merged