Gidk 2k9fpj gst prod
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #7845
Opened 2021-04-13 04:21 UTC by shalinee-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-05-07 10:10 UTC, aditi-tiwari17 approved these changes

2021-05-07 10:16 UTC, ravinderwalkover requested changes

2021-05-07 10:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/filing/filing.component.ts
> +    public navigateToOverview(type) {
return type

2021-05-07 10:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/filing/filing.component.ts
> +    public navigateTogstR3B(type) {
param and return type missing

2021-05-07 10:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.scss
> +                                    color: grey;
use color code

2021-05-07 10:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.ts
> +    public navigate(type) {
param and return type missing

2021-05-07 10:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/gstR1/gstR1.component.html
> +<div class="help-support-aside setting-sidebar-wrapper" *ngIf="asideGstSidebarMenuState === 'in'">
what's the use of blank div?

2021-05-07 10:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/gstR1/gstR1.component.ts
> +    public ngOnDestroy(){
return type

2021-05-07 10:16 UTC, ravinderwalkover commented on apps/web-giddh/src/app/gst/gstR2/gstR2.component.ts
> +    public ngOnDestroy(){
return type

2021-05-07 10:19 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/gstR1/gstR1.component.html
> +<div class="help-support-aside setting-sidebar-wrapper" *ngIf="asideGstSidebarMenuState === 'in'">
For backdrop of sidemenu

2021-05-26 11:01 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/filing/filing.component.ts
> +    public navigateToOverview(type) {
Done

2021-05-26 11:02 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/filing/filing.component.ts
> +    public navigateTogstR3B(type) {
Done

2021-05-26 11:03 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.scss
> +                                    color: grey;
Done

2021-05-26 11:05 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.ts
> +    public navigate(type) {
Done

2021-05-26 11:05 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/gstR1/gstR1.component.ts
> +    public ngOnDestroy(){
Done

2021-05-26 11:06 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/gstR2/gstR2.component.ts
> +    public ngOnDestroy(){
Done

2021-05-26 11:18 UTC, ravinderwalkover approved these changes

2021-05-27 11:27 UTC, merged