Gidk 31a6kh updatesidebr stage
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8060
Opened 2021-05-08 08:13 UTC by shalinee-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-05-08 08:49 UTC, ravinderwalkover requested changes

2021-05-08 08:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/daybook/daybook.component.ts
> +    public initialApiCalled: boolean = false;
this code shouldn't go to stage

2021-05-08 08:49 UTC, ravinderwalkover commented on apps/web-giddh/src/app/daybook/daybook.component.ts
> +                if (!this.initialApiCalled) {
this code shouldn't go to stage

2021-05-08 09:31 UTC, ravinderwalkover approved these changes

2021-05-11 06:19 UTC, shalinee-walkover commented
https://app.clickup.com/t/31a6kh

2021-05-11 06:21 UTC, prateek-giddh approved these changes

2021-05-12 04:18 UTC, merged