stage | GIDK-2bf9u7 | Aditi | total before discount website cherry-pick
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8129
Opened 2021-05-15 09:46 UTC by aditi-tiwari17

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-08-06 05:07 UTC, prateek-giddh requested changes

2021-08-06 05:07 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
> +                if (this.columnsVisibled && this.voucherType === 'sales') {
Do format this block

2021-08-06 05:07 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
> +
Avoid empty lines

2021-08-06 08:33 UTC, ravinderwalkover approved these changes

2021-08-09 08:51 UTC, prateek-giddh approved these changes

2021-08-09 08:58 UTC, merged