feat: Gidk-#2hgfrf | Prateek | Stage | Multi-currency support in Voucher adjustment (Ledger, voucher module, invoice preview)
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8161
Opened 2021-05-18 07:25 UTC by prateek-giddh

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
https://app.clickup.com/t/2hgfrf

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-05-18 07:25 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +            // let text = this.localeData?.currency_conversion;
WIll uncomment after multi-lingual v2 changes are deployed on STAGE

2021-06-30 16:13 UTC, prateek-giddh commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
> +                                            <span *ngIf="isSalesInvoice && isMulticurrencyAccount && adjustPaymentBalanceDueData === 0 && invFormData.voucherDetails.balanceDue === 0" class="balance-d
Delete this

2021-07-01 09:58 UTC, prateek-giddh commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
> +                                            <span *ngIf="isSalesInvoice && isMulticurrencyAccount && adjustPaymentBalanceDueData === 0 && invFormData.voucherDetails.balanceDue === 0" class="balance-d
Delete this

2021-07-02 08:17 UTC, ravinderwalkover requested changes

2021-07-02 08:17 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/invoice/en.json
> +    "e_invoice_statuses": {
duplicate key added

2021-07-02 08:17 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/locale/invoice/en.json
> +    "create_e_invoice": "Create E-invoice",
duplicate key added

2021-07-02 09:14 UTC, ravinderwalkover approved these changes

2021-07-02 09:15 UTC, merged