stage | GIDK-3bj75g | Aditi | env difference fixed
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8303
Opened 2021-05-29 14:28 UTC by aditi-tiwari17

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-06-08 10:19 UTC, prateek-giddh requested changes

2021-06-08 10:19 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts
> +    styleUrls: ['view-transactions.component.scss'],
Please change to `./view-transactions.component.scss`

2021-06-08 10:19 UTC, prateek-giddh commented on apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.ts
> +	styleUrls: ['reconcilation.component.scss'],
Please change to `./reconcilation.component.scss`

2021-06-08 10:19 UTC, prateek-giddh commented on apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
> +.p-0 {
Please check if this style is now required as we have global style for `padding: 0`

2021-06-08 10:19 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/header/header.component.scss
> +.p-0 {
Please check if this style is now required as we have global style for `padding: 0`

2021-06-08 11:20 UTC, ravinderwalkover approved these changes

2021-06-10 04:51 UTC, prateek-giddh approved these changes

2021-06-10 05:46 UTC, merged