shalinee | stage | PO responsive code cherrypick
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8598
Opened 2021-06-26 11:33 UTC by shalinee-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-06-26 11:51 UTC, prateek-giddh requested changes

2021-06-26 11:51 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
> +<<<<<<< HEAD
Improper merge conflict resolution

2021-06-26 11:51 UTC, prateek-giddh commented on apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
> +=======
Improper merge conflict resolution

2021-06-26 12:02 UTC, shalinee-walkover commented
https://app.clickup.com/t/3thkz3
cherry-picked PO responsive code
@shalinee-walkover

2021-06-26 12:03 UTC, shalinee-walkover commented on apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
> +<<<<<<< HEAD
Solved

2021-06-26 12:03 UTC, shalinee-walkover commented on apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
> +=======
Solved

2021-06-28 05:02 UTC, prateek-giddh approved these changes

2021-06-28 05:06 UTC, merged