GIDK-#2hcrq6 | SAGAR | PROD | Owner's email id should be automatically displayed in the Receipient's email id tab of export option.
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8623
Opened 2021-06-28 16:43 UTC by SagarWalkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)
https://app.clickup.com/t/2hcrq6

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-06-29 06:41 UTC, prateek-giddh approved these changes

2021-06-29 11:53 UTC, ravinderwalkover requested changes

2021-06-29 11:53 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
> +        return this.recipients;
is returned value getting used?

2021-07-01 13:02 UTC, ravinderwalkover requested changes

2021-07-01 13:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
> +    public getEmail(): any {
```suggestion
    public getEmail(): void {
```

2021-07-01 13:02 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
> +     * @returns updated recipient value to company email
doesn't return any value

2021-07-01 13:56 UTC, ravinderwalkover approved these changes

2021-07-01 14:03 UTC, merged