GIDK-#2b84ey | Sagar | PROD| User is not able to remove the tax applied on the account group in master
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8626
Opened 2021-06-28 17:02 UTC by SagarWalkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)
https://app.clickup.com/t/2b84ey

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-06-29 06:53 UTC, prateek-giddh approved these changes

2021-06-29 11:45 UTC, ravinderwalkover requested changes

2021-06-29 11:45 UTC, ravinderwalkover commented on apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
> +                        let applicableTaxes = activeGroupTaxHierarchy.applicableTaxes.map(p => p.uniqueName);
add nulity check for this 
```suggestion
                        let applicableTaxes = activeGroupTaxHierarchy?.applicableTaxes.map(p => p.uniqueName);
```

2021-07-01 12:55 UTC, ravinderwalkover approved these changes

2021-07-01 13:33 UTC, merged