Gidk 3ng8jj com branch beta
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8670
Opened 2021-07-02 09:09 UTC by shalinee-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-07-13 10:54 UTC, prateek-giddh requested changes
Do check PROD PR comments

2021-07-13 10:57 UTC, ravinderwalkover requested changes

2021-07-13 10:57 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-2.scss
> +.giddh-no-permissions-error-message {
remove this

2021-07-13 13:24 UTC, prateek-giddh approved these changes

2021-07-15 15:50 UTC, ravinderwalkover approved these changes

2021-07-23 05:03 UTC, merged