Gidk 3ng8jj com branch prod
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8671
Opened 2021-07-02 09:35 UTC by shalinee-walkover

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-07-13 10:48 UTC, prateek-giddh requested changes

2021-07-13 10:48 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
> +    public filterCompanyList(event: any): void {
Please check this method is also present in `primary-sidebar.component.ts`, do remove it from there if unused.

2021-07-13 10:48 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
> +    public changeCompany(selectedCompanyUniqueName: string, selectBranchUniqueName: string, fetchLastState?: boolean) {
Please check this method is also present in `primary-sidebar.component.ts`, do remove it from there if unused.

2021-07-13 10:48 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
> +    private setOrganizationDetails(type: OrganizationType, branchDetails: OrganizationDetails): void {
Please check this method is also present in `primary-sidebar.component.ts`, do remove it from there if unused.

2021-07-13 10:48 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
> +    public refreshCompanies(event: Event): void {
Please check this method is also present in `primary-sidebar.component.ts`, do remove it from there if unused.

2021-07-13 10:48 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
> +    public logout(): void {
Please check this method is also present in `primary-sidebar.component.ts`, do remove it from there if unused.

2021-07-13 10:48 UTC, prateek-giddh commented on apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
> +    public filterBranchList(event: any): void {
Please check a similar method `filterBranch` is also present in `primary-sidebar.component.ts`, do remove it from there if unused.

2021-07-13 10:51 UTC, ravinderwalkover requested changes

2021-07-13 10:51 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-2.scss
> +.giddh-no-permissions-error-message {
need to remove this

2021-07-13 13:23 UTC, prateek-giddh approved these changes

2021-07-15 16:09 UTC, ravinderwalkover approved these changes

2021-07-22 07:24 UTC, ravinderwalkover approved these changes

2021-07-23 05:19 UTC, merged