stage | GIDK-3nfxzv | Aditi | new design of list
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8748
Opened 2021-07-09 08:25 UTC by aditi-tiwari17

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
https://app.clickup.com/t/3nfxzv

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-07-09 13:05 UTC, ravinderwalkover requested changes

2021-07-09 13:05 UTC, ravinderwalkover commented on apps/web-giddh/src/app/services/general.service.ts
> +    public childOf(child, parent): boolean {
Define type of variables

2021-07-09 14:00 UTC, prateek-giddh requested changes

2021-07-12 04:42 UTC, prateek-giddh approved these changes

2021-07-12 05:56 UTC, ravinderwalkover approved these changes

2021-07-12 06:06 UTC, merged