beta | GIDK-3nfxzv | Aditi | new list design changes
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8795
Opened 2021-07-13 10:21 UTC by aditi-tiwari17

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
https://app.clickup.com/t/3nfxzv

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-07-13 13:48 UTC, ravinderwalkover requested changes

2021-07-13 13:48 UTC, ravinderwalkover commented on apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
> +    public toggleSearch(fieldName: string, el: any) {
add return type

2021-07-13 13:48 UTC, ravinderwalkover commented on apps/web-giddh/src/app/contact/contact.component.html
> +                                        <li role="menuitem" (click)="openSmsDialog();">
this should be commented

2021-07-13 13:48 UTC, ravinderwalkover commented on apps/web-giddh/src/app/contact/contact.component.ts
> +        }
add return type for unmatching if condition

2021-07-13 13:48 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> +                <div class="top-content">
for this new html

2021-07-13 13:48 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> +                                <a class="dropdown-item" href="javascript: void 0"
```suggestion
                                <a class="dropdown-item" href="javascript:;"
```

2021-07-13 13:48 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> +                                <a class="dropdown-item" href="javascript: void 0"
```suggestion
                                <a class="dropdown-item" href="javascript:;"
```

2021-07-13 13:48 UTC, ravinderwalkover commented on apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
> +            <div class="top-content">
for this new html

2021-07-14 05:17 UTC, prateek-giddh commented on apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
> +    public toggleSearch(fieldName: string, el: any) {
```suggestion
    public toggleSearch(fieldName: string, el: any): void {
```

2021-07-14 05:53 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> -                            <button *ngIf="!isCompany" id="ddl-newinv" dropdownToggle type="button"
Do check this ngIf should not be removed as we don't allow the user to create or edit in company mode

2021-07-14 06:41 UTC, prateek-giddh commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> -                        <div *ngIf="selectedVoucher === 'purchase'" class="btn-wrapper">
Do check this code block is getting removed for mobile screen

2021-07-14 06:54 UTC, ravinderwalkover approved these changes

2021-07-14 07:15 UTC, prateek-giddh reviewed
Please check

2021-07-14 07:20 UTC, prateek-giddh requested changes
Please check comment https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/8795#discussion_r669333024

2021-07-14 09:16 UTC, prateek-giddh approved these changes

2021-07-14 12:25 UTC, merged