Merge Prod in Stage
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #8858
Opened 2021-07-16 14:30 UTC by prateek-giddh

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2021-07-16 15:43 UTC, ravinderwalkover requested changes

2021-07-16 15:43 UTC, ravinderwalkover commented on apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.ts
> +        this.breakPointObserver.observe([
this is duplicate code. need to remove this

2021-07-17 07:14 UTC, aditi-tiwari17 approved these changes

2021-07-21 07:08 UTC, shalinee-walkover approved these changes

2021-07-22 06:30 UTC, ravinderwalkover approved these changes

2021-07-22 09:52 UTC, ravinderwalkover approved these changes

2021-07-23 07:24 UTC, merged