Ravinder | Beta | Integrating angular material in ledger module
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #9076
Opened 2021-08-11 05:02 UTC by ravinderwalkover

https://app.clickup.com/t/4dfty7

2021-09-07 12:52 UTC, aditi-tiwari17 approved these changes

2021-09-07 13:26 UTC, prateek-giddh requested changes

2021-09-07 13:26 UTC, prateek-giddh commented on apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts
> +     * Call's detect changes method
```suggestion
     * Calls detect changes method
```

2021-09-08 05:17 UTC, prateek-giddh approved these changes

2021-09-08 07:12 UTC, merged