Ravinder | Test | Fixed Ledger and daybook issues
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #9159
Opened 2021-08-23 14:24 UTC by ravinderwalkover

https://app.clickup.com/t/6n147b

2021-08-23 14:32 UTC, aditi-tiwari17 approved these changes

2021-08-24 04:53 UTC, prateek-giddh requested changes

2021-08-24 04:53 UTC, prateek-giddh commented on apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts
> +        if ('advanceSearchRequest' in changes && changes.advanceSearchRequest.currentValue && changes.advanceSearchRequest.currentValue !== changes.advanceSearchRequest.previousValue && changes.advan
```suggestion
        if ('advanceSearchRequest' in changes && changes.advanceSearchRequest.currentValue && changes.advanceSearchRequest.currentValue !== changes.advanceSearchRequest.previousValue && changes.advanceSearchRequest.currentValue.dataToSend?.bsRangeValue) {
```

2021-08-24 05:05 UTC, prateek-giddh approved these changes

2021-08-24 05:05 UTC, merged