Deep | Test | Fixed the issue
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #9442
Opened 2021-10-08 08:48 UTC by deepGiddh

https://app.clickup.com/t/b3z5b4

2021-10-08 08:54 UTC, deepGiddh commented on apps/web-giddh/src/app/store/General/general.reducer.ts
> +            let flattenAccountsArray = [...(state.flattenAccounts ||[])];
flatten Accounts is assigned a null value

2021-10-09 05:41 UTC, ravinderwalkover requested changes

2021-10-09 05:41 UTC, ravinderwalkover commented on apps/web-giddh/src/app/store/General/general.reducer.ts
> +               flattenAccountsArray = flattenAccountsArray.filter(account => account.uniqueName !== action.payload)
```suggestion
               flattenAccountsArray = flattenAccountsArray.filter(account => account.uniqueName !== action.payload);
```

2021-10-09 05:47 UTC, ravinderwalkover commented on apps/web-giddh/src/app/store/General/general.reducer.ts
> +            if(state && state.flattenAccounts){
```suggestion
            if(state?.flattenAccounts){
```

2021-10-09 06:05 UTC, ravinderwalkover approved these changes

2021-10-11 07:48 UTC, merged