Dilpreet | Stage | Fixed 8 bugs of ui exception
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #9835
Opened 2022-02-01 04:49 UTC by dilpreet77

https://app.clickup.com/t/1tewhz

2022-02-01 05:02 UTC, prateek-giddh requested changes

2022-02-01 05:02 UTC, prateek-giddh commented on apps/web-giddh/src/app/ledger/ledger.component.ts
> +                url: Configuration.ApiUrl + LEDGER_API.UPLOAD_FILE?.replace(':companyUniqueName', companyUniqueName),
UPLOAD_FILE is a constant, it can't be null or undefined

2022-02-01 05:02 UTC, prateek-giddh commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +        // listen for new add account utilsx
Please check an extra character is added

2022-02-01 05:32 UTC, ravinderwalkover requested changes

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                                accountType: (res.body.account) ? res.body.account?.type : null,
? is not required since nulity on account is already checked

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                            uniqueName: res.body?.uniqueName,
? is not required since nulity on body is already checked initially

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                            this.getAllAdvanceReceipts(response.account?.uniqueName, response.date);
```suggestion
                            this.getAllAdvanceReceipts(response.account.uniqueName, response.date);
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                uniqueName: (selectedVoucher) ? encodeURIComponent(selectedVoucher?.uniqueName) : (this.selectedInvoice) ? encodeURIComponent(this.selectedInvoice?.uniqueName) : (this.selectedInvoice
```suggestion
                uniqueName: (selectedVoucher) ? encodeURIComponent(selectedVoucher.uniqueName) : (this.selectedInvoice) ? encodeURIComponent(this.selectedInvoice.uniqueName) : (this.selectedInvoiceForDetails) ? encodeURIComponent(this.selectedInvoiceForDetails.uniqueName) : ''
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +            this.store.dispatch(this.invoiceActions.ActionOnInvoice(data?.uniqueName, data));
```suggestion
            this.store.dispatch(this.invoiceActions.ActionOnInvoice(data.uniqueName, data));
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                                v.isSelected = this.generalService?.checkIfValueExistsInArray(this.selectedInvoices, v?.uniqueName);
why added ? here?

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                    if (this.purchaseRecord && this.purchaseRecord?.uniqueName) {
```suggestion
                    if (this.purchaseRecord?.uniqueName) {
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/ledger.component.ts
> +                let blob = this.generalService.base64ToBlob(d?.body?.uploadedFile, `image/${d?.body?.fileType}`, 512);
```suggestion
                let blob = this.generalService.base64ToBlob(d.body?.uploadedFile, `image/${d.body?.fileType}`, 512);
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/ledger.component.ts
>              if (d.status === 'success') {
```suggestion
            if (d?.status === 'success') {
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/ledger.component.ts
> +                download(d?.body.name, blob, `image/${d?.body?.fileType}`)
```suggestion
                download(d.body?.name, blob, `image/${d.body?.fileType}`)
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/ledger/ledger.component.ts
> +                url: Configuration.ApiUrl + LEDGER_API.UPLOAD_FILE?.replace(':companyUniqueName', companyUniqueName),
what's the use of ? here?

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/login/login.component.ts
> +                        switch (user?.provider) {
```suggestion
                        switch (user.provider) {
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/login/login.component.ts
> +                                this.store.dispatch(this.loginAction.signupWithGoogle(user?.token));
```suggestion
                                this.store.dispatch(this.loginAction.signupWithGoogle(user.token));
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    label: o?.name,
? is not required here

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                        this.customerAcList$ = observableOf([{ label: tempSelectedAcc?.name, value: tempSelectedAcc.uniqueName, additional: tempSelectedAcc }]);
? is not required here since nulity check on tempSelectedAcc is already checked

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                        this.customerAcList$ = observableOf([{ label: tempSelectedAcc?.name, value: tempSelectedAcc.uniqueName, additional: tempSelectedAcc }]);
? is not required here since nulity check on tempSelectedAcc is already checked

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                        this.invFormData.voucherDetails.customerName = tempSelectedAcc?.name;
? is not required here since nulity check on tempSelectedAcc is already checked

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                            this.formFields[res.fields[key]?.name] = res?.fields[key];
```suggestion
                            this.formFields[res.fields[key]?.name] = res.fields[key];
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                            this.invFormData.voucherDetails.customerName = item?.name;
? is not required here since nulity check on item is already checked

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                attachedFiles: (this.invFormData.entries[0] && this.invFormData.entries[0]?.attachedFile) ? [this.invFormData.entries[0]?.attachedFile] : [],
```suggestion
                attachedFiles: (this.invFormData.entries[0]?.attachedFile) ? [this.invFormData.entries[0]?.attachedFile] : [],
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +            this.selectedFileName = this.file?.name;
```suggestion
            this.selectedFileName = this.file.name;
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    attachedFiles: (this.invFormData.entries[0] && this.invFormData.entries[0]?.attachedFile) ? [this.invFormData.entries[0]?.attachedFile] : [],
```suggestion
                    attachedFiles: (this.invFormData.entries[0]?.attachedFile) ? [this.invFormData.entries[0]?.attachedFile] : [],
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                entry.otherTaxModal.itemLabel = trx.stockDetails && trx.stockDetails?.name ? trx.accountName + '(' + trx.stockDetails?.name + ')' : trx.accountName;
```suggestion
                entry.otherTaxModal.itemLabel = trx.stockDetails?.name ? trx.accountName + '(' + trx.stockDetails?.name + ')' : trx.accountName;
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    entry.otherTaxModal.appliedOtherTax = { name: tax?.name, uniqueName: tax.uniqueName };
? is not required here since nulity check on tax is already checked

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    entry.otherTaxModal.appliedOtherTax = { name: tax?.name, uniqueName: tax.uniqueName };
? is not required here since nulity check on tax is already checked

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    name: f.discount?.name,
you added ? here but why not for above keys?

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                            name: ta.name || (selectedTax && selectedTax?.name) || ''
```suggestion
                            name: ta.name || selectedTax?.name || ''
```

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    salesTransactionItemClass.stockDetails.name = t.stock?.name;
? is not required here since nulity check on t.stock is already checked

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    discountLedger.name = discount?.name;
you added ? here but why not for above keys?

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    tradeDiscount.discount.name = discountLedger?.name;
you added ? here but why not for above keys?

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                bankAccounts.push({ label: account?.name, value: account.uniqueName, additional: account });
you added ? here but why not for other key?

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                                label: result.stock ? `${result?.name} (${result.stock?.name})` : result?.name,
? is not required here

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                label: result.stock ? `${result?.name} (${result.stock?.name})` : result?.name,
? is not required here

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    label: result.stock ? `${result?.name} (${result?.stock.name})` : result?.name,
? is not required here

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    label: result.stock ? `${result?.name} (${result.stock?.name})` : result?.name,
? is not required here

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                    name: discount?.name,
you added ? here but why not for other keys?

2022-02-01 05:32 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +            data.stateName = data.state?.name;
you added ? here but why not for other key?

2022-02-01 07:39 UTC, ravinderwalkover requested changes

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +        if (this.purchaseRecord && this.purchaseRecord?.uniqueName) {
```suggestion
        if (this.purchaseRecord?.uniqueName) {
```

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                            dueDate: res.body?.dueDate,
we are already checking res.body for nulity, so no need to check here

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +        this.changeStatusInvoiceUniqueName = item?.uniqueName;
is this useful?

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                if (voucher?.voucherNumber === voucherUpdatedDetails?.number) {
```suggestion
                if (voucher?.voucherNumber === voucherUpdatedDetails.number) {
```

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                    if (voucher?.account?.uniqueName !== voucherUpdatedDetails?.account?.uniqueName) {
```suggestion
                    if (voucher?.account?.uniqueName !== voucherUpdatedDetails.account?.uniqueName) {
```

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                        this.voucherData.items[loop].account = voucherUpdatedDetails?.account;
```suggestion
                        this.voucherData.items[loop].account = voucherUpdatedDetails.account;
```

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                                existingInvoices.push(item?.uniqueName);
```suggestion
                                existingInvoices.push(item.uniqueName);
```

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                                if (existingInvoices?.indexOf(invoice) > -1) {
```suggestion
                                if (existingInvoices.indexOf(invoice) > -1) {
```

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> +                                    selectedInvoices?.push(invoice);
```suggestion
                                    selectedInvoices.push(invoice);
```

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                            entry.otherTaxModal.appliedOtherTax = { name: tax?.name, uniqueName: tax.uniqueName };
you added ? for name and not for uniqueName. why?

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                        otherTaxModal.appliedOtherTax = { name: ta?.name, uniqueName: ta.uniqueName };
you added ? for name and not for uniqueName. why? and how ta can be null of undefined here? Explain in detail

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +                label: stateR?.name,
you added ? for name and not for other keys. why?

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +            data.stateCode = data.state?.code;
is this useful?

2022-02-01 07:39 UTC, ravinderwalkover commented on apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> +            data.stateName = data.state?.name;
is this useful?

2022-02-01 08:35 UTC, prateek-giddh approved these changes

2022-02-07 05:47 UTC, ravinderwalkover approved these changes

2022-02-09 12:57 UTC, merged