Dilpreet fixed with proper way
Walkover-Web-Solution/Giddh-New-Angular4-App pull request #9844
Opened 2022-02-01 19:44 UTC by dilpreet77

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2022-02-02 04:53 UTC, prateek-giddh approved these changes

2022-02-02 04:56 UTC, ravinderwalkover approved these changes

2022-02-02 04:56 UTC, ravinderwalkover requested changes

2022-02-02 04:56 UTC, ravinderwalkover commented on apps/web-giddh/src/assets/css/style-2.scss
> +.branch-profile-wrapper {
can we add this css in address-settings.component.scss?

2022-02-07 06:51 UTC, ravinderwalkover approved these changes

2022-02-07 06:51 UTC, merged